package datapro.eibs.beans;

import datapro.eibs.sockets.*;
import java.io.*;
import java.math.*;

import java.util.*;

/**
* Class generated by AS/400 CRTCLASS command from ECL0210DS physical file definition.
* 
* File level identifier is 1130611112849.
* Record format level identifier is 29137C85CD740.
*/

public class ECL0210DSMessage extends MessageRecord
{
  final static String fldnames[] = {
                                     "H01USERID",
                                     "H01PROGRM",
                                     "H01TIMSYS",
                                     "H01SCRCOD",
                                     "H01OPECOD",
                                     "H01FLGMAS",
                                     "H01FLGWK1",
                                     "H01FLGWK2",
                                     "H01FLGWK3",
                                     "E01FECDAN",
                                     "E01FECDME",
                                     "E01FECDDI",
                                     "E01FECHAN",
                                     "E01FECHME",
                                     "E01FECHDI",
                                     "E01TIPOPE",
                                     "E01USERID",
                                     "E01NROINS",
                                     "E01NROCTA",
                                     "E01FECOPE",
                                     "E01USUARI",
                                     "E01TRANSA",
                                     "E01MONTO",
                                     "E01CLIENT",
                                     "E01NRCHIN",
                                     "E01CTADES"
                                   };
  final static String tnames[] = {
                                   "H01USERID",
                                   "H01PROGRM",
                                   "H01TIMSYS",
                                   "H01SCRCOD",
                                   "H01OPECOD",
                                   "H01FLGMAS",
                                   "H01FLGWK1",
                                   "H01FLGWK2",
                                   "H01FLGWK3",
                                   "E01FECDAN",
                                   "E01FECDME",
                                   "E01FECDDI",
                                   "E01FECHAN",
                                   "E01FECHME",
                                   "E01FECHDI",
                                   "E01TIPOPE",
                                   "E01USERID",
                                   "E01NROINS",
                                   "E01NROCTA",
                                   "E01FECOPE",
                                   "E01USUARI",
                                   "E01TRANSA",
                                   "E01MONTO",
                                   "E01CLIENT",
                                   "E01NRCHIN",
                                   "E01CTADES"
                                 };
  final static String fid = "1130611112849";
  final static String rid = "29137C85CD740";
  final static String fmtname = "ECL0210DS";
  final int FIELDCOUNT = 26;
  private static Hashtable tlookup = new Hashtable();
  private CharacterField fieldH01USERID = null;
  private CharacterField fieldH01PROGRM = null;
  private CharacterField fieldH01TIMSYS = null;
  private CharacterField fieldH01SCRCOD = null;
  private CharacterField fieldH01OPECOD = null;
  private CharacterField fieldH01FLGMAS = null;
  private CharacterField fieldH01FLGWK1 = null;
  private CharacterField fieldH01FLGWK2 = null;
  private CharacterField fieldH01FLGWK3 = null;
  private DecimalField fieldE01FECDAN = null;
  private DecimalField fieldE01FECDME = null;
  private DecimalField fieldE01FECDDI = null;
  private DecimalField fieldE01FECHAN = null;
  private DecimalField fieldE01FECHME = null;
  private DecimalField fieldE01FECHDI = null;
  private DecimalField fieldE01TIPOPE = null;
  private CharacterField fieldE01USERID = null;
  private CharacterField fieldE01NROINS = null;
  private CharacterField fieldE01NROCTA = null;
  private DecimalField fieldE01FECOPE = null;
  private CharacterField fieldE01USUARI = null;
  private DecimalField fieldE01TRANSA = null;
  private DecimalField fieldE01MONTO = null;
  private CharacterField fieldE01CLIENT = null;
  private DecimalField fieldE01NRCHIN = null;
  private CharacterField fieldE01CTADES = null;

  /**
  * Constructor for ECL0210DSMessage.
  */
  public ECL0210DSMessage()
  {
    createFields();
    initialize();
  }

  /**
  * Create fields for this message.
  * This method implements the abstract method in the MessageRecord superclass.
  */
  protected void createFields()
  {
    recordsize = 200;
    fileid = fid;
    recordid = rid;
    message = new byte[getByteLength()];
    formatname = fmtname;
    fieldnames = fldnames;
    tagnames = tnames;
    fields = new MessageField[FIELDCOUNT];

    fields[0] = fieldH01USERID =
    new CharacterField(message, HEADERSIZE + 0, 10, "H01USERID");
    fields[1] = fieldH01PROGRM =
    new CharacterField(message, HEADERSIZE + 10, 10, "H01PROGRM");
    fields[2] = fieldH01TIMSYS =
    new CharacterField(message, HEADERSIZE + 20, 12, "H01TIMSYS");
    fields[3] = fieldH01SCRCOD =
    new CharacterField(message, HEADERSIZE + 32, 2, "H01SCRCOD");
    fields[4] = fieldH01OPECOD =
    new CharacterField(message, HEADERSIZE + 34, 4, "H01OPECOD");
    fields[5] = fieldH01FLGMAS =
    new CharacterField(message, HEADERSIZE + 38, 1, "H01FLGMAS");
    fields[6] = fieldH01FLGWK1 =
    new CharacterField(message, HEADERSIZE + 39, 1, "H01FLGWK1");
    fields[7] = fieldH01FLGWK2 =
    new CharacterField(message, HEADERSIZE + 40, 1, "H01FLGWK2");
    fields[8] = fieldH01FLGWK3 =
    new CharacterField(message, HEADERSIZE + 41, 1, "H01FLGWK3");
    fields[9] = fieldE01FECDAN =
    new DecimalField(message, HEADERSIZE + 42, 5, 0, "E01FECDAN");
    fields[10] = fieldE01FECDME =
    new DecimalField(message, HEADERSIZE + 47, 3, 0, "E01FECDME");
    fields[11] = fieldE01FECDDI =
    new DecimalField(message, HEADERSIZE + 50, 3, 0, "E01FECDDI");
    fields[12] = fieldE01FECHAN =
    new DecimalField(message, HEADERSIZE + 53, 5, 0, "E01FECHAN");
    fields[13] = fieldE01FECHME =
    new DecimalField(message, HEADERSIZE + 58, 3, 0, "E01FECHME");
    fields[14] = fieldE01FECHDI =
    new DecimalField(message, HEADERSIZE + 61, 3, 0, "E01FECHDI");
    fields[15] = fieldE01TIPOPE =
    new DecimalField(message, HEADERSIZE + 64, 3, 0, "E01TIPOPE");
    fields[16] = fieldE01USERID =
    new CharacterField(message, HEADERSIZE + 67, 10, "E01USERID");
    fields[17] = fieldE01NROINS =
    new CharacterField(message, HEADERSIZE + 77, 20, "E01NROINS");
    fields[18] = fieldE01NROCTA =
    new CharacterField(message, HEADERSIZE + 97, 20, "E01NROCTA");
    fields[19] = fieldE01FECOPE =
    new DecimalField(message, HEADERSIZE + 117, 9, 0, "E01FECOPE");
    fields[20] = fieldE01USUARI =
    new CharacterField(message, HEADERSIZE + 126, 10, "E01USUARI");
    fields[21] = fieldE01TRANSA =
    new DecimalField(message, HEADERSIZE + 136, 3, 0, "E01TRANSA");
    fields[22] = fieldE01MONTO =
    new DecimalField(message, HEADERSIZE + 139, 17, 2, "E01MONTO");
    fields[23] = fieldE01CLIENT =
    new CharacterField(message, HEADERSIZE + 156, 10, "E01CLIENT");
    fields[24] = fieldE01NRCHIN =
    new DecimalField(message, HEADERSIZE + 166, 14, 0, "E01NRCHIN");
    fields[25] = fieldE01CTADES =
    new CharacterField(message, HEADERSIZE + 180, 20, "E01CTADES");

    synchronized (tlookup)
    {
      if (tlookup.isEmpty())
      {
        for (int i = 0; i < tnames.length; i++)
          tlookup.put(tnames[i], new Integer(i));
      }
    }

    taglookup = tlookup;
  }

  /**
  * Set field H01USERID using a String value.
  */
  public void setH01USERID(String newvalue)
  {
    fieldH01USERID.setString(newvalue);
  }

  /**
  * Get value of field H01USERID as a String.
  */
  public String getH01USERID()
  {
    return fieldH01USERID.getString();
  }

  /**
  * Set field H01PROGRM using a String value.
  */
  public void setH01PROGRM(String newvalue)
  {
    fieldH01PROGRM.setString(newvalue);
  }

  /**
  * Get value of field H01PROGRM as a String.
  */
  public String getH01PROGRM()
  {
    return fieldH01PROGRM.getString();
  }

  /**
  * Set field H01TIMSYS using a String value.
  */
  public void setH01TIMSYS(String newvalue)
  {
    fieldH01TIMSYS.setString(newvalue);
  }

  /**
  * Get value of field H01TIMSYS as a String.
  */
  public String getH01TIMSYS()
  {
    return fieldH01TIMSYS.getString();
  }

  /**
  * Set field H01SCRCOD using a String value.
  */
  public void setH01SCRCOD(String newvalue)
  {
    fieldH01SCRCOD.setString(newvalue);
  }

  /**
  * Get value of field H01SCRCOD as a String.
  */
  public String getH01SCRCOD()
  {
    return fieldH01SCRCOD.getString();
  }

  /**
  * Set field H01OPECOD using a String value.
  */
  public void setH01OPECOD(String newvalue)
  {
    fieldH01OPECOD.setString(newvalue);
  }

  /**
  * Get value of field H01OPECOD as a String.
  */
  public String getH01OPECOD()
  {
    return fieldH01OPECOD.getString();
  }

  /**
  * Set field H01FLGMAS using a String value.
  */
  public void setH01FLGMAS(String newvalue)
  {
    fieldH01FLGMAS.setString(newvalue);
  }

  /**
  * Get value of field H01FLGMAS as a String.
  */
  public String getH01FLGMAS()
  {
    return fieldH01FLGMAS.getString();
  }

  /**
  * Set field H01FLGWK1 using a String value.
  */
  public void setH01FLGWK1(String newvalue)
  {
    fieldH01FLGWK1.setString(newvalue);
  }

  /**
  * Get value of field H01FLGWK1 as a String.
  */
  public String getH01FLGWK1()
  {
    return fieldH01FLGWK1.getString();
  }

  /**
  * Set field H01FLGWK2 using a String value.
  */
  public void setH01FLGWK2(String newvalue)
  {
    fieldH01FLGWK2.setString(newvalue);
  }

  /**
  * Get value of field H01FLGWK2 as a String.
  */
  public String getH01FLGWK2()
  {
    return fieldH01FLGWK2.getString();
  }

  /**
  * Set field H01FLGWK3 using a String value.
  */
  public void setH01FLGWK3(String newvalue)
  {
    fieldH01FLGWK3.setString(newvalue);
  }

  /**
  * Get value of field H01FLGWK3 as a String.
  */
  public String getH01FLGWK3()
  {
    return fieldH01FLGWK3.getString();
  }

  /**
  * Set field E01FECDAN using a String value.
  */
  public void setE01FECDAN(String newvalue)
  {
    fieldE01FECDAN.setString(newvalue);
  }

  /**
  * Get value of field E01FECDAN as a String.
  */
  public String getE01FECDAN()
  {
    return fieldE01FECDAN.getString();
  }

  /**
  * Set numeric field E01FECDAN using a BigDecimal value.
  */
  public void setE01FECDAN(BigDecimal newvalue)
  {
    fieldE01FECDAN.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01FECDAN as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01FECDAN()
  {
    return fieldE01FECDAN.getBigDecimal();
  }

  /**
  * Set field E01FECDME using a String value.
  */
  public void setE01FECDME(String newvalue)
  {
    fieldE01FECDME.setString(newvalue);
  }

  /**
  * Get value of field E01FECDME as a String.
  */
  public String getE01FECDME()
  {
    return fieldE01FECDME.getString();
  }

  /**
  * Set numeric field E01FECDME using a BigDecimal value.
  */
  public void setE01FECDME(BigDecimal newvalue)
  {
    fieldE01FECDME.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01FECDME as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01FECDME()
  {
    return fieldE01FECDME.getBigDecimal();
  }

  /**
  * Set field E01FECDDI using a String value.
  */
  public void setE01FECDDI(String newvalue)
  {
    fieldE01FECDDI.setString(newvalue);
  }

  /**
  * Get value of field E01FECDDI as a String.
  */
  public String getE01FECDDI()
  {
    return fieldE01FECDDI.getString();
  }

  /**
  * Set numeric field E01FECDDI using a BigDecimal value.
  */
  public void setE01FECDDI(BigDecimal newvalue)
  {
    fieldE01FECDDI.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01FECDDI as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01FECDDI()
  {
    return fieldE01FECDDI.getBigDecimal();
  }

  /**
  * Set field E01FECHAN using a String value.
  */
  public void setE01FECHAN(String newvalue)
  {
    fieldE01FECHAN.setString(newvalue);
  }

  /**
  * Get value of field E01FECHAN as a String.
  */
  public String getE01FECHAN()
  {
    return fieldE01FECHAN.getString();
  }

  /**
  * Set numeric field E01FECHAN using a BigDecimal value.
  */
  public void setE01FECHAN(BigDecimal newvalue)
  {
    fieldE01FECHAN.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01FECHAN as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01FECHAN()
  {
    return fieldE01FECHAN.getBigDecimal();
  }

  /**
  * Set field E01FECHME using a String value.
  */
  public void setE01FECHME(String newvalue)
  {
    fieldE01FECHME.setString(newvalue);
  }

  /**
  * Get value of field E01FECHME as a String.
  */
  public String getE01FECHME()
  {
    return fieldE01FECHME.getString();
  }

  /**
  * Set numeric field E01FECHME using a BigDecimal value.
  */
  public void setE01FECHME(BigDecimal newvalue)
  {
    fieldE01FECHME.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01FECHME as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01FECHME()
  {
    return fieldE01FECHME.getBigDecimal();
  }

  /**
  * Set field E01FECHDI using a String value.
  */
  public void setE01FECHDI(String newvalue)
  {
    fieldE01FECHDI.setString(newvalue);
  }

  /**
  * Get value of field E01FECHDI as a String.
  */
  public String getE01FECHDI()
  {
    return fieldE01FECHDI.getString();
  }

  /**
  * Set numeric field E01FECHDI using a BigDecimal value.
  */
  public void setE01FECHDI(BigDecimal newvalue)
  {
    fieldE01FECHDI.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01FECHDI as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01FECHDI()
  {
    return fieldE01FECHDI.getBigDecimal();
  }

  /**
  * Set field E01TIPOPE using a String value.
  */
  public void setE01TIPOPE(String newvalue)
  {
    fieldE01TIPOPE.setString(newvalue);
  }

  /**
  * Get value of field E01TIPOPE as a String.
  */
  public String getE01TIPOPE()
  {
    return fieldE01TIPOPE.getString();
  }

  /**
  * Set numeric field E01TIPOPE using a BigDecimal value.
  */
  public void setE01TIPOPE(BigDecimal newvalue)
  {
    fieldE01TIPOPE.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01TIPOPE as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01TIPOPE()
  {
    return fieldE01TIPOPE.getBigDecimal();
  }

  /**
  * Set field E01USERID using a String value.
  */
  public void setE01USERID(String newvalue)
  {
    fieldE01USERID.setString(newvalue);
  }

  /**
  * Get value of field E01USERID as a String.
  */
  public String getE01USERID()
  {
    return fieldE01USERID.getString();
  }

  /**
  * Set field E01NROINS using a String value.
  */
  public void setE01NROINS(String newvalue)
  {
    fieldE01NROINS.setString(newvalue);
  }

  /**
  * Get value of field E01NROINS as a String.
  */
  public String getE01NROINS()
  {
    return fieldE01NROINS.getString();
  }

  /**
  * Set field E01NROCTA using a String value.
  */
  public void setE01NROCTA(String newvalue)
  {
    fieldE01NROCTA.setString(newvalue);
  }

  /**
  * Get value of field E01NROCTA as a String.
  */
  public String getE01NROCTA()
  {
    return fieldE01NROCTA.getString();
  }

  /**
  * Set field E01FECOPE using a String value.
  */
  public void setE01FECOPE(String newvalue)
  {
    fieldE01FECOPE.setString(newvalue);
  }

  /**
  * Get value of field E01FECOPE as a String.
  */
  public String getE01FECOPE()
  {
    return fieldE01FECOPE.getString();
  }

  /**
  * Set numeric field E01FECOPE using a BigDecimal value.
  */
  public void setE01FECOPE(BigDecimal newvalue)
  {
    fieldE01FECOPE.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01FECOPE as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01FECOPE()
  {
    return fieldE01FECOPE.getBigDecimal();
  }

  /**
  * Set field E01USUARI using a String value.
  */
  public void setE01USUARI(String newvalue)
  {
    fieldE01USUARI.setString(newvalue);
  }

  /**
  * Get value of field E01USUARI as a String.
  */
  public String getE01USUARI()
  {
    return fieldE01USUARI.getString();
  }

  /**
  * Set field E01TRANSA using a String value.
  */
  public void setE01TRANSA(String newvalue)
  {
    fieldE01TRANSA.setString(newvalue);
  }

  /**
  * Get value of field E01TRANSA as a String.
  */
  public String getE01TRANSA()
  {
    return fieldE01TRANSA.getString();
  }

  /**
  * Set numeric field E01TRANSA using a BigDecimal value.
  */
  public void setE01TRANSA(BigDecimal newvalue)
  {
    fieldE01TRANSA.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01TRANSA as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01TRANSA()
  {
    return fieldE01TRANSA.getBigDecimal();
  }

  /**
  * Set field E01MONTO using a String value.
  */
  public void setE01MONTO(String newvalue)
  {
    fieldE01MONTO.setString(newvalue);
  }

  /**
  * Get value of field E01MONTO as a String.
  */
  public String getE01MONTO()
  {
    return fieldE01MONTO.getString();
  }

  /**
  * Set numeric field E01MONTO using a BigDecimal value.
  */
  public void setE01MONTO(BigDecimal newvalue)
  {
    fieldE01MONTO.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01MONTO as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01MONTO()
  {
    return fieldE01MONTO.getBigDecimal();
  }

  /**
  * Set field E01CLIENT using a String value.
  */
  public void setE01CLIENT(String newvalue)
  {
    fieldE01CLIENT.setString(newvalue);
  }

  /**
  * Get value of field E01CLIENT as a String.
  */
  public String getE01CLIENT()
  {
    return fieldE01CLIENT.getString();
  }

  /**
  * Set field E01NRCHIN using a String value.
  */
  public void setE01NRCHIN(String newvalue)
  {
    fieldE01NRCHIN.setString(newvalue);
  }

  /**
  * Get value of field E01NRCHIN as a String.
  */
  public String getE01NRCHIN()
  {
    return fieldE01NRCHIN.getString();
  }

  /**
  * Set numeric field E01NRCHIN using a BigDecimal value.
  */
  public void setE01NRCHIN(BigDecimal newvalue)
  {
    fieldE01NRCHIN.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01NRCHIN as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01NRCHIN()
  {
    return fieldE01NRCHIN.getBigDecimal();
  }

  /**
  * Set field E01CTADES using a String value.
  */
  public void setE01CTADES(String newvalue)
  {
    fieldE01CTADES.setString(newvalue);
  }

  /**
  * Get value of field E01CTADES as a String.
  */
  public String getE01CTADES()
  {
    return fieldE01CTADES.getString();
  }

}
