package datapro.eibs.beans;

import datapro.eibs.sockets.*;
import java.io.*;
import java.math.*;

import java.util.*;

/**
* Class generated by AS/400 CRTCLASS command from ECO105005 physical file definition.
* 
* File level identifier is 1150306082649.
* Record format level identifier is 4ADD3AC3AB876.
*/

public class ECO105005Message extends MessageRecord
{
  final static String fldnames[] = {
                                     "H05USERID",
                                     "H05PROGRM",
                                     "H05TIMSYS",
                                     "H05SCRCOD",
                                     "H05OPECOD",
                                     "H05FLGMAS",
                                     "H05FLGWK1",
                                     "H05FLGWK2",
                                     "H05FLGWK3",
                                     "H05IPADDR",
                                     "H05TABSEC",
                                     "E05CRT",
                                     "D05CRT",
                                     "E05OPE",
                                     "E05RCRBNK",
                                     "E05RCRCUN",
                                     "E05RCRNUM",
                                     "E05RCRDCL",
                                     "E05RCRIDN",
                                     "E05RCRCRF",
                                     "E05RCRDRF",
                                     "E05RCRSQR",
                                     "E05RCRIRA",
                                     "E05RCRICA",
                                     "E05RCRIOR",
                                     "E05RCRTDR",
                                     "E05RCRLRC",
                                     "E05RCRCVR",
                                     "E05RCRDVR",
                                     "E05RCRLVR",
                                     "E05RCRDLV",
                                     "E05RCRVMT",
                                     "E05RCRVXT",
                                     "E05RCRTDS",
                                     "E05RCRCNL",
                                     "E05RCRFCN",
                                     "E05RCRDCN",
                                     "E05RCRVIM",
                                     "E05RCRVID",
                                     "E05RCRVIY",
                                     "E05RCRVFM",
                                     "E05RCRVFD",
                                     "E05RCRVFY",
                                     "E05RCRCMM",
                                     "E05RCRCDD",
                                     "E05RCRCYY",
                                     "E05RCRCTM",
                                     "E05RCRCUS",
                                     "E05RCRAMM",
                                     "E05RCRADD",
                                     "E05RCRAYY",
                                     "E05RCRATM",
                                     "E05RCRAUS",
                                     "E05RCRMMM",
                                     "E05RCRMDD",
                                     "E05RCRMYY",
                                     "E05RCRMTM",
                                     "E05RCRMUS",
                                     "F05CRF",
                                     "F05IRA",
                                     "F05ICA",
                                     "F05IOR",
                                     "F05TDR",
                                     "F05LRC",
                                     "F05CVR",
                                     "F05LVR",
                                     "F05VMT",
                                     "F05VXT",
                                     "F05TDS",
                                     "F05CNL",
                                     "F05VIR",
                                     "F05VFR",
                                     "E05APR",
                                     "E05NUMREC",
                                     "E05INDOPE"
                                   };
  final static String tnames[] = {
                                   "H05USERID",
                                   "H05PROGRM",
                                   "H05TIMSYS",
                                   "H05SCRCOD",
                                   "H05OPECOD",
                                   "H05FLGMAS",
                                   "H05FLGWK1",
                                   "H05FLGWK2",
                                   "H05FLGWK3",
                                   "H05IPADDR",
                                   "H05TABSEC",
                                   "E05CRT",
                                   "D05CRT",
                                   "E05OPE",
                                   "E05RCRBNK",
                                   "E05RCRCUN",
                                   "E05RCRNUM",
                                   "E05RCRDCL",
                                   "E05RCRIDN",
                                   "E05RCRCRF",
                                   "E05RCRDRF",
                                   "E05RCRSQR",
                                   "E05RCRIRA",
                                   "E05RCRICA",
                                   "E05RCRIOR",
                                   "E05RCRTDR",
                                   "E05RCRLRC",
                                   "E05RCRCVR",
                                   "E05RCRDVR",
                                   "E05RCRLVR",
                                   "E05RCRDLV",
                                   "E05RCRVMT",
                                   "E05RCRVXT",
                                   "E05RCRTDS",
                                   "E05RCRCNL",
                                   "E05RCRFCN",
                                   "E05RCRDCN",
                                   "E05RCRVIM",
                                   "E05RCRVID",
                                   "E05RCRVIY",
                                   "E05RCRVFM",
                                   "E05RCRVFD",
                                   "E05RCRVFY",
                                   "E05RCRCMM",
                                   "E05RCRCDD",
                                   "E05RCRCYY",
                                   "E05RCRCTM",
                                   "E05RCRCUS",
                                   "E05RCRAMM",
                                   "E05RCRADD",
                                   "E05RCRAYY",
                                   "E05RCRATM",
                                   "E05RCRAUS",
                                   "E05RCRMMM",
                                   "E05RCRMDD",
                                   "E05RCRMYY",
                                   "E05RCRMTM",
                                   "E05RCRMUS",
                                   "F05CRF",
                                   "F05IRA",
                                   "F05ICA",
                                   "F05IOR",
                                   "F05TDR",
                                   "F05LRC",
                                   "F05CVR",
                                   "F05LVR",
                                   "F05VMT",
                                   "F05VXT",
                                   "F05TDS",
                                   "F05CNL",
                                   "F05VIR",
                                   "F05VFR",
                                   "E05APR",
                                   "E05NUMREC",
                                   "E05INDOPE"
                                 };
  final static String fid = "1150306082649";
  final static String rid = "4ADD3AC3AB876";
  final static String fmtname = "ECO105005";
  final int FIELDCOUNT = 75;
  private static Hashtable tlookup = new Hashtable();
  private CharacterField fieldH05USERID = null;
  private CharacterField fieldH05PROGRM = null;
  private CharacterField fieldH05TIMSYS = null;
  private CharacterField fieldH05SCRCOD = null;
  private CharacterField fieldH05OPECOD = null;
  private CharacterField fieldH05FLGMAS = null;
  private CharacterField fieldH05FLGWK1 = null;
  private CharacterField fieldH05FLGWK2 = null;
  private CharacterField fieldH05FLGWK3 = null;
  private CharacterField fieldH05IPADDR = null;
  private CharacterField fieldH05TABSEC = null;
  private CharacterField fieldE05CRT = null;
  private CharacterField fieldD05CRT = null;
  private CharacterField fieldE05OPE = null;
  private CharacterField fieldE05RCRBNK = null;
  private DecimalField fieldE05RCRCUN = null;
  private DecimalField fieldE05RCRNUM = null;
  private CharacterField fieldE05RCRDCL = null;
  private CharacterField fieldE05RCRIDN = null;
  private CharacterField fieldE05RCRCRF = null;
  private CharacterField fieldE05RCRDRF = null;
  private DecimalField fieldE05RCRSQR = null;
  private CharacterField fieldE05RCRIRA = null;
  private CharacterField fieldE05RCRICA = null;
  private CharacterField fieldE05RCRIOR = null;
  private CharacterField fieldE05RCRTDR = null;
  private DecimalField fieldE05RCRLRC = null;
  private CharacterField fieldE05RCRCVR = null;
  private CharacterField fieldE05RCRDVR = null;
  private CharacterField fieldE05RCRLVR = null;
  private CharacterField fieldE05RCRDLV = null;
  private DecimalField fieldE05RCRVMT = null;
  private DecimalField fieldE05RCRVXT = null;
  private CharacterField fieldE05RCRTDS = null;
  private CharacterField fieldE05RCRCNL = null;
  private CharacterField fieldE05RCRFCN = null;
  private CharacterField fieldE05RCRDCN = null;
  private DecimalField fieldE05RCRVIM = null;
  private DecimalField fieldE05RCRVID = null;
  private DecimalField fieldE05RCRVIY = null;
  private DecimalField fieldE05RCRVFM = null;
  private DecimalField fieldE05RCRVFD = null;
  private DecimalField fieldE05RCRVFY = null;
  private DecimalField fieldE05RCRCMM = null;
  private DecimalField fieldE05RCRCDD = null;
  private DecimalField fieldE05RCRCYY = null;
  private CharacterField fieldE05RCRCTM = null;
  private CharacterField fieldE05RCRCUS = null;
  private DecimalField fieldE05RCRAMM = null;
  private DecimalField fieldE05RCRADD = null;
  private DecimalField fieldE05RCRAYY = null;
  private CharacterField fieldE05RCRATM = null;
  private CharacterField fieldE05RCRAUS = null;
  private DecimalField fieldE05RCRMMM = null;
  private DecimalField fieldE05RCRMDD = null;
  private DecimalField fieldE05RCRMYY = null;
  private CharacterField fieldE05RCRMTM = null;
  private CharacterField fieldE05RCRMUS = null;
  private CharacterField fieldF05CRF = null;
  private CharacterField fieldF05IRA = null;
  private CharacterField fieldF05ICA = null;
  private CharacterField fieldF05IOR = null;
  private CharacterField fieldF05TDR = null;
  private CharacterField fieldF05LRC = null;
  private CharacterField fieldF05CVR = null;
  private CharacterField fieldF05LVR = null;
  private CharacterField fieldF05VMT = null;
  private CharacterField fieldF05VXT = null;
  private CharacterField fieldF05TDS = null;
  private CharacterField fieldF05CNL = null;
  private CharacterField fieldF05VIR = null;
  private CharacterField fieldF05VFR = null;
  private CharacterField fieldE05APR = null;
  private DecimalField fieldE05NUMREC = null;
  private CharacterField fieldE05INDOPE = null;

  /**
  * Constructor for ECO105005Message.
  */
  public ECO105005Message()
  {
    createFields();
    initialize();
  }

  /**
  * Create fields for this message.
  * This method implements the abstract method in the MessageRecord superclass.
  */
  protected void createFields()
  {
    recordsize = 2190;
    fileid = fid;
    recordid = rid;
    message = new byte[getByteLength()];
    formatname = fmtname;
    fieldnames = fldnames;
    tagnames = tnames;
    fields = new MessageField[FIELDCOUNT];

    fields[0] = fieldH05USERID =
    new CharacterField(message, HEADERSIZE + 0, 10, "H05USERID");
    fields[1] = fieldH05PROGRM =
    new CharacterField(message, HEADERSIZE + 10, 10, "H05PROGRM");
    fields[2] = fieldH05TIMSYS =
    new CharacterField(message, HEADERSIZE + 20, 12, "H05TIMSYS");
    fields[3] = fieldH05SCRCOD =
    new CharacterField(message, HEADERSIZE + 32, 2, "H05SCRCOD");
    fields[4] = fieldH05OPECOD =
    new CharacterField(message, HEADERSIZE + 34, 4, "H05OPECOD");
    fields[5] = fieldH05FLGMAS =
    new CharacterField(message, HEADERSIZE + 38, 1, "H05FLGMAS");
    fields[6] = fieldH05FLGWK1 =
    new CharacterField(message, HEADERSIZE + 39, 1, "H05FLGWK1");
    fields[7] = fieldH05FLGWK2 =
    new CharacterField(message, HEADERSIZE + 40, 1, "H05FLGWK2");
    fields[8] = fieldH05FLGWK3 =
    new CharacterField(message, HEADERSIZE + 41, 1, "H05FLGWK3");
    fields[9] = fieldH05IPADDR =
    new CharacterField(message, HEADERSIZE + 42, 25, "H05IPADDR");
    fields[10] = fieldH05TABSEC =
    new CharacterField(message, HEADERSIZE + 67, 20, "H05TABSEC");
    fields[11] = fieldE05CRT =
    new CharacterField(message, HEADERSIZE + 87, 1, "E05CRT");
    fields[12] = fieldD05CRT =
    new CharacterField(message, HEADERSIZE + 88, 45, "D05CRT");
    fields[13] = fieldE05OPE =
    new CharacterField(message, HEADERSIZE + 133, 2, "E05OPE");
    fields[14] = fieldE05RCRBNK =
    new CharacterField(message, HEADERSIZE + 135, 2, "E05RCRBNK");
    fields[15] = fieldE05RCRCUN =
    new DecimalField(message, HEADERSIZE + 137, 10, 0, "E05RCRCUN");
    fields[16] = fieldE05RCRNUM =
    new DecimalField(message, HEADERSIZE + 147, 13, 0, "E05RCRNUM");
    fields[17] = fieldE05RCRDCL =
    new CharacterField(message, HEADERSIZE + 160, 60, "E05RCRDCL");
    fields[18] = fieldE05RCRIDN =
    new CharacterField(message, HEADERSIZE + 220, 25, "E05RCRIDN");
    fields[19] = fieldE05RCRCRF =
    new CharacterField(message, HEADERSIZE + 245, 4, "E05RCRCRF");
    fields[20] = fieldE05RCRDRF =
    new CharacterField(message, HEADERSIZE + 249, 45, "E05RCRDRF");
    fields[21] = fieldE05RCRSQR =
    new DecimalField(message, HEADERSIZE + 294, 3, 0, "E05RCRSQR");
    fields[22] = fieldE05RCRIRA =
    new CharacterField(message, HEADERSIZE + 297, 1, "E05RCRIRA");
    fields[23] = fieldE05RCRICA =
    new CharacterField(message, HEADERSIZE + 298, 1, "E05RCRICA");
    fields[24] = fieldE05RCRIOR =
    new CharacterField(message, HEADERSIZE + 299, 1, "E05RCRIOR");
    fields[25] = fieldE05RCRTDR =
    new CharacterField(message, HEADERSIZE + 300, 25, "E05RCRTDR");
    fields[26] = fieldE05RCRLRC =
    new DecimalField(message, HEADERSIZE + 325, 5, 0, "E05RCRLRC");
    fields[27] = fieldE05RCRCVR =
    new CharacterField(message, HEADERSIZE + 330, 4, "E05RCRCVR");
    fields[28] = fieldE05RCRDVR =
    new CharacterField(message, HEADERSIZE + 334, 45, "E05RCRDVR");
    fields[29] = fieldE05RCRLVR =
    new CharacterField(message, HEADERSIZE + 379, 4, "E05RCRLVR");
    fields[30] = fieldE05RCRDLV =
    new CharacterField(message, HEADERSIZE + 383, 45, "E05RCRDLV");
    fields[31] = fieldE05RCRVMT =
    new DecimalField(message, HEADERSIZE + 428, 19, 2, "E05RCRVMT");
    fields[32] = fieldE05RCRVXT =
    new DecimalField(message, HEADERSIZE + 447, 19, 2, "E05RCRVXT");
    fields[33] = fieldE05RCRTDS =
    new CharacterField(message, HEADERSIZE + 466, 25, "E05RCRTDS");
    fields[34] = fieldE05RCRCNL =
    new CharacterField(message, HEADERSIZE + 491, 48, "E05RCRCNL");
    fields[35] = fieldE05RCRFCN =
    new CharacterField(message, HEADERSIZE + 539, 24, "E05RCRFCN");
    fields[36] = fieldE05RCRDCN =
    new CharacterField(message, HEADERSIZE + 563, 1440, "E05RCRDCN");
    fields[37] = fieldE05RCRVIM =
    new DecimalField(message, HEADERSIZE + 2003, 3, 0, "E05RCRVIM");
    fields[38] = fieldE05RCRVID =
    new DecimalField(message, HEADERSIZE + 2006, 3, 0, "E05RCRVID");
    fields[39] = fieldE05RCRVIY =
    new DecimalField(message, HEADERSIZE + 2009, 5, 0, "E05RCRVIY");
    fields[40] = fieldE05RCRVFM =
    new DecimalField(message, HEADERSIZE + 2014, 3, 0, "E05RCRVFM");
    fields[41] = fieldE05RCRVFD =
    new DecimalField(message, HEADERSIZE + 2017, 3, 0, "E05RCRVFD");
    fields[42] = fieldE05RCRVFY =
    new DecimalField(message, HEADERSIZE + 2020, 5, 0, "E05RCRVFY");
    fields[43] = fieldE05RCRCMM =
    new DecimalField(message, HEADERSIZE + 2025, 3, 0, "E05RCRCMM");
    fields[44] = fieldE05RCRCDD =
    new DecimalField(message, HEADERSIZE + 2028, 3, 0, "E05RCRCDD");
    fields[45] = fieldE05RCRCYY =
    new DecimalField(message, HEADERSIZE + 2031, 5, 0, "E05RCRCYY");
    fields[46] = fieldE05RCRCTM =
    new CharacterField(message, HEADERSIZE + 2036, 26, "E05RCRCTM");
    fields[47] = fieldE05RCRCUS =
    new CharacterField(message, HEADERSIZE + 2062, 10, "E05RCRCUS");
    fields[48] = fieldE05RCRAMM =
    new DecimalField(message, HEADERSIZE + 2072, 3, 0, "E05RCRAMM");
    fields[49] = fieldE05RCRADD =
    new DecimalField(message, HEADERSIZE + 2075, 3, 0, "E05RCRADD");
    fields[50] = fieldE05RCRAYY =
    new DecimalField(message, HEADERSIZE + 2078, 5, 0, "E05RCRAYY");
    fields[51] = fieldE05RCRATM =
    new CharacterField(message, HEADERSIZE + 2083, 26, "E05RCRATM");
    fields[52] = fieldE05RCRAUS =
    new CharacterField(message, HEADERSIZE + 2109, 10, "E05RCRAUS");
    fields[53] = fieldE05RCRMMM =
    new DecimalField(message, HEADERSIZE + 2119, 3, 0, "E05RCRMMM");
    fields[54] = fieldE05RCRMDD =
    new DecimalField(message, HEADERSIZE + 2122, 3, 0, "E05RCRMDD");
    fields[55] = fieldE05RCRMYY =
    new DecimalField(message, HEADERSIZE + 2125, 5, 0, "E05RCRMYY");
    fields[56] = fieldE05RCRMTM =
    new CharacterField(message, HEADERSIZE + 2130, 26, "E05RCRMTM");
    fields[57] = fieldE05RCRMUS =
    new CharacterField(message, HEADERSIZE + 2156, 10, "E05RCRMUS");
    fields[58] = fieldF05CRF =
    new CharacterField(message, HEADERSIZE + 2166, 1, "F05CRF");
    fields[59] = fieldF05IRA =
    new CharacterField(message, HEADERSIZE + 2167, 1, "F05IRA");
    fields[60] = fieldF05ICA =
    new CharacterField(message, HEADERSIZE + 2168, 1, "F05ICA");
    fields[61] = fieldF05IOR =
    new CharacterField(message, HEADERSIZE + 2169, 1, "F05IOR");
    fields[62] = fieldF05TDR =
    new CharacterField(message, HEADERSIZE + 2170, 1, "F05TDR");
    fields[63] = fieldF05LRC =
    new CharacterField(message, HEADERSIZE + 2171, 1, "F05LRC");
    fields[64] = fieldF05CVR =
    new CharacterField(message, HEADERSIZE + 2172, 1, "F05CVR");
    fields[65] = fieldF05LVR =
    new CharacterField(message, HEADERSIZE + 2173, 1, "F05LVR");
    fields[66] = fieldF05VMT =
    new CharacterField(message, HEADERSIZE + 2174, 1, "F05VMT");
    fields[67] = fieldF05VXT =
    new CharacterField(message, HEADERSIZE + 2175, 1, "F05VXT");
    fields[68] = fieldF05TDS =
    new CharacterField(message, HEADERSIZE + 2176, 1, "F05TDS");
    fields[69] = fieldF05CNL =
    new CharacterField(message, HEADERSIZE + 2177, 1, "F05CNL");
    fields[70] = fieldF05VIR =
    new CharacterField(message, HEADERSIZE + 2178, 1, "F05VIR");
    fields[71] = fieldF05VFR =
    new CharacterField(message, HEADERSIZE + 2179, 1, "F05VFR");
    fields[72] = fieldE05APR =
    new CharacterField(message, HEADERSIZE + 2180, 1, "E05APR");
    fields[73] = fieldE05NUMREC =
    new DecimalField(message, HEADERSIZE + 2181, 8, 0, "E05NUMREC");
    fields[74] = fieldE05INDOPE =
    new CharacterField(message, HEADERSIZE + 2189, 1, "E05INDOPE");

    synchronized (tlookup)
    {
      if (tlookup.isEmpty())
      {
        for (int i = 0; i < tnames.length; i++)
          tlookup.put(tnames[i], new Integer(i));
      }
    }

    taglookup = tlookup;
  }

  /**
  * Set field H05USERID using a String value.
  */
  public void setH05USERID(String newvalue)
  {
    fieldH05USERID.setString(newvalue);
  }

  /**
  * Get value of field H05USERID as a String.
  */
  public String getH05USERID()
  {
    return fieldH05USERID.getString();
  }

  /**
  * Set field H05PROGRM using a String value.
  */
  public void setH05PROGRM(String newvalue)
  {
    fieldH05PROGRM.setString(newvalue);
  }

  /**
  * Get value of field H05PROGRM as a String.
  */
  public String getH05PROGRM()
  {
    return fieldH05PROGRM.getString();
  }

  /**
  * Set field H05TIMSYS using a String value.
  */
  public void setH05TIMSYS(String newvalue)
  {
    fieldH05TIMSYS.setString(newvalue);
  }

  /**
  * Get value of field H05TIMSYS as a String.
  */
  public String getH05TIMSYS()
  {
    return fieldH05TIMSYS.getString();
  }

  /**
  * Set field H05SCRCOD using a String value.
  */
  public void setH05SCRCOD(String newvalue)
  {
    fieldH05SCRCOD.setString(newvalue);
  }

  /**
  * Get value of field H05SCRCOD as a String.
  */
  public String getH05SCRCOD()
  {
    return fieldH05SCRCOD.getString();
  }

  /**
  * Set field H05OPECOD using a String value.
  */
  public void setH05OPECOD(String newvalue)
  {
    fieldH05OPECOD.setString(newvalue);
  }

  /**
  * Get value of field H05OPECOD as a String.
  */
  public String getH05OPECOD()
  {
    return fieldH05OPECOD.getString();
  }

  /**
  * Set field H05FLGMAS using a String value.
  */
  public void setH05FLGMAS(String newvalue)
  {
    fieldH05FLGMAS.setString(newvalue);
  }

  /**
  * Get value of field H05FLGMAS as a String.
  */
  public String getH05FLGMAS()
  {
    return fieldH05FLGMAS.getString();
  }

  /**
  * Set field H05FLGWK1 using a String value.
  */
  public void setH05FLGWK1(String newvalue)
  {
    fieldH05FLGWK1.setString(newvalue);
  }

  /**
  * Get value of field H05FLGWK1 as a String.
  */
  public String getH05FLGWK1()
  {
    return fieldH05FLGWK1.getString();
  }

  /**
  * Set field H05FLGWK2 using a String value.
  */
  public void setH05FLGWK2(String newvalue)
  {
    fieldH05FLGWK2.setString(newvalue);
  }

  /**
  * Get value of field H05FLGWK2 as a String.
  */
  public String getH05FLGWK2()
  {
    return fieldH05FLGWK2.getString();
  }

  /**
  * Set field H05FLGWK3 using a String value.
  */
  public void setH05FLGWK3(String newvalue)
  {
    fieldH05FLGWK3.setString(newvalue);
  }

  /**
  * Get value of field H05FLGWK3 as a String.
  */
  public String getH05FLGWK3()
  {
    return fieldH05FLGWK3.getString();
  }

  /**
  * Set field H05IPADDR using a String value.
  */
  public void setH05IPADDR(String newvalue)
  {
    fieldH05IPADDR.setString(newvalue);
  }

  /**
  * Get value of field H05IPADDR as a String.
  */
  public String getH05IPADDR()
  {
    return fieldH05IPADDR.getString();
  }

  /**
  * Set field H05TABSEC using a String value.
  */
  public void setH05TABSEC(String newvalue)
  {
    fieldH05TABSEC.setString(newvalue);
  }

  /**
  * Get value of field H05TABSEC as a String.
  */
  public String getH05TABSEC()
  {
    return fieldH05TABSEC.getString();
  }

  /**
  * Set field E05CRT using a String value.
  */
  public void setE05CRT(String newvalue)
  {
    fieldE05CRT.setString(newvalue);
  }

  /**
  * Get value of field E05CRT as a String.
  */
  public String getE05CRT()
  {
    return fieldE05CRT.getString();
  }

  /**
  * Set field D05CRT using a String value.
  */
  public void setD05CRT(String newvalue)
  {
    fieldD05CRT.setString(newvalue);
  }

  /**
  * Get value of field D05CRT as a String.
  */
  public String getD05CRT()
  {
    return fieldD05CRT.getString();
  }

  /**
  * Set field E05OPE using a String value.
  */
  public void setE05OPE(String newvalue)
  {
    fieldE05OPE.setString(newvalue);
  }

  /**
  * Get value of field E05OPE as a String.
  */
  public String getE05OPE()
  {
    return fieldE05OPE.getString();
  }

  /**
  * Set field E05RCRBNK using a String value.
  */
  public void setE05RCRBNK(String newvalue)
  {
    fieldE05RCRBNK.setString(newvalue);
  }

  /**
  * Get value of field E05RCRBNK as a String.
  */
  public String getE05RCRBNK()
  {
    return fieldE05RCRBNK.getString();
  }

  /**
  * Set field E05RCRCUN using a String value.
  */
  public void setE05RCRCUN(String newvalue)
  {
    fieldE05RCRCUN.setString(newvalue);
  }

  /**
  * Get value of field E05RCRCUN as a String.
  */
  public String getE05RCRCUN()
  {
    return fieldE05RCRCUN.getString();
  }

  /**
  * Set numeric field E05RCRCUN using a BigDecimal value.
  */
  public void setE05RCRCUN(BigDecimal newvalue)
  {
    fieldE05RCRCUN.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05RCRCUN as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05RCRCUN()
  {
    return fieldE05RCRCUN.getBigDecimal();
  }

  /**
  * Set field E05RCRNUM using a String value.
  */
  public void setE05RCRNUM(String newvalue)
  {
    fieldE05RCRNUM.setString(newvalue);
  }

  /**
  * Get value of field E05RCRNUM as a String.
  */
  public String getE05RCRNUM()
  {
    return fieldE05RCRNUM.getString();
  }

  /**
  * Set numeric field E05RCRNUM using a BigDecimal value.
  */
  public void setE05RCRNUM(BigDecimal newvalue)
  {
    fieldE05RCRNUM.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05RCRNUM as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05RCRNUM()
  {
    return fieldE05RCRNUM.getBigDecimal();
  }

  /**
  * Set field E05RCRDCL using a String value.
  */
  public void setE05RCRDCL(String newvalue)
  {
    fieldE05RCRDCL.setString(newvalue);
  }

  /**
  * Get value of field E05RCRDCL as a String.
  */
  public String getE05RCRDCL()
  {
    return fieldE05RCRDCL.getString();
  }

  /**
  * Set field E05RCRIDN using a String value.
  */
  public void setE05RCRIDN(String newvalue)
  {
    fieldE05RCRIDN.setString(newvalue);
  }

  /**
  * Get value of field E05RCRIDN as a String.
  */
  public String getE05RCRIDN()
  {
    return fieldE05RCRIDN.getString();
  }

  /**
  * Set field E05RCRCRF using a String value.
  */
  public void setE05RCRCRF(String newvalue)
  {
    fieldE05RCRCRF.setString(newvalue);
  }

  /**
  * Get value of field E05RCRCRF as a String.
  */
  public String getE05RCRCRF()
  {
    return fieldE05RCRCRF.getString();
  }

  /**
  * Set field E05RCRDRF using a String value.
  */
  public void setE05RCRDRF(String newvalue)
  {
    fieldE05RCRDRF.setString(newvalue);
  }

  /**
  * Get value of field E05RCRDRF as a String.
  */
  public String getE05RCRDRF()
  {
    return fieldE05RCRDRF.getString();
  }

  /**
  * Set field E05RCRSQR using a String value.
  */
  public void setE05RCRSQR(String newvalue)
  {
    fieldE05RCRSQR.setString(newvalue);
  }

  /**
  * Get value of field E05RCRSQR as a String.
  */
  public String getE05RCRSQR()
  {
    return fieldE05RCRSQR.getString();
  }

  /**
  * Set numeric field E05RCRSQR using a BigDecimal value.
  */
  public void setE05RCRSQR(BigDecimal newvalue)
  {
    fieldE05RCRSQR.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05RCRSQR as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05RCRSQR()
  {
    return fieldE05RCRSQR.getBigDecimal();
  }

  /**
  * Set field E05RCRIRA using a String value.
  */
  public void setE05RCRIRA(String newvalue)
  {
    fieldE05RCRIRA.setString(newvalue);
  }

  /**
  * Get value of field E05RCRIRA as a String.
  */
  public String getE05RCRIRA()
  {
    return fieldE05RCRIRA.getString();
  }

  /**
  * Set field E05RCRICA using a String value.
  */
  public void setE05RCRICA(String newvalue)
  {
    fieldE05RCRICA.setString(newvalue);
  }

  /**
  * Get value of field E05RCRICA as a String.
  */
  public String getE05RCRICA()
  {
    return fieldE05RCRICA.getString();
  }

  /**
  * Set field E05RCRIOR using a String value.
  */
  public void setE05RCRIOR(String newvalue)
  {
    fieldE05RCRIOR.setString(newvalue);
  }

  /**
  * Get value of field E05RCRIOR as a String.
  */
  public String getE05RCRIOR()
  {
    return fieldE05RCRIOR.getString();
  }

  /**
  * Set field E05RCRTDR using a String value.
  */
  public void setE05RCRTDR(String newvalue)
  {
    fieldE05RCRTDR.setString(newvalue);
  }

  /**
  * Get value of field E05RCRTDR as a String.
  */
  public String getE05RCRTDR()
  {
    return fieldE05RCRTDR.getString();
  }

  /**
  * Set field E05RCRLRC using a String value.
  */
  public void setE05RCRLRC(String newvalue)
  {
    fieldE05RCRLRC.setString(newvalue);
  }

  /**
  * Get value of field E05RCRLRC as a String.
  */
  public String getE05RCRLRC()
  {
    return fieldE05RCRLRC.getString();
  }

  /**
  * Set numeric field E05RCRLRC using a BigDecimal value.
  */
  public void setE05RCRLRC(BigDecimal newvalue)
  {
    fieldE05RCRLRC.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05RCRLRC as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05RCRLRC()
  {
    return fieldE05RCRLRC.getBigDecimal();
  }

  /**
  * Set field E05RCRCVR using a String value.
  */
  public void setE05RCRCVR(String newvalue)
  {
    fieldE05RCRCVR.setString(newvalue);
  }

  /**
  * Get value of field E05RCRCVR as a String.
  */
  public String getE05RCRCVR()
  {
    return fieldE05RCRCVR.getString();
  }

  /**
  * Set field E05RCRDVR using a String value.
  */
  public void setE05RCRDVR(String newvalue)
  {
    fieldE05RCRDVR.setString(newvalue);
  }

  /**
  * Get value of field E05RCRDVR as a String.
  */
  public String getE05RCRDVR()
  {
    return fieldE05RCRDVR.getString();
  }

  /**
  * Set field E05RCRLVR using a String value.
  */
  public void setE05RCRLVR(String newvalue)
  {
    fieldE05RCRLVR.setString(newvalue);
  }

  /**
  * Get value of field E05RCRLVR as a String.
  */
  public String getE05RCRLVR()
  {
    return fieldE05RCRLVR.getString();
  }

  /**
  * Set field E05RCRDLV using a String value.
  */
  public void setE05RCRDLV(String newvalue)
  {
    fieldE05RCRDLV.setString(newvalue);
  }

  /**
  * Get value of field E05RCRDLV as a String.
  */
  public String getE05RCRDLV()
  {
    return fieldE05RCRDLV.getString();
  }

  /**
  * Set field E05RCRVMT using a String value.
  */
  public void setE05RCRVMT(String newvalue)
  {
    fieldE05RCRVMT.setString(newvalue);
  }

  /**
  * Get value of field E05RCRVMT as a String.
  */
  public String getE05RCRVMT()
  {
    return fieldE05RCRVMT.getString();
  }

  /**
  * Set numeric field E05RCRVMT using a BigDecimal value.
  */
  public void setE05RCRVMT(BigDecimal newvalue)
  {
    fieldE05RCRVMT.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05RCRVMT as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05RCRVMT()
  {
    return fieldE05RCRVMT.getBigDecimal();
  }

  /**
  * Set field E05RCRVXT using a String value.
  */
  public void setE05RCRVXT(String newvalue)
  {
    fieldE05RCRVXT.setString(newvalue);
  }

  /**
  * Get value of field E05RCRVXT as a String.
  */
  public String getE05RCRVXT()
  {
    return fieldE05RCRVXT.getString();
  }

  /**
  * Set numeric field E05RCRVXT using a BigDecimal value.
  */
  public void setE05RCRVXT(BigDecimal newvalue)
  {
    fieldE05RCRVXT.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05RCRVXT as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05RCRVXT()
  {
    return fieldE05RCRVXT.getBigDecimal();
  }

  /**
  * Set field E05RCRTDS using a String value.
  */
  public void setE05RCRTDS(String newvalue)
  {
    fieldE05RCRTDS.setString(newvalue);
  }

  /**
  * Get value of field E05RCRTDS as a String.
  */
  public String getE05RCRTDS()
  {
    return fieldE05RCRTDS.getString();
  }

  /**
  * Set field E05RCRCNL using a String value.
  */
  public void setE05RCRCNL(String newvalue)
  {
    fieldE05RCRCNL.setString(newvalue);
  }

  /**
  * Get value of field E05RCRCNL as a String.
  */
  public String getE05RCRCNL()
  {
    return fieldE05RCRCNL.getString();
  }

  /**
  * Set field E05RCRFCN using a String value.
  */
  public void setE05RCRFCN(String newvalue)
  {
    fieldE05RCRFCN.setString(newvalue);
  }

  /**
  * Get value of field E05RCRFCN as a String.
  */
  public String getE05RCRFCN()
  {
    return fieldE05RCRFCN.getString();
  }

  /**
  * Set field E05RCRDCN using a String value.
  */
  public void setE05RCRDCN(String newvalue)
  {
    fieldE05RCRDCN.setString(newvalue);
  }

  /**
  * Get value of field E05RCRDCN as a String.
  */
  public String getE05RCRDCN()
  {
    return fieldE05RCRDCN.getString();
  }

  /**
  * Set field E05RCRVIM using a String value.
  */
  public void setE05RCRVIM(String newvalue)
  {
    fieldE05RCRVIM.setString(newvalue);
  }

  /**
  * Get value of field E05RCRVIM as a String.
  */
  public String getE05RCRVIM()
  {
    return fieldE05RCRVIM.getString();
  }

  /**
  * Set numeric field E05RCRVIM using a BigDecimal value.
  */
  public void setE05RCRVIM(BigDecimal newvalue)
  {
    fieldE05RCRVIM.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05RCRVIM as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05RCRVIM()
  {
    return fieldE05RCRVIM.getBigDecimal();
  }

  /**
  * Set field E05RCRVID using a String value.
  */
  public void setE05RCRVID(String newvalue)
  {
    fieldE05RCRVID.setString(newvalue);
  }

  /**
  * Get value of field E05RCRVID as a String.
  */
  public String getE05RCRVID()
  {
    return fieldE05RCRVID.getString();
  }

  /**
  * Set numeric field E05RCRVID using a BigDecimal value.
  */
  public void setE05RCRVID(BigDecimal newvalue)
  {
    fieldE05RCRVID.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05RCRVID as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05RCRVID()
  {
    return fieldE05RCRVID.getBigDecimal();
  }

  /**
  * Set field E05RCRVIY using a String value.
  */
  public void setE05RCRVIY(String newvalue)
  {
    fieldE05RCRVIY.setString(newvalue);
  }

  /**
  * Get value of field E05RCRVIY as a String.
  */
  public String getE05RCRVIY()
  {
    return fieldE05RCRVIY.getString();
  }

  /**
  * Set numeric field E05RCRVIY using a BigDecimal value.
  */
  public void setE05RCRVIY(BigDecimal newvalue)
  {
    fieldE05RCRVIY.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05RCRVIY as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05RCRVIY()
  {
    return fieldE05RCRVIY.getBigDecimal();
  }

  /**
  * Set field E05RCRVFM using a String value.
  */
  public void setE05RCRVFM(String newvalue)
  {
    fieldE05RCRVFM.setString(newvalue);
  }

  /**
  * Get value of field E05RCRVFM as a String.
  */
  public String getE05RCRVFM()
  {
    return fieldE05RCRVFM.getString();
  }

  /**
  * Set numeric field E05RCRVFM using a BigDecimal value.
  */
  public void setE05RCRVFM(BigDecimal newvalue)
  {
    fieldE05RCRVFM.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05RCRVFM as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05RCRVFM()
  {
    return fieldE05RCRVFM.getBigDecimal();
  }

  /**
  * Set field E05RCRVFD using a String value.
  */
  public void setE05RCRVFD(String newvalue)
  {
    fieldE05RCRVFD.setString(newvalue);
  }

  /**
  * Get value of field E05RCRVFD as a String.
  */
  public String getE05RCRVFD()
  {
    return fieldE05RCRVFD.getString();
  }

  /**
  * Set numeric field E05RCRVFD using a BigDecimal value.
  */
  public void setE05RCRVFD(BigDecimal newvalue)
  {
    fieldE05RCRVFD.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05RCRVFD as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05RCRVFD()
  {
    return fieldE05RCRVFD.getBigDecimal();
  }

  /**
  * Set field E05RCRVFY using a String value.
  */
  public void setE05RCRVFY(String newvalue)
  {
    fieldE05RCRVFY.setString(newvalue);
  }

  /**
  * Get value of field E05RCRVFY as a String.
  */
  public String getE05RCRVFY()
  {
    return fieldE05RCRVFY.getString();
  }

  /**
  * Set numeric field E05RCRVFY using a BigDecimal value.
  */
  public void setE05RCRVFY(BigDecimal newvalue)
  {
    fieldE05RCRVFY.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05RCRVFY as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05RCRVFY()
  {
    return fieldE05RCRVFY.getBigDecimal();
  }

  /**
  * Set field E05RCRCMM using a String value.
  */
  public void setE05RCRCMM(String newvalue)
  {
    fieldE05RCRCMM.setString(newvalue);
  }

  /**
  * Get value of field E05RCRCMM as a String.
  */
  public String getE05RCRCMM()
  {
    return fieldE05RCRCMM.getString();
  }

  /**
  * Set numeric field E05RCRCMM using a BigDecimal value.
  */
  public void setE05RCRCMM(BigDecimal newvalue)
  {
    fieldE05RCRCMM.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05RCRCMM as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05RCRCMM()
  {
    return fieldE05RCRCMM.getBigDecimal();
  }

  /**
  * Set field E05RCRCDD using a String value.
  */
  public void setE05RCRCDD(String newvalue)
  {
    fieldE05RCRCDD.setString(newvalue);
  }

  /**
  * Get value of field E05RCRCDD as a String.
  */
  public String getE05RCRCDD()
  {
    return fieldE05RCRCDD.getString();
  }

  /**
  * Set numeric field E05RCRCDD using a BigDecimal value.
  */
  public void setE05RCRCDD(BigDecimal newvalue)
  {
    fieldE05RCRCDD.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05RCRCDD as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05RCRCDD()
  {
    return fieldE05RCRCDD.getBigDecimal();
  }

  /**
  * Set field E05RCRCYY using a String value.
  */
  public void setE05RCRCYY(String newvalue)
  {
    fieldE05RCRCYY.setString(newvalue);
  }

  /**
  * Get value of field E05RCRCYY as a String.
  */
  public String getE05RCRCYY()
  {
    return fieldE05RCRCYY.getString();
  }

  /**
  * Set numeric field E05RCRCYY using a BigDecimal value.
  */
  public void setE05RCRCYY(BigDecimal newvalue)
  {
    fieldE05RCRCYY.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05RCRCYY as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05RCRCYY()
  {
    return fieldE05RCRCYY.getBigDecimal();
  }

  /**
  * Set field E05RCRCTM using a String value.
  */
  public void setE05RCRCTM(String newvalue)
  {
    fieldE05RCRCTM.setString(newvalue);
  }

  /**
  * Get value of field E05RCRCTM as a String.
  */
  public String getE05RCRCTM()
  {
    return fieldE05RCRCTM.getString();
  }

  /**
  * Set field E05RCRCUS using a String value.
  */
  public void setE05RCRCUS(String newvalue)
  {
    fieldE05RCRCUS.setString(newvalue);
  }

  /**
  * Get value of field E05RCRCUS as a String.
  */
  public String getE05RCRCUS()
  {
    return fieldE05RCRCUS.getString();
  }

  /**
  * Set field E05RCRAMM using a String value.
  */
  public void setE05RCRAMM(String newvalue)
  {
    fieldE05RCRAMM.setString(newvalue);
  }

  /**
  * Get value of field E05RCRAMM as a String.
  */
  public String getE05RCRAMM()
  {
    return fieldE05RCRAMM.getString();
  }

  /**
  * Set numeric field E05RCRAMM using a BigDecimal value.
  */
  public void setE05RCRAMM(BigDecimal newvalue)
  {
    fieldE05RCRAMM.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05RCRAMM as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05RCRAMM()
  {
    return fieldE05RCRAMM.getBigDecimal();
  }

  /**
  * Set field E05RCRADD using a String value.
  */
  public void setE05RCRADD(String newvalue)
  {
    fieldE05RCRADD.setString(newvalue);
  }

  /**
  * Get value of field E05RCRADD as a String.
  */
  public String getE05RCRADD()
  {
    return fieldE05RCRADD.getString();
  }

  /**
  * Set numeric field E05RCRADD using a BigDecimal value.
  */
  public void setE05RCRADD(BigDecimal newvalue)
  {
    fieldE05RCRADD.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05RCRADD as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05RCRADD()
  {
    return fieldE05RCRADD.getBigDecimal();
  }

  /**
  * Set field E05RCRAYY using a String value.
  */
  public void setE05RCRAYY(String newvalue)
  {
    fieldE05RCRAYY.setString(newvalue);
  }

  /**
  * Get value of field E05RCRAYY as a String.
  */
  public String getE05RCRAYY()
  {
    return fieldE05RCRAYY.getString();
  }

  /**
  * Set numeric field E05RCRAYY using a BigDecimal value.
  */
  public void setE05RCRAYY(BigDecimal newvalue)
  {
    fieldE05RCRAYY.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05RCRAYY as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05RCRAYY()
  {
    return fieldE05RCRAYY.getBigDecimal();
  }

  /**
  * Set field E05RCRATM using a String value.
  */
  public void setE05RCRATM(String newvalue)
  {
    fieldE05RCRATM.setString(newvalue);
  }

  /**
  * Get value of field E05RCRATM as a String.
  */
  public String getE05RCRATM()
  {
    return fieldE05RCRATM.getString();
  }

  /**
  * Set field E05RCRAUS using a String value.
  */
  public void setE05RCRAUS(String newvalue)
  {
    fieldE05RCRAUS.setString(newvalue);
  }

  /**
  * Get value of field E05RCRAUS as a String.
  */
  public String getE05RCRAUS()
  {
    return fieldE05RCRAUS.getString();
  }

  /**
  * Set field E05RCRMMM using a String value.
  */
  public void setE05RCRMMM(String newvalue)
  {
    fieldE05RCRMMM.setString(newvalue);
  }

  /**
  * Get value of field E05RCRMMM as a String.
  */
  public String getE05RCRMMM()
  {
    return fieldE05RCRMMM.getString();
  }

  /**
  * Set numeric field E05RCRMMM using a BigDecimal value.
  */
  public void setE05RCRMMM(BigDecimal newvalue)
  {
    fieldE05RCRMMM.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05RCRMMM as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05RCRMMM()
  {
    return fieldE05RCRMMM.getBigDecimal();
  }

  /**
  * Set field E05RCRMDD using a String value.
  */
  public void setE05RCRMDD(String newvalue)
  {
    fieldE05RCRMDD.setString(newvalue);
  }

  /**
  * Get value of field E05RCRMDD as a String.
  */
  public String getE05RCRMDD()
  {
    return fieldE05RCRMDD.getString();
  }

  /**
  * Set numeric field E05RCRMDD using a BigDecimal value.
  */
  public void setE05RCRMDD(BigDecimal newvalue)
  {
    fieldE05RCRMDD.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05RCRMDD as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05RCRMDD()
  {
    return fieldE05RCRMDD.getBigDecimal();
  }

  /**
  * Set field E05RCRMYY using a String value.
  */
  public void setE05RCRMYY(String newvalue)
  {
    fieldE05RCRMYY.setString(newvalue);
  }

  /**
  * Get value of field E05RCRMYY as a String.
  */
  public String getE05RCRMYY()
  {
    return fieldE05RCRMYY.getString();
  }

  /**
  * Set numeric field E05RCRMYY using a BigDecimal value.
  */
  public void setE05RCRMYY(BigDecimal newvalue)
  {
    fieldE05RCRMYY.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05RCRMYY as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05RCRMYY()
  {
    return fieldE05RCRMYY.getBigDecimal();
  }

  /**
  * Set field E05RCRMTM using a String value.
  */
  public void setE05RCRMTM(String newvalue)
  {
    fieldE05RCRMTM.setString(newvalue);
  }

  /**
  * Get value of field E05RCRMTM as a String.
  */
  public String getE05RCRMTM()
  {
    return fieldE05RCRMTM.getString();
  }

  /**
  * Set field E05RCRMUS using a String value.
  */
  public void setE05RCRMUS(String newvalue)
  {
    fieldE05RCRMUS.setString(newvalue);
  }

  /**
  * Get value of field E05RCRMUS as a String.
  */
  public String getE05RCRMUS()
  {
    return fieldE05RCRMUS.getString();
  }

  /**
  * Set field F05CRF using a String value.
  */
  public void setF05CRF(String newvalue)
  {
    fieldF05CRF.setString(newvalue);
  }

  /**
  * Get value of field F05CRF as a String.
  */
  public String getF05CRF()
  {
    return fieldF05CRF.getString();
  }

  /**
  * Set field F05IRA using a String value.
  */
  public void setF05IRA(String newvalue)
  {
    fieldF05IRA.setString(newvalue);
  }

  /**
  * Get value of field F05IRA as a String.
  */
  public String getF05IRA()
  {
    return fieldF05IRA.getString();
  }

  /**
  * Set field F05ICA using a String value.
  */
  public void setF05ICA(String newvalue)
  {
    fieldF05ICA.setString(newvalue);
  }

  /**
  * Get value of field F05ICA as a String.
  */
  public String getF05ICA()
  {
    return fieldF05ICA.getString();
  }

  /**
  * Set field F05IOR using a String value.
  */
  public void setF05IOR(String newvalue)
  {
    fieldF05IOR.setString(newvalue);
  }

  /**
  * Get value of field F05IOR as a String.
  */
  public String getF05IOR()
  {
    return fieldF05IOR.getString();
  }

  /**
  * Set field F05TDR using a String value.
  */
  public void setF05TDR(String newvalue)
  {
    fieldF05TDR.setString(newvalue);
  }

  /**
  * Get value of field F05TDR as a String.
  */
  public String getF05TDR()
  {
    return fieldF05TDR.getString();
  }

  /**
  * Set field F05LRC using a String value.
  */
  public void setF05LRC(String newvalue)
  {
    fieldF05LRC.setString(newvalue);
  }

  /**
  * Get value of field F05LRC as a String.
  */
  public String getF05LRC()
  {
    return fieldF05LRC.getString();
  }

  /**
  * Set field F05CVR using a String value.
  */
  public void setF05CVR(String newvalue)
  {
    fieldF05CVR.setString(newvalue);
  }

  /**
  * Get value of field F05CVR as a String.
  */
  public String getF05CVR()
  {
    return fieldF05CVR.getString();
  }

  /**
  * Set field F05LVR using a String value.
  */
  public void setF05LVR(String newvalue)
  {
    fieldF05LVR.setString(newvalue);
  }

  /**
  * Get value of field F05LVR as a String.
  */
  public String getF05LVR()
  {
    return fieldF05LVR.getString();
  }

  /**
  * Set field F05VMT using a String value.
  */
  public void setF05VMT(String newvalue)
  {
    fieldF05VMT.setString(newvalue);
  }

  /**
  * Get value of field F05VMT as a String.
  */
  public String getF05VMT()
  {
    return fieldF05VMT.getString();
  }

  /**
  * Set field F05VXT using a String value.
  */
  public void setF05VXT(String newvalue)
  {
    fieldF05VXT.setString(newvalue);
  }

  /**
  * Get value of field F05VXT as a String.
  */
  public String getF05VXT()
  {
    return fieldF05VXT.getString();
  }

  /**
  * Set field F05TDS using a String value.
  */
  public void setF05TDS(String newvalue)
  {
    fieldF05TDS.setString(newvalue);
  }

  /**
  * Get value of field F05TDS as a String.
  */
  public String getF05TDS()
  {
    return fieldF05TDS.getString();
  }

  /**
  * Set field F05CNL using a String value.
  */
  public void setF05CNL(String newvalue)
  {
    fieldF05CNL.setString(newvalue);
  }

  /**
  * Get value of field F05CNL as a String.
  */
  public String getF05CNL()
  {
    return fieldF05CNL.getString();
  }

  /**
  * Set field F05VIR using a String value.
  */
  public void setF05VIR(String newvalue)
  {
    fieldF05VIR.setString(newvalue);
  }

  /**
  * Get value of field F05VIR as a String.
  */
  public String getF05VIR()
  {
    return fieldF05VIR.getString();
  }

  /**
  * Set field F05VFR using a String value.
  */
  public void setF05VFR(String newvalue)
  {
    fieldF05VFR.setString(newvalue);
  }

  /**
  * Get value of field F05VFR as a String.
  */
  public String getF05VFR()
  {
    return fieldF05VFR.getString();
  }

  /**
  * Set field E05APR using a String value.
  */
  public void setE05APR(String newvalue)
  {
    fieldE05APR.setString(newvalue);
  }

  /**
  * Get value of field E05APR as a String.
  */
  public String getE05APR()
  {
    return fieldE05APR.getString();
  }

  /**
  * Set field E05NUMREC using a String value.
  */
  public void setE05NUMREC(String newvalue)
  {
    fieldE05NUMREC.setString(newvalue);
  }

  /**
  * Get value of field E05NUMREC as a String.
  */
  public String getE05NUMREC()
  {
    return fieldE05NUMREC.getString();
  }

  /**
  * Set numeric field E05NUMREC using a BigDecimal value.
  */
  public void setE05NUMREC(BigDecimal newvalue)
  {
    fieldE05NUMREC.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05NUMREC as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05NUMREC()
  {
    return fieldE05NUMREC.getBigDecimal();
  }

  /**
  * Set field E05INDOPE using a String value.
  */
  public void setE05INDOPE(String newvalue)
  {
    fieldE05INDOPE.setString(newvalue);
  }

  /**
  * Get value of field E05INDOPE as a String.
  */
  public String getE05INDOPE()
  {
    return fieldE05INDOPE.getString();
  }

}
