package datapro.eibs.beans;

import datapro.eibs.sockets.*;
import java.io.*;
import java.math.*;

import java.util.*;

/**
* Class generated by AS/400 CRTCLASS command from EDP070701 physical file definition.
* 
* File level identifier is 1130611113110.
* Record format level identifier is 45C5507A1729F.
*/

public class EDP070701Message extends MessageRecord
{
  final static String fldnames[] = {
                                     "H01USERID",
                                     "H01PROGRM",
                                     "H01TIMSYS",
                                     "H01SCRCOD",
                                     "H01OPECOD",
                                     "H01FLGMAS",
                                     "H01FLGWK1",
                                     "H01FLGWK2",
                                     "H01FLGWK3",
                                     "E01CNTLAN",
                                     "E01DPYCNM",
                                     "E01DPYUID",
                                     "E01DPYCMN",
                                     "E01DPYSEC",
                                     "E01DPYPRE",
                                     "E01OPECDE"
                                   };
  final static String tnames[] = {
                                   "H01USERID",
                                   "H01PROGRM",
                                   "H01TIMSYS",
                                   "H01SCRCOD",
                                   "H01OPECOD",
                                   "H01FLGMAS",
                                   "H01FLGWK1",
                                   "H01FLGWK2",
                                   "H01FLGWK3",
                                   "E01CNTLAN",
                                   "E01DPYCNM",
                                   "E01DPYUID",
                                   "E01DPYCMN",
                                   "E01DPYSEC",
                                   "E01DPYPRE",
                                   "E01OPECDE"
                                 };
  final static String fid = "1130611113110";
  final static String rid = "45C5507A1729F";
  final static String fmtname = "EDP070701";
  final int FIELDCOUNT = 16;
  private static Hashtable tlookup = new Hashtable();
  private CharacterField fieldH01USERID = null;
  private CharacterField fieldH01PROGRM = null;
  private CharacterField fieldH01TIMSYS = null;
  private CharacterField fieldH01SCRCOD = null;
  private CharacterField fieldH01OPECOD = null;
  private CharacterField fieldH01FLGMAS = null;
  private CharacterField fieldH01FLGWK1 = null;
  private CharacterField fieldH01FLGWK2 = null;
  private CharacterField fieldH01FLGWK3 = null;
  private CharacterField fieldE01CNTLAN = null;
  private CharacterField fieldE01DPYCNM = null;
  private CharacterField fieldE01DPYUID = null;
  private CharacterField fieldE01DPYCMN = null;
  private CharacterField fieldE01DPYSEC = null;
  private CharacterField fieldE01DPYPRE = null;
  private CharacterField fieldE01OPECDE = null;

  /**
  * Constructor for EDP070701Message.
  */
  public EDP070701Message()
  {
    createFields();
    initialize();
  }

  /**
  * Create fields for this message.
  * This method implements the abstract method in the MessageRecord superclass.
  */
  protected void createFields()
  {
    recordsize = 61;
    fileid = fid;
    recordid = rid;
    message = new byte[getByteLength()];
    formatname = fmtname;
    fieldnames = fldnames;
    tagnames = tnames;
    fields = new MessageField[FIELDCOUNT];

    fields[0] = fieldH01USERID =
    new CharacterField(message, HEADERSIZE + 0, 10, "H01USERID");
    fields[1] = fieldH01PROGRM =
    new CharacterField(message, HEADERSIZE + 10, 10, "H01PROGRM");
    fields[2] = fieldH01TIMSYS =
    new CharacterField(message, HEADERSIZE + 20, 12, "H01TIMSYS");
    fields[3] = fieldH01SCRCOD =
    new CharacterField(message, HEADERSIZE + 32, 2, "H01SCRCOD");
    fields[4] = fieldH01OPECOD =
    new CharacterField(message, HEADERSIZE + 34, 4, "H01OPECOD");
    fields[5] = fieldH01FLGMAS =
    new CharacterField(message, HEADERSIZE + 38, 1, "H01FLGMAS");
    fields[6] = fieldH01FLGWK1 =
    new CharacterField(message, HEADERSIZE + 39, 1, "H01FLGWK1");
    fields[7] = fieldH01FLGWK2 =
    new CharacterField(message, HEADERSIZE + 40, 1, "H01FLGWK2");
    fields[8] = fieldH01FLGWK3 =
    new CharacterField(message, HEADERSIZE + 41, 1, "H01FLGWK3");
    fields[9] = fieldE01CNTLAN =
    new CharacterField(message, HEADERSIZE + 42, 1, "E01CNTLAN");
    fields[10] = fieldE01DPYCNM =
    new CharacterField(message, HEADERSIZE + 43, 4, "E01DPYCNM");
    fields[11] = fieldE01DPYUID =
    new CharacterField(message, HEADERSIZE + 47, 10, "E01DPYUID");
    fields[12] = fieldE01DPYCMN =
    new CharacterField(message, HEADERSIZE + 57, 1, "E01DPYCMN");
    fields[13] = fieldE01DPYSEC =
    new CharacterField(message, HEADERSIZE + 58, 1, "E01DPYSEC");
    fields[14] = fieldE01DPYPRE =
    new CharacterField(message, HEADERSIZE + 59, 1, "E01DPYPRE");
    fields[15] = fieldE01OPECDE =
    new CharacterField(message, HEADERSIZE + 60, 1, "E01OPECDE");

    synchronized (tlookup)
    {
      if (tlookup.isEmpty())
      {
        for (int i = 0; i < tnames.length; i++)
          tlookup.put(tnames[i], new Integer(i));
      }
    }

    taglookup = tlookup;
  }

  /**
  * Set field H01USERID using a String value.
  */
  public void setH01USERID(String newvalue)
  {
    fieldH01USERID.setString(newvalue);
  }

  /**
  * Get value of field H01USERID as a String.
  */
  public String getH01USERID()
  {
    return fieldH01USERID.getString();
  }

  /**
  * Set field H01PROGRM using a String value.
  */
  public void setH01PROGRM(String newvalue)
  {
    fieldH01PROGRM.setString(newvalue);
  }

  /**
  * Get value of field H01PROGRM as a String.
  */
  public String getH01PROGRM()
  {
    return fieldH01PROGRM.getString();
  }

  /**
  * Set field H01TIMSYS using a String value.
  */
  public void setH01TIMSYS(String newvalue)
  {
    fieldH01TIMSYS.setString(newvalue);
  }

  /**
  * Get value of field H01TIMSYS as a String.
  */
  public String getH01TIMSYS()
  {
    return fieldH01TIMSYS.getString();
  }

  /**
  * Set field H01SCRCOD using a String value.
  */
  public void setH01SCRCOD(String newvalue)
  {
    fieldH01SCRCOD.setString(newvalue);
  }

  /**
  * Get value of field H01SCRCOD as a String.
  */
  public String getH01SCRCOD()
  {
    return fieldH01SCRCOD.getString();
  }

  /**
  * Set field H01OPECOD using a String value.
  */
  public void setH01OPECOD(String newvalue)
  {
    fieldH01OPECOD.setString(newvalue);
  }

  /**
  * Get value of field H01OPECOD as a String.
  */
  public String getH01OPECOD()
  {
    return fieldH01OPECOD.getString();
  }

  /**
  * Set field H01FLGMAS using a String value.
  */
  public void setH01FLGMAS(String newvalue)
  {
    fieldH01FLGMAS.setString(newvalue);
  }

  /**
  * Get value of field H01FLGMAS as a String.
  */
  public String getH01FLGMAS()
  {
    return fieldH01FLGMAS.getString();
  }

  /**
  * Set field H01FLGWK1 using a String value.
  */
  public void setH01FLGWK1(String newvalue)
  {
    fieldH01FLGWK1.setString(newvalue);
  }

  /**
  * Get value of field H01FLGWK1 as a String.
  */
  public String getH01FLGWK1()
  {
    return fieldH01FLGWK1.getString();
  }

  /**
  * Set field H01FLGWK2 using a String value.
  */
  public void setH01FLGWK2(String newvalue)
  {
    fieldH01FLGWK2.setString(newvalue);
  }

  /**
  * Get value of field H01FLGWK2 as a String.
  */
  public String getH01FLGWK2()
  {
    return fieldH01FLGWK2.getString();
  }

  /**
  * Set field H01FLGWK3 using a String value.
  */
  public void setH01FLGWK3(String newvalue)
  {
    fieldH01FLGWK3.setString(newvalue);
  }

  /**
  * Get value of field H01FLGWK3 as a String.
  */
  public String getH01FLGWK3()
  {
    return fieldH01FLGWK3.getString();
  }

  /**
  * Set field E01CNTLAN using a String value.
  */
  public void setE01CNTLAN(String newvalue)
  {
    fieldE01CNTLAN.setString(newvalue);
  }

  /**
  * Get value of field E01CNTLAN as a String.
  */
  public String getE01CNTLAN()
  {
    return fieldE01CNTLAN.getString();
  }

  /**
  * Set field E01DPYCNM using a String value.
  */
  public void setE01DPYCNM(String newvalue)
  {
    fieldE01DPYCNM.setString(newvalue);
  }

  /**
  * Get value of field E01DPYCNM as a String.
  */
  public String getE01DPYCNM()
  {
    return fieldE01DPYCNM.getString();
  }

  /**
  * Set field E01DPYUID using a String value.
  */
  public void setE01DPYUID(String newvalue)
  {
    fieldE01DPYUID.setString(newvalue);
  }

  /**
  * Get value of field E01DPYUID as a String.
  */
  public String getE01DPYUID()
  {
    return fieldE01DPYUID.getString();
  }

  /**
  * Set field E01DPYCMN using a String value.
  */
  public void setE01DPYCMN(String newvalue)
  {
    fieldE01DPYCMN.setString(newvalue);
  }

  /**
  * Get value of field E01DPYCMN as a String.
  */
  public String getE01DPYCMN()
  {
    return fieldE01DPYCMN.getString();
  }

  /**
  * Set field E01DPYSEC using a String value.
  */
  public void setE01DPYSEC(String newvalue)
  {
    fieldE01DPYSEC.setString(newvalue);
  }

  /**
  * Get value of field E01DPYSEC as a String.
  */
  public String getE01DPYSEC()
  {
    return fieldE01DPYSEC.getString();
  }

  /**
  * Set field E01DPYPRE using a String value.
  */
  public void setE01DPYPRE(String newvalue)
  {
    fieldE01DPYPRE.setString(newvalue);
  }

  /**
  * Get value of field E01DPYPRE as a String.
  */
  public String getE01DPYPRE()
  {
    return fieldE01DPYPRE.getString();
  }

  /**
  * Set field E01OPECDE using a String value.
  */
  public void setE01OPECDE(String newvalue)
  {
    fieldE01OPECDE.setString(newvalue);
  }

  /**
  * Get value of field E01OPECDE as a String.
  */
  public String getE01OPECDE()
  {
    return fieldE01OPECDE.getString();
  }

}
