package datapro.eibs.beans;

import datapro.eibs.sockets.*;
import java.io.*;
import java.math.*;

import java.util.*;

/**
* Class generated by AS/400 CRTCLASS command from ESD008701 physical file definition.
* 
* File level identifier is 1110914111400.
* Record format level identifier is 3EA5F53FC9F2A.
*/

public class ESD008701Message extends MessageRecord
{
  final static String fldnames[] = {
                                     "H01USERID",
                                     "H01PROGRM",
                                     "H01TIMSYS",
                                     "H01SCR",
                                     "H01OPECOD",
                                     "H01FLGMAS",
                                     "H01FLGWK1",
                                     "H01FLGWK2",
                                     "H01FLGWK3",
                                     "E01LGT",
                                     "E01CUN",
                                     "E01FNA",
                                     "E01FN2",
                                     "E01LN1",
                                     "E01LN2",
                                     "E01ACA",
                                     "E01NA1",
                                     "E01NA2",
                                     "E01NA3",
                                     "E01NA4",
                                     "E01CTY",
                                     "E01STE",
                                     "E01CTR",
                                     "E01SHN",
                                     "E01POB",
                                     "E01CCS",
                                     "E01ZPC",
                                     "E01IDN",
                                     "E01TID",
                                     "E01PID",
                                     "E01IDF",
                                     "E01TIF",
                                     "E01PIF",
                                     "E01ID3",
                                     "E01TI3",
                                     "E01PI3",
                                     "E01ID4",
                                     "E01TI4",
                                     "E01PI4",
                                     "E01BDM",
                                     "E01BDD",
                                     "E01BDY",
                                     "E01LIF",
                                     "E01RLV",
                                     "E01GRP",
                                     "E01SEX",
                                     "E01TYP",
                                     "E01MST",
                                     "E01IDM",
                                     "E01IDD",
                                     "E01IDY",
                                     "E01ILV",
                                     "E01STS",
                                     "E01MLC",
                                     "E01CCL",
                                     "E01RSL",
                                     "E01HPN",
                                     "E01HPNX",
                                     "E01FL2",
                                     "E01PHN",
                                     "E01PHNX",
                                     "E01PH1",
                                     "E01FAX",
                                     "E01FAXX",
                                     "E01EDL",
                                     "E01INL",
                                     "E01BUC",
                                     "E01COB",
                                     "E01RBY",
                                     "E01RBN",
                                     "E01FL3",
                                     "E01STF",
                                     "E01SOI",
                                     "E01NSO",
                                     "E01FL1",
                                     "E01IAD",
                                     "E01OFC",
                                     "E01OF2",
                                     "E01INC",
                                     "E01GEC",
                                     "E01UC1",
                                     "E01UC2",
                                     "E01UC3",
                                     "E01UC4",
                                     "E01UC5",
                                     "E01UC6",
                                     "E01UC7",
                                     "E01UC8",
                                     "E01UC9",
                                     "E01PRV",
                                     "E01CMP",
                                     "E01FL4",
                                     "E01SDY",
                                     "E01FL5",
                                     "E01FL6",
                                     "E01FL7",
                                     "E01FL8",
                                     "E01WEB",
                                     "E01BRA",
                                     "E01SCH",
                                     "E01SST",
                                     "E01FC1",
                                     "E01FC2",
                                     "E01TER",
                                     "E01FG1",
                                     "E01FG2",
                                     "E01AM1",
                                     "E01DD1",
                                     "E01DD2",
                                     "E01DD3",
                                     "E01D11",
                                     "E01D12",
                                     "E01D13",
                                     "E01F01",
                                     "E01PHO1",
                                     "E01PHO2",
                                     "E01PHO3",
                                     "D01STE",
                                     "F01NA2",
                                     "F01NA3",
                                     "F01NA4",
                                     "F01MLC",
                                     "F01STE",
                                     "F01CTR",
                                     "F01POB",
                                     "F01ZPC",
                                     "F01IAD",
                                     "F01IDN",
                                     "F01TID",
                                     "F01PID",
                                     "F01IDF",
                                     "F01TIF",
                                     "F01PIF",
                                     "F01ID3",
                                     "F01TI3",
                                     "F01PI3",
                                     "F01ID4",
                                     "F01TI4",
                                     "F01PI4",
                                     "E01NUMREC",
                                     "E01INDOPE"
                                   };
  final static String tnames[] = {
                                   "H01USERID",
                                   "H01PROGRM",
                                   "H01TIMSYS",
                                   "H01SCR",
                                   "H01OPECOD",
                                   "H01FLGMAS",
                                   "H01FLGWK1",
                                   "H01FLGWK2",
                                   "H01FLGWK3",
                                   "E01LGT",
                                   "E01CUN",
                                   "E01FNA",
                                   "E01FN2",
                                   "E01LN1",
                                   "E01LN2",
                                   "E01ACA",
                                   "E01NA1",
                                   "E01NA2",
                                   "E01NA3",
                                   "E01NA4",
                                   "E01CTY",
                                   "E01STE",
                                   "E01CTR",
                                   "E01SHN",
                                   "E01POB",
                                   "E01CCS",
                                   "E01ZPC",
                                   "E01IDN",
                                   "E01TID",
                                   "E01PID",
                                   "E01IDF",
                                   "E01TIF",
                                   "E01PIF",
                                   "E01ID3",
                                   "E01TI3",
                                   "E01PI3",
                                   "E01ID4",
                                   "E01TI4",
                                   "E01PI4",
                                   "E01BDM",
                                   "E01BDD",
                                   "E01BDY",
                                   "E01LIF",
                                   "E01RLV",
                                   "E01GRP",
                                   "E01SEX",
                                   "E01TYP",
                                   "E01MST",
                                   "E01IDM",
                                   "E01IDD",
                                   "E01IDY",
                                   "E01ILV",
                                   "E01STS",
                                   "E01MLC",
                                   "E01CCL",
                                   "E01RSL",
                                   "E01HPN",
                                   "E01HPNX",
                                   "E01FL2",
                                   "E01PHN",
                                   "E01PHNX",
                                   "E01PH1",
                                   "E01FAX",
                                   "E01FAXX",
                                   "E01EDL",
                                   "E01INL",
                                   "E01BUC",
                                   "E01COB",
                                   "E01RBY",
                                   "E01RBN",
                                   "E01FL3",
                                   "E01STF",
                                   "E01SOI",
                                   "E01NSO",
                                   "E01FL1",
                                   "E01IAD",
                                   "E01OFC",
                                   "E01OF2",
                                   "E01INC",
                                   "E01GEC",
                                   "E01UC1",
                                   "E01UC2",
                                   "E01UC3",
                                   "E01UC4",
                                   "E01UC5",
                                   "E01UC6",
                                   "E01UC7",
                                   "E01UC8",
                                   "E01UC9",
                                   "E01PRV",
                                   "E01CMP",
                                   "E01FL4",
                                   "E01SDY",
                                   "E01FL5",
                                   "E01FL6",
                                   "E01FL7",
                                   "E01FL8",
                                   "E01WEB",
                                   "E01BRA",
                                   "E01SCH",
                                   "E01SST",
                                   "E01FC1",
                                   "E01FC2",
                                   "E01TER",
                                   "E01FG1",
                                   "E01FG2",
                                   "E01AM1",
                                   "E01DD1",
                                   "E01DD2",
                                   "E01DD3",
                                   "E01D11",
                                   "E01D12",
                                   "E01D13",
                                   "E01F01",
                                   "E01PHO1",
                                   "E01PHO2",
                                   "E01PHO3",
                                   "D01STE",
                                   "F01NA2",
                                   "F01NA3",
                                   "F01NA4",
                                   "F01MLC",
                                   "F01STE",
                                   "F01CTR",
                                   "F01POB",
                                   "F01ZPC",
                                   "F01IAD",
                                   "F01IDN",
                                   "F01TID",
                                   "F01PID",
                                   "F01IDF",
                                   "F01TIF",
                                   "F01PIF",
                                   "F01ID3",
                                   "F01TI3",
                                   "F01PI3",
                                   "F01ID4",
                                   "F01TI4",
                                   "F01PI4",
                                   "E01NUMREC",
                                   "E01INDOPE"
                                 };
  final static String fid = "1110914111400";
  final static String rid = "3EA5F53FC9F2A";
  final static String fmtname = "ESD008701";
  final int FIELDCOUNT = 141;
  private static Hashtable tlookup = new Hashtable();
  private CharacterField fieldH01USERID = null;
  private CharacterField fieldH01PROGRM = null;
  private CharacterField fieldH01TIMSYS = null;
  private CharacterField fieldH01SCR = null;
  private CharacterField fieldH01OPECOD = null;
  private CharacterField fieldH01FLGMAS = null;
  private CharacterField fieldH01FLGWK1 = null;
  private CharacterField fieldH01FLGWK2 = null;
  private CharacterField fieldH01FLGWK3 = null;
  private CharacterField fieldE01LGT = null;
  private DecimalField fieldE01CUN = null;
  private CharacterField fieldE01FNA = null;
  private CharacterField fieldE01FN2 = null;
  private CharacterField fieldE01LN1 = null;
  private CharacterField fieldE01LN2 = null;
  private CharacterField fieldE01ACA = null;
  private CharacterField fieldE01NA1 = null;
  private CharacterField fieldE01NA2 = null;
  private CharacterField fieldE01NA3 = null;
  private CharacterField fieldE01NA4 = null;
  private CharacterField fieldE01CTY = null;
  private CharacterField fieldE01STE = null;
  private CharacterField fieldE01CTR = null;
  private CharacterField fieldE01SHN = null;
  private CharacterField fieldE01POB = null;
  private CharacterField fieldE01CCS = null;
  private CharacterField fieldE01ZPC = null;
  private CharacterField fieldE01IDN = null;
  private CharacterField fieldE01TID = null;
  private CharacterField fieldE01PID = null;
  private CharacterField fieldE01IDF = null;
  private CharacterField fieldE01TIF = null;
  private CharacterField fieldE01PIF = null;
  private CharacterField fieldE01ID3 = null;
  private CharacterField fieldE01TI3 = null;
  private CharacterField fieldE01PI3 = null;
  private CharacterField fieldE01ID4 = null;
  private CharacterField fieldE01TI4 = null;
  private CharacterField fieldE01PI4 = null;
  private DecimalField fieldE01BDM = null;
  private DecimalField fieldE01BDD = null;
  private DecimalField fieldE01BDY = null;
  private CharacterField fieldE01LIF = null;
  private CharacterField fieldE01RLV = null;
  private DecimalField fieldE01GRP = null;
  private CharacterField fieldE01SEX = null;
  private CharacterField fieldE01TYP = null;
  private CharacterField fieldE01MST = null;
  private DecimalField fieldE01IDM = null;
  private DecimalField fieldE01IDD = null;
  private DecimalField fieldE01IDY = null;
  private DecimalField fieldE01ILV = null;
  private CharacterField fieldE01STS = null;
  private CharacterField fieldE01MLC = null;
  private CharacterField fieldE01CCL = null;
  private CharacterField fieldE01RSL = null;
  private DecimalField fieldE01HPN = null;
  private DecimalField fieldE01HPNX = null;
  private CharacterField fieldE01FL2 = null;
  private DecimalField fieldE01PHN = null;
  private DecimalField fieldE01PHNX = null;
  private DecimalField fieldE01PH1 = null;
  private DecimalField fieldE01FAX = null;
  private DecimalField fieldE01FAXX = null;
  private CharacterField fieldE01EDL = null;
  private CharacterField fieldE01INL = null;
  private CharacterField fieldE01BUC = null;
  private CharacterField fieldE01COB = null;
  private CharacterField fieldE01RBY = null;
  private CharacterField fieldE01RBN = null;
  private CharacterField fieldE01FL3 = null;
  private CharacterField fieldE01STF = null;
  private CharacterField fieldE01SOI = null;
  private DecimalField fieldE01NSO = null;
  private CharacterField fieldE01FL1 = null;
  private CharacterField fieldE01IAD = null;
  private CharacterField fieldE01OFC = null;
  private CharacterField fieldE01OF2 = null;
  private CharacterField fieldE01INC = null;
  private CharacterField fieldE01GEC = null;
  private CharacterField fieldE01UC1 = null;
  private CharacterField fieldE01UC2 = null;
  private CharacterField fieldE01UC3 = null;
  private CharacterField fieldE01UC4 = null;
  private CharacterField fieldE01UC5 = null;
  private CharacterField fieldE01UC6 = null;
  private CharacterField fieldE01UC7 = null;
  private CharacterField fieldE01UC8 = null;
  private CharacterField fieldE01UC9 = null;
  private CharacterField fieldE01PRV = null;
  private CharacterField fieldE01CMP = null;
  private CharacterField fieldE01FL4 = null;
  private CharacterField fieldE01SDY = null;
  private CharacterField fieldE01FL5 = null;
  private CharacterField fieldE01FL6 = null;
  private CharacterField fieldE01FL7 = null;
  private CharacterField fieldE01FL8 = null;
  private CharacterField fieldE01WEB = null;
  private DecimalField fieldE01BRA = null;
  private CharacterField fieldE01SCH = null;
  private CharacterField fieldE01SST = null;
  private CharacterField fieldE01FC1 = null;
  private CharacterField fieldE01FC2 = null;
  private DecimalField fieldE01TER = null;
  private CharacterField fieldE01FG1 = null;
  private CharacterField fieldE01FG2 = null;
  private DecimalField fieldE01AM1 = null;
  private DecimalField fieldE01DD1 = null;
  private DecimalField fieldE01DD2 = null;
  private DecimalField fieldE01DD3 = null;
  private DecimalField fieldE01D11 = null;
  private DecimalField fieldE01D12 = null;
  private DecimalField fieldE01D13 = null;
  private CharacterField fieldE01F01 = null;
  private DecimalField fieldE01PHO1 = null;
  private DecimalField fieldE01PHO2 = null;
  private DecimalField fieldE01PHO3 = null;
  private CharacterField fieldD01STE = null;
  private CharacterField fieldF01NA2 = null;
  private CharacterField fieldF01NA3 = null;
  private CharacterField fieldF01NA4 = null;
  private CharacterField fieldF01MLC = null;
  private CharacterField fieldF01STE = null;
  private CharacterField fieldF01CTR = null;
  private CharacterField fieldF01POB = null;
  private CharacterField fieldF01ZPC = null;
  private CharacterField fieldF01IAD = null;
  private CharacterField fieldF01IDN = null;
  private CharacterField fieldF01TID = null;
  private CharacterField fieldF01PID = null;
  private CharacterField fieldF01IDF = null;
  private CharacterField fieldF01TIF = null;
  private CharacterField fieldF01PIF = null;
  private CharacterField fieldF01ID3 = null;
  private CharacterField fieldF01TI3 = null;
  private CharacterField fieldF01PI3 = null;
  private CharacterField fieldF01ID4 = null;
  private CharacterField fieldF01TI4 = null;
  private CharacterField fieldF01PI4 = null;
  private DecimalField fieldE01NUMREC = null;
  private CharacterField fieldE01INDOPE = null;

  /**
  * Constructor for ESD008701Message.
  */
  public ESD008701Message()
  {
    createFields();
    initialize();
  }

  /**
  * Create fields for this message.
  * This method implements the abstract method in the MessageRecord superclass.
  */
  protected void createFields()
  {
    recordsize = 1248;
    fileid = fid;
    recordid = rid;
    message = new byte[getByteLength()];
    formatname = fmtname;
    fieldnames = fldnames;
    tagnames = tnames;
    fields = new MessageField[FIELDCOUNT];

    fields[0] = fieldH01USERID =
    new CharacterField(message, HEADERSIZE + 0, 10, "H01USERID");
    fields[1] = fieldH01PROGRM =
    new CharacterField(message, HEADERSIZE + 10, 10, "H01PROGRM");
    fields[2] = fieldH01TIMSYS =
    new CharacterField(message, HEADERSIZE + 20, 12, "H01TIMSYS");
    fields[3] = fieldH01SCR =
    new CharacterField(message, HEADERSIZE + 32, 2, "H01SCR");
    fields[4] = fieldH01OPECOD =
    new CharacterField(message, HEADERSIZE + 34, 4, "H01OPECOD");
    fields[5] = fieldH01FLGMAS =
    new CharacterField(message, HEADERSIZE + 38, 1, "H01FLGMAS");
    fields[6] = fieldH01FLGWK1 =
    new CharacterField(message, HEADERSIZE + 39, 1, "H01FLGWK1");
    fields[7] = fieldH01FLGWK2 =
    new CharacterField(message, HEADERSIZE + 40, 1, "H01FLGWK2");
    fields[8] = fieldH01FLGWK3 =
    new CharacterField(message, HEADERSIZE + 41, 1, "H01FLGWK3");
    fields[9] = fieldE01LGT =
    new CharacterField(message, HEADERSIZE + 42, 1, "E01LGT");
    fields[10] = fieldE01CUN =
    new DecimalField(message, HEADERSIZE + 43, 10, 0, "E01CUN");
    fields[11] = fieldE01FNA =
    new CharacterField(message, HEADERSIZE + 53, 30, "E01FNA");
    fields[12] = fieldE01FN2 =
    new CharacterField(message, HEADERSIZE + 83, 30, "E01FN2");
    fields[13] = fieldE01LN1 =
    new CharacterField(message, HEADERSIZE + 113, 30, "E01LN1");
    fields[14] = fieldE01LN2 =
    new CharacterField(message, HEADERSIZE + 143, 30, "E01LN2");
    fields[15] = fieldE01ACA =
    new CharacterField(message, HEADERSIZE + 173, 30, "E01ACA");
    fields[16] = fieldE01NA1 =
    new CharacterField(message, HEADERSIZE + 203, 60, "E01NA1");
    fields[17] = fieldE01NA2 =
    new CharacterField(message, HEADERSIZE + 263, 45, "E01NA2");
    fields[18] = fieldE01NA3 =
    new CharacterField(message, HEADERSIZE + 308, 45, "E01NA3");
    fields[19] = fieldE01NA4 =
    new CharacterField(message, HEADERSIZE + 353, 45, "E01NA4");
    fields[20] = fieldE01CTY =
    new CharacterField(message, HEADERSIZE + 398, 35, "E01CTY");
    fields[21] = fieldE01STE =
    new CharacterField(message, HEADERSIZE + 433, 4, "E01STE");
    fields[22] = fieldE01CTR =
    new CharacterField(message, HEADERSIZE + 437, 35, "E01CTR");
    fields[23] = fieldE01SHN =
    new CharacterField(message, HEADERSIZE + 472, 25, "E01SHN");
    fields[24] = fieldE01POB =
    new CharacterField(message, HEADERSIZE + 497, 10, "E01POB");
    fields[25] = fieldE01CCS =
    new CharacterField(message, HEADERSIZE + 507, 4, "E01CCS");
    fields[26] = fieldE01ZPC =
    new CharacterField(message, HEADERSIZE + 511, 15, "E01ZPC");
    fields[27] = fieldE01IDN =
    new CharacterField(message, HEADERSIZE + 526, 25, "E01IDN");
    fields[28] = fieldE01TID =
    new CharacterField(message, HEADERSIZE + 551, 4, "E01TID");
    fields[29] = fieldE01PID =
    new CharacterField(message, HEADERSIZE + 555, 4, "E01PID");
    fields[30] = fieldE01IDF =
    new CharacterField(message, HEADERSIZE + 559, 25, "E01IDF");
    fields[31] = fieldE01TIF =
    new CharacterField(message, HEADERSIZE + 584, 4, "E01TIF");
    fields[32] = fieldE01PIF =
    new CharacterField(message, HEADERSIZE + 588, 4, "E01PIF");
    fields[33] = fieldE01ID3 =
    new CharacterField(message, HEADERSIZE + 592, 25, "E01ID3");
    fields[34] = fieldE01TI3 =
    new CharacterField(message, HEADERSIZE + 617, 4, "E01TI3");
    fields[35] = fieldE01PI3 =
    new CharacterField(message, HEADERSIZE + 621, 4, "E01PI3");
    fields[36] = fieldE01ID4 =
    new CharacterField(message, HEADERSIZE + 625, 25, "E01ID4");
    fields[37] = fieldE01TI4 =
    new CharacterField(message, HEADERSIZE + 650, 4, "E01TI4");
    fields[38] = fieldE01PI4 =
    new CharacterField(message, HEADERSIZE + 654, 4, "E01PI4");
    fields[39] = fieldE01BDM =
    new DecimalField(message, HEADERSIZE + 658, 3, 0, "E01BDM");
    fields[40] = fieldE01BDD =
    new DecimalField(message, HEADERSIZE + 661, 3, 0, "E01BDD");
    fields[41] = fieldE01BDY =
    new DecimalField(message, HEADERSIZE + 664, 5, 0, "E01BDY");
    fields[42] = fieldE01LIF =
    new CharacterField(message, HEADERSIZE + 669, 1, "E01LIF");
    fields[43] = fieldE01RLV =
    new CharacterField(message, HEADERSIZE + 670, 1, "E01RLV");
    fields[44] = fieldE01GRP =
    new DecimalField(message, HEADERSIZE + 671, 10, 0, "E01GRP");
    fields[45] = fieldE01SEX =
    new CharacterField(message, HEADERSIZE + 681, 1, "E01SEX");
    fields[46] = fieldE01TYP =
    new CharacterField(message, HEADERSIZE + 682, 1, "E01TYP");
    fields[47] = fieldE01MST =
    new CharacterField(message, HEADERSIZE + 683, 1, "E01MST");
    fields[48] = fieldE01IDM =
    new DecimalField(message, HEADERSIZE + 684, 3, 0, "E01IDM");
    fields[49] = fieldE01IDD =
    new DecimalField(message, HEADERSIZE + 687, 3, 0, "E01IDD");
    fields[50] = fieldE01IDY =
    new DecimalField(message, HEADERSIZE + 690, 5, 0, "E01IDY");
    fields[51] = fieldE01ILV =
    new DecimalField(message, HEADERSIZE + 695, 2, 0, "E01ILV");
    fields[52] = fieldE01STS =
    new CharacterField(message, HEADERSIZE + 697, 1, "E01STS");
    fields[53] = fieldE01MLC =
    new CharacterField(message, HEADERSIZE + 698, 4, "E01MLC");
    fields[54] = fieldE01CCL =
    new CharacterField(message, HEADERSIZE + 702, 1, "E01CCL");
    fields[55] = fieldE01RSL =
    new CharacterField(message, HEADERSIZE + 703, 4, "E01RSL");
    fields[56] = fieldE01HPN =
    new DecimalField(message, HEADERSIZE + 707, 16, 0, "E01HPN");
    fields[57] = fieldE01HPNX =
    new DecimalField(message, HEADERSIZE + 723, 6, 0, "E01HPNX");
    fields[58] = fieldE01FL2 =
    new CharacterField(message, HEADERSIZE + 729, 1, "E01FL2");
    fields[59] = fieldE01PHN =
    new DecimalField(message, HEADERSIZE + 730, 16, 0, "E01PHN");
    fields[60] = fieldE01PHNX =
    new DecimalField(message, HEADERSIZE + 746, 6, 0, "E01PHNX");
    fields[61] = fieldE01PH1 =
    new DecimalField(message, HEADERSIZE + 752, 16, 0, "E01PH1");
    fields[62] = fieldE01FAX =
    new DecimalField(message, HEADERSIZE + 768, 16, 0, "E01FAX");
    fields[63] = fieldE01FAXX =
    new DecimalField(message, HEADERSIZE + 784, 6, 0, "E01FAXX");
    fields[64] = fieldE01EDL =
    new CharacterField(message, HEADERSIZE + 790, 4, "E01EDL");
    fields[65] = fieldE01INL =
    new CharacterField(message, HEADERSIZE + 794, 1, "E01INL");
    fields[66] = fieldE01BUC =
    new CharacterField(message, HEADERSIZE + 795, 4, "E01BUC");
    fields[67] = fieldE01COB =
    new CharacterField(message, HEADERSIZE + 799, 4, "E01COB");
    fields[68] = fieldE01RBY =
    new CharacterField(message, HEADERSIZE + 803, 4, "E01RBY");
    fields[69] = fieldE01RBN =
    new CharacterField(message, HEADERSIZE + 807, 45, "E01RBN");
    fields[70] = fieldE01FL3 =
    new CharacterField(message, HEADERSIZE + 852, 1, "E01FL3");
    fields[71] = fieldE01STF =
    new CharacterField(message, HEADERSIZE + 853, 1, "E01STF");
    fields[72] = fieldE01SOI =
    new CharacterField(message, HEADERSIZE + 854, 4, "E01SOI");
    fields[73] = fieldE01NSO =
    new DecimalField(message, HEADERSIZE + 858, 3, 0, "E01NSO");
    fields[74] = fieldE01FL1 =
    new CharacterField(message, HEADERSIZE + 861, 1, "E01FL1");
    fields[75] = fieldE01IAD =
    new CharacterField(message, HEADERSIZE + 862, 60, "E01IAD");
    fields[76] = fieldE01OFC =
    new CharacterField(message, HEADERSIZE + 922, 4, "E01OFC");
    fields[77] = fieldE01OF2 =
    new CharacterField(message, HEADERSIZE + 926, 4, "E01OF2");
    fields[78] = fieldE01INC =
    new CharacterField(message, HEADERSIZE + 930, 4, "E01INC");
    fields[79] = fieldE01GEC =
    new CharacterField(message, HEADERSIZE + 934, 4, "E01GEC");
    fields[80] = fieldE01UC1 =
    new CharacterField(message, HEADERSIZE + 938, 4, "E01UC1");
    fields[81] = fieldE01UC2 =
    new CharacterField(message, HEADERSIZE + 942, 4, "E01UC2");
    fields[82] = fieldE01UC3 =
    new CharacterField(message, HEADERSIZE + 946, 4, "E01UC3");
    fields[83] = fieldE01UC4 =
    new CharacterField(message, HEADERSIZE + 950, 6, "E01UC4");
    fields[84] = fieldE01UC5 =
    new CharacterField(message, HEADERSIZE + 956, 4, "E01UC5");
    fields[85] = fieldE01UC6 =
    new CharacterField(message, HEADERSIZE + 960, 4, "E01UC6");
    fields[86] = fieldE01UC7 =
    new CharacterField(message, HEADERSIZE + 964, 4, "E01UC7");
    fields[87] = fieldE01UC8 =
    new CharacterField(message, HEADERSIZE + 968, 4, "E01UC8");
    fields[88] = fieldE01UC9 =
    new CharacterField(message, HEADERSIZE + 972, 4, "E01UC9");
    fields[89] = fieldE01PRV =
    new CharacterField(message, HEADERSIZE + 976, 2, "E01PRV");
    fields[90] = fieldE01CMP =
    new CharacterField(message, HEADERSIZE + 978, 1, "E01CMP");
    fields[91] = fieldE01FL4 =
    new CharacterField(message, HEADERSIZE + 979, 1, "E01FL4");
    fields[92] = fieldE01SDY =
    new CharacterField(message, HEADERSIZE + 980, 2, "E01SDY");
    fields[93] = fieldE01FL5 =
    new CharacterField(message, HEADERSIZE + 982, 1, "E01FL5");
    fields[94] = fieldE01FL6 =
    new CharacterField(message, HEADERSIZE + 983, 1, "E01FL6");
    fields[95] = fieldE01FL7 =
    new CharacterField(message, HEADERSIZE + 984, 1, "E01FL7");
    fields[96] = fieldE01FL8 =
    new CharacterField(message, HEADERSIZE + 985, 8, "E01FL8");
    fields[97] = fieldE01WEB =
    new CharacterField(message, HEADERSIZE + 993, 60, "E01WEB");
    fields[98] = fieldE01BRA =
    new DecimalField(message, HEADERSIZE + 1053, 5, 0, "E01BRA");
    fields[99] = fieldE01SCH =
    new CharacterField(message, HEADERSIZE + 1058, 4, "E01SCH");
    fields[100] = fieldE01SST =
    new CharacterField(message, HEADERSIZE + 1062, 4, "E01SST");
    fields[101] = fieldE01FC1 =
    new CharacterField(message, HEADERSIZE + 1066, 4, "E01FC1");
    fields[102] = fieldE01FC2 =
    new CharacterField(message, HEADERSIZE + 1070, 4, "E01FC2");
    fields[103] = fieldE01TER =
    new DecimalField(message, HEADERSIZE + 1074, 6, 0, "E01TER");
    fields[104] = fieldE01FG1 =
    new CharacterField(message, HEADERSIZE + 1080, 1, "E01FG1");
    fields[105] = fieldE01FG2 =
    new CharacterField(message, HEADERSIZE + 1081, 1, "E01FG2");
    fields[106] = fieldE01AM1 =
    new DecimalField(message, HEADERSIZE + 1082, 17, 2, "E01AM1");
    fields[107] = fieldE01DD1 =
    new DecimalField(message, HEADERSIZE + 1099, 3, 0, "E01DD1");
    fields[108] = fieldE01DD2 =
    new DecimalField(message, HEADERSIZE + 1102, 3, 0, "E01DD2");
    fields[109] = fieldE01DD3 =
    new DecimalField(message, HEADERSIZE + 1105, 5, 0, "E01DD3");
    fields[110] = fieldE01D11 =
    new DecimalField(message, HEADERSIZE + 1110, 3, 0, "E01D11");
    fields[111] = fieldE01D12 =
    new DecimalField(message, HEADERSIZE + 1113, 3, 0, "E01D12");
    fields[112] = fieldE01D13 =
    new DecimalField(message, HEADERSIZE + 1116, 5, 0, "E01D13");
    fields[113] = fieldE01F01 =
    new CharacterField(message, HEADERSIZE + 1121, 4, "E01F01");
    fields[114] = fieldE01PHO1 =
    new DecimalField(message, HEADERSIZE + 1125, 16, 0, "E01PHO1");
    fields[115] = fieldE01PHO2 =
    new DecimalField(message, HEADERSIZE + 1141, 16, 0, "E01PHO2");
    fields[116] = fieldE01PHO3 =
    new DecimalField(message, HEADERSIZE + 1157, 16, 0, "E01PHO3");
    fields[117] = fieldD01STE =
    new CharacterField(message, HEADERSIZE + 1173, 45, "D01STE");
    fields[118] = fieldF01NA2 =
    new CharacterField(message, HEADERSIZE + 1218, 1, "F01NA2");
    fields[119] = fieldF01NA3 =
    new CharacterField(message, HEADERSIZE + 1219, 1, "F01NA3");
    fields[120] = fieldF01NA4 =
    new CharacterField(message, HEADERSIZE + 1220, 1, "F01NA4");
    fields[121] = fieldF01MLC =
    new CharacterField(message, HEADERSIZE + 1221, 1, "F01MLC");
    fields[122] = fieldF01STE =
    new CharacterField(message, HEADERSIZE + 1222, 1, "F01STE");
    fields[123] = fieldF01CTR =
    new CharacterField(message, HEADERSIZE + 1223, 1, "F01CTR");
    fields[124] = fieldF01POB =
    new CharacterField(message, HEADERSIZE + 1224, 1, "F01POB");
    fields[125] = fieldF01ZPC =
    new CharacterField(message, HEADERSIZE + 1225, 1, "F01ZPC");
    fields[126] = fieldF01IAD =
    new CharacterField(message, HEADERSIZE + 1226, 1, "F01IAD");
    fields[127] = fieldF01IDN =
    new CharacterField(message, HEADERSIZE + 1227, 1, "F01IDN");
    fields[128] = fieldF01TID =
    new CharacterField(message, HEADERSIZE + 1228, 1, "F01TID");
    fields[129] = fieldF01PID =
    new CharacterField(message, HEADERSIZE + 1229, 1, "F01PID");
    fields[130] = fieldF01IDF =
    new CharacterField(message, HEADERSIZE + 1230, 1, "F01IDF");
    fields[131] = fieldF01TIF =
    new CharacterField(message, HEADERSIZE + 1231, 1, "F01TIF");
    fields[132] = fieldF01PIF =
    new CharacterField(message, HEADERSIZE + 1232, 1, "F01PIF");
    fields[133] = fieldF01ID3 =
    new CharacterField(message, HEADERSIZE + 1233, 1, "F01ID3");
    fields[134] = fieldF01TI3 =
    new CharacterField(message, HEADERSIZE + 1234, 1, "F01TI3");
    fields[135] = fieldF01PI3 =
    new CharacterField(message, HEADERSIZE + 1235, 1, "F01PI3");
    fields[136] = fieldF01ID4 =
    new CharacterField(message, HEADERSIZE + 1236, 1, "F01ID4");
    fields[137] = fieldF01TI4 =
    new CharacterField(message, HEADERSIZE + 1237, 1, "F01TI4");
    fields[138] = fieldF01PI4 =
    new CharacterField(message, HEADERSIZE + 1238, 1, "F01PI4");
    fields[139] = fieldE01NUMREC =
    new DecimalField(message, HEADERSIZE + 1239, 8, 0, "E01NUMREC");
    fields[140] = fieldE01INDOPE =
    new CharacterField(message, HEADERSIZE + 1247, 1, "E01INDOPE");

    synchronized (tlookup)
    {
      if (tlookup.isEmpty())
      {
        for (int i = 0; i < tnames.length; i++)
          tlookup.put(tnames[i], new Integer(i));
      }
    }

    taglookup = tlookup;
  }

  /**
  * Set field H01USERID using a String value.
  */
  public void setH01USERID(String newvalue)
  {
    fieldH01USERID.setString(newvalue);
  }

  /**
  * Get value of field H01USERID as a String.
  */
  public String getH01USERID()
  {
    return fieldH01USERID.getString();
  }

  /**
  * Set field H01PROGRM using a String value.
  */
  public void setH01PROGRM(String newvalue)
  {
    fieldH01PROGRM.setString(newvalue);
  }

  /**
  * Get value of field H01PROGRM as a String.
  */
  public String getH01PROGRM()
  {
    return fieldH01PROGRM.getString();
  }

  /**
  * Set field H01TIMSYS using a String value.
  */
  public void setH01TIMSYS(String newvalue)
  {
    fieldH01TIMSYS.setString(newvalue);
  }

  /**
  * Get value of field H01TIMSYS as a String.
  */
  public String getH01TIMSYS()
  {
    return fieldH01TIMSYS.getString();
  }

  /**
  * Set field H01SCR using a String value.
  */
  public void setH01SCR(String newvalue)
  {
    fieldH01SCR.setString(newvalue);
  }

  /**
  * Get value of field H01SCR as a String.
  */
  public String getH01SCR()
  {
    return fieldH01SCR.getString();
  }

  /**
  * Set field H01OPECOD using a String value.
  */
  public void setH01OPECOD(String newvalue)
  {
    fieldH01OPECOD.setString(newvalue);
  }

  /**
  * Get value of field H01OPECOD as a String.
  */
  public String getH01OPECOD()
  {
    return fieldH01OPECOD.getString();
  }

  /**
  * Set field H01FLGMAS using a String value.
  */
  public void setH01FLGMAS(String newvalue)
  {
    fieldH01FLGMAS.setString(newvalue);
  }

  /**
  * Get value of field H01FLGMAS as a String.
  */
  public String getH01FLGMAS()
  {
    return fieldH01FLGMAS.getString();
  }

  /**
  * Set field H01FLGWK1 using a String value.
  */
  public void setH01FLGWK1(String newvalue)
  {
    fieldH01FLGWK1.setString(newvalue);
  }

  /**
  * Get value of field H01FLGWK1 as a String.
  */
  public String getH01FLGWK1()
  {
    return fieldH01FLGWK1.getString();
  }

  /**
  * Set field H01FLGWK2 using a String value.
  */
  public void setH01FLGWK2(String newvalue)
  {
    fieldH01FLGWK2.setString(newvalue);
  }

  /**
  * Get value of field H01FLGWK2 as a String.
  */
  public String getH01FLGWK2()
  {
    return fieldH01FLGWK2.getString();
  }

  /**
  * Set field H01FLGWK3 using a String value.
  */
  public void setH01FLGWK3(String newvalue)
  {
    fieldH01FLGWK3.setString(newvalue);
  }

  /**
  * Get value of field H01FLGWK3 as a String.
  */
  public String getH01FLGWK3()
  {
    return fieldH01FLGWK3.getString();
  }

  /**
  * Set field E01LGT using a String value.
  */
  public void setE01LGT(String newvalue)
  {
    fieldE01LGT.setString(newvalue);
  }

  /**
  * Get value of field E01LGT as a String.
  */
  public String getE01LGT()
  {
    return fieldE01LGT.getString();
  }

  /**
  * Set field E01CUN using a String value.
  */
  public void setE01CUN(String newvalue)
  {
    fieldE01CUN.setString(newvalue);
  }

  /**
  * Get value of field E01CUN as a String.
  */
  public String getE01CUN()
  {
    return fieldE01CUN.getString();
  }

  /**
  * Set numeric field E01CUN using a BigDecimal value.
  */
  public void setE01CUN(BigDecimal newvalue)
  {
    fieldE01CUN.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CUN as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CUN()
  {
    return fieldE01CUN.getBigDecimal();
  }

  /**
  * Set field E01FNA using a String value.
  */
  public void setE01FNA(String newvalue)
  {
    fieldE01FNA.setString(newvalue);
  }

  /**
  * Get value of field E01FNA as a String.
  */
  public String getE01FNA()
  {
    return fieldE01FNA.getString();
  }

  /**
  * Set field E01FN2 using a String value.
  */
  public void setE01FN2(String newvalue)
  {
    fieldE01FN2.setString(newvalue);
  }

  /**
  * Get value of field E01FN2 as a String.
  */
  public String getE01FN2()
  {
    return fieldE01FN2.getString();
  }

  /**
  * Set field E01LN1 using a String value.
  */
  public void setE01LN1(String newvalue)
  {
    fieldE01LN1.setString(newvalue);
  }

  /**
  * Get value of field E01LN1 as a String.
  */
  public String getE01LN1()
  {
    return fieldE01LN1.getString();
  }

  /**
  * Set field E01LN2 using a String value.
  */
  public void setE01LN2(String newvalue)
  {
    fieldE01LN2.setString(newvalue);
  }

  /**
  * Get value of field E01LN2 as a String.
  */
  public String getE01LN2()
  {
    return fieldE01LN2.getString();
  }

  /**
  * Set field E01ACA using a String value.
  */
  public void setE01ACA(String newvalue)
  {
    fieldE01ACA.setString(newvalue);
  }

  /**
  * Get value of field E01ACA as a String.
  */
  public String getE01ACA()
  {
    return fieldE01ACA.getString();
  }

  /**
  * Set field E01NA1 using a String value.
  */
  public void setE01NA1(String newvalue)
  {
    fieldE01NA1.setString(newvalue);
  }

  /**
  * Get value of field E01NA1 as a String.
  */
  public String getE01NA1()
  {
    return fieldE01NA1.getString();
  }

  /**
  * Set field E01NA2 using a String value.
  */
  public void setE01NA2(String newvalue)
  {
    fieldE01NA2.setString(newvalue);
  }

  /**
  * Get value of field E01NA2 as a String.
  */
  public String getE01NA2()
  {
    return fieldE01NA2.getString();
  }

  /**
  * Set field E01NA3 using a String value.
  */
  public void setE01NA3(String newvalue)
  {
    fieldE01NA3.setString(newvalue);
  }

  /**
  * Get value of field E01NA3 as a String.
  */
  public String getE01NA3()
  {
    return fieldE01NA3.getString();
  }

  /**
  * Set field E01NA4 using a String value.
  */
  public void setE01NA4(String newvalue)
  {
    fieldE01NA4.setString(newvalue);
  }

  /**
  * Get value of field E01NA4 as a String.
  */
  public String getE01NA4()
  {
    return fieldE01NA4.getString();
  }

  /**
  * Set field E01CTY using a String value.
  */
  public void setE01CTY(String newvalue)
  {
    fieldE01CTY.setString(newvalue);
  }

  /**
  * Get value of field E01CTY as a String.
  */
  public String getE01CTY()
  {
    return fieldE01CTY.getString();
  }

  /**
  * Set field E01STE using a String value.
  */
  public void setE01STE(String newvalue)
  {
    fieldE01STE.setString(newvalue);
  }

  /**
  * Get value of field E01STE as a String.
  */
  public String getE01STE()
  {
    return fieldE01STE.getString();
  }

  /**
  * Set field E01CTR using a String value.
  */
  public void setE01CTR(String newvalue)
  {
    fieldE01CTR.setString(newvalue);
  }

  /**
  * Get value of field E01CTR as a String.
  */
  public String getE01CTR()
  {
    return fieldE01CTR.getString();
  }

  /**
  * Set field E01SHN using a String value.
  */
  public void setE01SHN(String newvalue)
  {
    fieldE01SHN.setString(newvalue);
  }

  /**
  * Get value of field E01SHN as a String.
  */
  public String getE01SHN()
  {
    return fieldE01SHN.getString();
  }

  /**
  * Set field E01POB using a String value.
  */
  public void setE01POB(String newvalue)
  {
    fieldE01POB.setString(newvalue);
  }

  /**
  * Get value of field E01POB as a String.
  */
  public String getE01POB()
  {
    return fieldE01POB.getString();
  }

  /**
  * Set field E01CCS using a String value.
  */
  public void setE01CCS(String newvalue)
  {
    fieldE01CCS.setString(newvalue);
  }

  /**
  * Get value of field E01CCS as a String.
  */
  public String getE01CCS()
  {
    return fieldE01CCS.getString();
  }

  /**
  * Set field E01ZPC using a String value.
  */
  public void setE01ZPC(String newvalue)
  {
    fieldE01ZPC.setString(newvalue);
  }

  /**
  * Get value of field E01ZPC as a String.
  */
  public String getE01ZPC()
  {
    return fieldE01ZPC.getString();
  }

  /**
  * Set field E01IDN using a String value.
  */
  public void setE01IDN(String newvalue)
  {
    fieldE01IDN.setString(newvalue);
  }

  /**
  * Get value of field E01IDN as a String.
  */
  public String getE01IDN()
  {
    return fieldE01IDN.getString();
  }

  /**
  * Set field E01TID using a String value.
  */
  public void setE01TID(String newvalue)
  {
    fieldE01TID.setString(newvalue);
  }

  /**
  * Get value of field E01TID as a String.
  */
  public String getE01TID()
  {
    return fieldE01TID.getString();
  }

  /**
  * Set field E01PID using a String value.
  */
  public void setE01PID(String newvalue)
  {
    fieldE01PID.setString(newvalue);
  }

  /**
  * Get value of field E01PID as a String.
  */
  public String getE01PID()
  {
    return fieldE01PID.getString();
  }

  /**
  * Set field E01IDF using a String value.
  */
  public void setE01IDF(String newvalue)
  {
    fieldE01IDF.setString(newvalue);
  }

  /**
  * Get value of field E01IDF as a String.
  */
  public String getE01IDF()
  {
    return fieldE01IDF.getString();
  }

  /**
  * Set field E01TIF using a String value.
  */
  public void setE01TIF(String newvalue)
  {
    fieldE01TIF.setString(newvalue);
  }

  /**
  * Get value of field E01TIF as a String.
  */
  public String getE01TIF()
  {
    return fieldE01TIF.getString();
  }

  /**
  * Set field E01PIF using a String value.
  */
  public void setE01PIF(String newvalue)
  {
    fieldE01PIF.setString(newvalue);
  }

  /**
  * Get value of field E01PIF as a String.
  */
  public String getE01PIF()
  {
    return fieldE01PIF.getString();
  }

  /**
  * Set field E01ID3 using a String value.
  */
  public void setE01ID3(String newvalue)
  {
    fieldE01ID3.setString(newvalue);
  }

  /**
  * Get value of field E01ID3 as a String.
  */
  public String getE01ID3()
  {
    return fieldE01ID3.getString();
  }

  /**
  * Set field E01TI3 using a String value.
  */
  public void setE01TI3(String newvalue)
  {
    fieldE01TI3.setString(newvalue);
  }

  /**
  * Get value of field E01TI3 as a String.
  */
  public String getE01TI3()
  {
    return fieldE01TI3.getString();
  }

  /**
  * Set field E01PI3 using a String value.
  */
  public void setE01PI3(String newvalue)
  {
    fieldE01PI3.setString(newvalue);
  }

  /**
  * Get value of field E01PI3 as a String.
  */
  public String getE01PI3()
  {
    return fieldE01PI3.getString();
  }

  /**
  * Set field E01ID4 using a String value.
  */
  public void setE01ID4(String newvalue)
  {
    fieldE01ID4.setString(newvalue);
  }

  /**
  * Get value of field E01ID4 as a String.
  */
  public String getE01ID4()
  {
    return fieldE01ID4.getString();
  }

  /**
  * Set field E01TI4 using a String value.
  */
  public void setE01TI4(String newvalue)
  {
    fieldE01TI4.setString(newvalue);
  }

  /**
  * Get value of field E01TI4 as a String.
  */
  public String getE01TI4()
  {
    return fieldE01TI4.getString();
  }

  /**
  * Set field E01PI4 using a String value.
  */
  public void setE01PI4(String newvalue)
  {
    fieldE01PI4.setString(newvalue);
  }

  /**
  * Get value of field E01PI4 as a String.
  */
  public String getE01PI4()
  {
    return fieldE01PI4.getString();
  }

  /**
  * Set field E01BDM using a String value.
  */
  public void setE01BDM(String newvalue)
  {
    fieldE01BDM.setString(newvalue);
  }

  /**
  * Get value of field E01BDM as a String.
  */
  public String getE01BDM()
  {
    return fieldE01BDM.getString();
  }

  /**
  * Set numeric field E01BDM using a BigDecimal value.
  */
  public void setE01BDM(BigDecimal newvalue)
  {
    fieldE01BDM.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01BDM as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01BDM()
  {
    return fieldE01BDM.getBigDecimal();
  }

  /**
  * Set field E01BDD using a String value.
  */
  public void setE01BDD(String newvalue)
  {
    fieldE01BDD.setString(newvalue);
  }

  /**
  * Get value of field E01BDD as a String.
  */
  public String getE01BDD()
  {
    return fieldE01BDD.getString();
  }

  /**
  * Set numeric field E01BDD using a BigDecimal value.
  */
  public void setE01BDD(BigDecimal newvalue)
  {
    fieldE01BDD.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01BDD as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01BDD()
  {
    return fieldE01BDD.getBigDecimal();
  }

  /**
  * Set field E01BDY using a String value.
  */
  public void setE01BDY(String newvalue)
  {
    fieldE01BDY.setString(newvalue);
  }

  /**
  * Get value of field E01BDY as a String.
  */
  public String getE01BDY()
  {
    return fieldE01BDY.getString();
  }

  /**
  * Set numeric field E01BDY using a BigDecimal value.
  */
  public void setE01BDY(BigDecimal newvalue)
  {
    fieldE01BDY.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01BDY as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01BDY()
  {
    return fieldE01BDY.getBigDecimal();
  }

  /**
  * Set field E01LIF using a String value.
  */
  public void setE01LIF(String newvalue)
  {
    fieldE01LIF.setString(newvalue);
  }

  /**
  * Get value of field E01LIF as a String.
  */
  public String getE01LIF()
  {
    return fieldE01LIF.getString();
  }

  /**
  * Set field E01RLV using a String value.
  */
  public void setE01RLV(String newvalue)
  {
    fieldE01RLV.setString(newvalue);
  }

  /**
  * Get value of field E01RLV as a String.
  */
  public String getE01RLV()
  {
    return fieldE01RLV.getString();
  }

  /**
  * Set field E01GRP using a String value.
  */
  public void setE01GRP(String newvalue)
  {
    fieldE01GRP.setString(newvalue);
  }

  /**
  * Get value of field E01GRP as a String.
  */
  public String getE01GRP()
  {
    return fieldE01GRP.getString();
  }

  /**
  * Set numeric field E01GRP using a BigDecimal value.
  */
  public void setE01GRP(BigDecimal newvalue)
  {
    fieldE01GRP.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01GRP as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01GRP()
  {
    return fieldE01GRP.getBigDecimal();
  }

  /**
  * Set field E01SEX using a String value.
  */
  public void setE01SEX(String newvalue)
  {
    fieldE01SEX.setString(newvalue);
  }

  /**
  * Get value of field E01SEX as a String.
  */
  public String getE01SEX()
  {
    return fieldE01SEX.getString();
  }

  /**
  * Set field E01TYP using a String value.
  */
  public void setE01TYP(String newvalue)
  {
    fieldE01TYP.setString(newvalue);
  }

  /**
  * Get value of field E01TYP as a String.
  */
  public String getE01TYP()
  {
    return fieldE01TYP.getString();
  }

  /**
  * Set field E01MST using a String value.
  */
  public void setE01MST(String newvalue)
  {
    fieldE01MST.setString(newvalue);
  }

  /**
  * Get value of field E01MST as a String.
  */
  public String getE01MST()
  {
    return fieldE01MST.getString();
  }

  /**
  * Set field E01IDM using a String value.
  */
  public void setE01IDM(String newvalue)
  {
    fieldE01IDM.setString(newvalue);
  }

  /**
  * Get value of field E01IDM as a String.
  */
  public String getE01IDM()
  {
    return fieldE01IDM.getString();
  }

  /**
  * Set numeric field E01IDM using a BigDecimal value.
  */
  public void setE01IDM(BigDecimal newvalue)
  {
    fieldE01IDM.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01IDM as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01IDM()
  {
    return fieldE01IDM.getBigDecimal();
  }

  /**
  * Set field E01IDD using a String value.
  */
  public void setE01IDD(String newvalue)
  {
    fieldE01IDD.setString(newvalue);
  }

  /**
  * Get value of field E01IDD as a String.
  */
  public String getE01IDD()
  {
    return fieldE01IDD.getString();
  }

  /**
  * Set numeric field E01IDD using a BigDecimal value.
  */
  public void setE01IDD(BigDecimal newvalue)
  {
    fieldE01IDD.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01IDD as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01IDD()
  {
    return fieldE01IDD.getBigDecimal();
  }

  /**
  * Set field E01IDY using a String value.
  */
  public void setE01IDY(String newvalue)
  {
    fieldE01IDY.setString(newvalue);
  }

  /**
  * Get value of field E01IDY as a String.
  */
  public String getE01IDY()
  {
    return fieldE01IDY.getString();
  }

  /**
  * Set numeric field E01IDY using a BigDecimal value.
  */
  public void setE01IDY(BigDecimal newvalue)
  {
    fieldE01IDY.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01IDY as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01IDY()
  {
    return fieldE01IDY.getBigDecimal();
  }

  /**
  * Set field E01ILV using a String value.
  */
  public void setE01ILV(String newvalue)
  {
    fieldE01ILV.setString(newvalue);
  }

  /**
  * Get value of field E01ILV as a String.
  */
  public String getE01ILV()
  {
    return fieldE01ILV.getString();
  }

  /**
  * Set numeric field E01ILV using a BigDecimal value.
  */
  public void setE01ILV(BigDecimal newvalue)
  {
    fieldE01ILV.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01ILV as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01ILV()
  {
    return fieldE01ILV.getBigDecimal();
  }

  /**
  * Set field E01STS using a String value.
  */
  public void setE01STS(String newvalue)
  {
    fieldE01STS.setString(newvalue);
  }

  /**
  * Get value of field E01STS as a String.
  */
  public String getE01STS()
  {
    return fieldE01STS.getString();
  }

  /**
  * Set field E01MLC using a String value.
  */
  public void setE01MLC(String newvalue)
  {
    fieldE01MLC.setString(newvalue);
  }

  /**
  * Get value of field E01MLC as a String.
  */
  public String getE01MLC()
  {
    return fieldE01MLC.getString();
  }

  /**
  * Set field E01CCL using a String value.
  */
  public void setE01CCL(String newvalue)
  {
    fieldE01CCL.setString(newvalue);
  }

  /**
  * Get value of field E01CCL as a String.
  */
  public String getE01CCL()
  {
    return fieldE01CCL.getString();
  }

  /**
  * Set field E01RSL using a String value.
  */
  public void setE01RSL(String newvalue)
  {
    fieldE01RSL.setString(newvalue);
  }

  /**
  * Get value of field E01RSL as a String.
  */
  public String getE01RSL()
  {
    return fieldE01RSL.getString();
  }

  /**
  * Set field E01HPN using a String value.
  */
  public void setE01HPN(String newvalue)
  {
    fieldE01HPN.setString(newvalue);
  }

  /**
  * Get value of field E01HPN as a String.
  */
  public String getE01HPN()
  {
    return fieldE01HPN.getString();
  }

  /**
  * Set numeric field E01HPN using a BigDecimal value.
  */
  public void setE01HPN(BigDecimal newvalue)
  {
    fieldE01HPN.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01HPN as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01HPN()
  {
    return fieldE01HPN.getBigDecimal();
  }

  /**
  * Set field E01HPNX using a String value.
  */
  public void setE01HPNX(String newvalue)
  {
    fieldE01HPNX.setString(newvalue);
  }

  /**
  * Get value of field E01HPNX as a String.
  */
  public String getE01HPNX()
  {
    return fieldE01HPNX.getString();
  }

  /**
  * Set numeric field E01HPNX using a BigDecimal value.
  */
  public void setE01HPNX(BigDecimal newvalue)
  {
    fieldE01HPNX.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01HPNX as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01HPNX()
  {
    return fieldE01HPNX.getBigDecimal();
  }

  /**
  * Set field E01FL2 using a String value.
  */
  public void setE01FL2(String newvalue)
  {
    fieldE01FL2.setString(newvalue);
  }

  /**
  * Get value of field E01FL2 as a String.
  */
  public String getE01FL2()
  {
    return fieldE01FL2.getString();
  }

  /**
  * Set field E01PHN using a String value.
  */
  public void setE01PHN(String newvalue)
  {
    fieldE01PHN.setString(newvalue);
  }

  /**
  * Get value of field E01PHN as a String.
  */
  public String getE01PHN()
  {
    return fieldE01PHN.getString();
  }

  /**
  * Set numeric field E01PHN using a BigDecimal value.
  */
  public void setE01PHN(BigDecimal newvalue)
  {
    fieldE01PHN.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01PHN as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01PHN()
  {
    return fieldE01PHN.getBigDecimal();
  }

  /**
  * Set field E01PHNX using a String value.
  */
  public void setE01PHNX(String newvalue)
  {
    fieldE01PHNX.setString(newvalue);
  }

  /**
  * Get value of field E01PHNX as a String.
  */
  public String getE01PHNX()
  {
    return fieldE01PHNX.getString();
  }

  /**
  * Set numeric field E01PHNX using a BigDecimal value.
  */
  public void setE01PHNX(BigDecimal newvalue)
  {
    fieldE01PHNX.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01PHNX as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01PHNX()
  {
    return fieldE01PHNX.getBigDecimal();
  }

  /**
  * Set field E01PH1 using a String value.
  */
  public void setE01PH1(String newvalue)
  {
    fieldE01PH1.setString(newvalue);
  }

  /**
  * Get value of field E01PH1 as a String.
  */
  public String getE01PH1()
  {
    return fieldE01PH1.getString();
  }

  /**
  * Set numeric field E01PH1 using a BigDecimal value.
  */
  public void setE01PH1(BigDecimal newvalue)
  {
    fieldE01PH1.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01PH1 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01PH1()
  {
    return fieldE01PH1.getBigDecimal();
  }

  /**
  * Set field E01FAX using a String value.
  */
  public void setE01FAX(String newvalue)
  {
    fieldE01FAX.setString(newvalue);
  }

  /**
  * Get value of field E01FAX as a String.
  */
  public String getE01FAX()
  {
    return fieldE01FAX.getString();
  }

  /**
  * Set numeric field E01FAX using a BigDecimal value.
  */
  public void setE01FAX(BigDecimal newvalue)
  {
    fieldE01FAX.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01FAX as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01FAX()
  {
    return fieldE01FAX.getBigDecimal();
  }

  /**
  * Set field E01FAXX using a String value.
  */
  public void setE01FAXX(String newvalue)
  {
    fieldE01FAXX.setString(newvalue);
  }

  /**
  * Get value of field E01FAXX as a String.
  */
  public String getE01FAXX()
  {
    return fieldE01FAXX.getString();
  }

  /**
  * Set numeric field E01FAXX using a BigDecimal value.
  */
  public void setE01FAXX(BigDecimal newvalue)
  {
    fieldE01FAXX.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01FAXX as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01FAXX()
  {
    return fieldE01FAXX.getBigDecimal();
  }

  /**
  * Set field E01EDL using a String value.
  */
  public void setE01EDL(String newvalue)
  {
    fieldE01EDL.setString(newvalue);
  }

  /**
  * Get value of field E01EDL as a String.
  */
  public String getE01EDL()
  {
    return fieldE01EDL.getString();
  }

  /**
  * Set field E01INL using a String value.
  */
  public void setE01INL(String newvalue)
  {
    fieldE01INL.setString(newvalue);
  }

  /**
  * Get value of field E01INL as a String.
  */
  public String getE01INL()
  {
    return fieldE01INL.getString();
  }

  /**
  * Set field E01BUC using a String value.
  */
  public void setE01BUC(String newvalue)
  {
    fieldE01BUC.setString(newvalue);
  }

  /**
  * Get value of field E01BUC as a String.
  */
  public String getE01BUC()
  {
    return fieldE01BUC.getString();
  }

  /**
  * Set field E01COB using a String value.
  */
  public void setE01COB(String newvalue)
  {
    fieldE01COB.setString(newvalue);
  }

  /**
  * Get value of field E01COB as a String.
  */
  public String getE01COB()
  {
    return fieldE01COB.getString();
  }

  /**
  * Set field E01RBY using a String value.
  */
  public void setE01RBY(String newvalue)
  {
    fieldE01RBY.setString(newvalue);
  }

  /**
  * Get value of field E01RBY as a String.
  */
  public String getE01RBY()
  {
    return fieldE01RBY.getString();
  }

  /**
  * Set field E01RBN using a String value.
  */
  public void setE01RBN(String newvalue)
  {
    fieldE01RBN.setString(newvalue);
  }

  /**
  * Get value of field E01RBN as a String.
  */
  public String getE01RBN()
  {
    return fieldE01RBN.getString();
  }

  /**
  * Set field E01FL3 using a String value.
  */
  public void setE01FL3(String newvalue)
  {
    fieldE01FL3.setString(newvalue);
  }

  /**
  * Get value of field E01FL3 as a String.
  */
  public String getE01FL3()
  {
    return fieldE01FL3.getString();
  }

  /**
  * Set field E01STF using a String value.
  */
  public void setE01STF(String newvalue)
  {
    fieldE01STF.setString(newvalue);
  }

  /**
  * Get value of field E01STF as a String.
  */
  public String getE01STF()
  {
    return fieldE01STF.getString();
  }

  /**
  * Set field E01SOI using a String value.
  */
  public void setE01SOI(String newvalue)
  {
    fieldE01SOI.setString(newvalue);
  }

  /**
  * Get value of field E01SOI as a String.
  */
  public String getE01SOI()
  {
    return fieldE01SOI.getString();
  }

  /**
  * Set field E01NSO using a String value.
  */
  public void setE01NSO(String newvalue)
  {
    fieldE01NSO.setString(newvalue);
  }

  /**
  * Get value of field E01NSO as a String.
  */
  public String getE01NSO()
  {
    return fieldE01NSO.getString();
  }

  /**
  * Set numeric field E01NSO using a BigDecimal value.
  */
  public void setE01NSO(BigDecimal newvalue)
  {
    fieldE01NSO.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01NSO as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01NSO()
  {
    return fieldE01NSO.getBigDecimal();
  }

  /**
  * Set field E01FL1 using a String value.
  */
  public void setE01FL1(String newvalue)
  {
    fieldE01FL1.setString(newvalue);
  }

  /**
  * Get value of field E01FL1 as a String.
  */
  public String getE01FL1()
  {
    return fieldE01FL1.getString();
  }

  /**
  * Set field E01IAD using a String value.
  */
  public void setE01IAD(String newvalue)
  {
    fieldE01IAD.setString(newvalue);
  }

  /**
  * Get value of field E01IAD as a String.
  */
  public String getE01IAD()
  {
    return fieldE01IAD.getString();
  }

  /**
  * Set field E01OFC using a String value.
  */
  public void setE01OFC(String newvalue)
  {
    fieldE01OFC.setString(newvalue);
  }

  /**
  * Get value of field E01OFC as a String.
  */
  public String getE01OFC()
  {
    return fieldE01OFC.getString();
  }

  /**
  * Set field E01OF2 using a String value.
  */
  public void setE01OF2(String newvalue)
  {
    fieldE01OF2.setString(newvalue);
  }

  /**
  * Get value of field E01OF2 as a String.
  */
  public String getE01OF2()
  {
    return fieldE01OF2.getString();
  }

  /**
  * Set field E01INC using a String value.
  */
  public void setE01INC(String newvalue)
  {
    fieldE01INC.setString(newvalue);
  }

  /**
  * Get value of field E01INC as a String.
  */
  public String getE01INC()
  {
    return fieldE01INC.getString();
  }

  /**
  * Set field E01GEC using a String value.
  */
  public void setE01GEC(String newvalue)
  {
    fieldE01GEC.setString(newvalue);
  }

  /**
  * Get value of field E01GEC as a String.
  */
  public String getE01GEC()
  {
    return fieldE01GEC.getString();
  }

  /**
  * Set field E01UC1 using a String value.
  */
  public void setE01UC1(String newvalue)
  {
    fieldE01UC1.setString(newvalue);
  }

  /**
  * Get value of field E01UC1 as a String.
  */
  public String getE01UC1()
  {
    return fieldE01UC1.getString();
  }

  /**
  * Set field E01UC2 using a String value.
  */
  public void setE01UC2(String newvalue)
  {
    fieldE01UC2.setString(newvalue);
  }

  /**
  * Get value of field E01UC2 as a String.
  */
  public String getE01UC2()
  {
    return fieldE01UC2.getString();
  }

  /**
  * Set field E01UC3 using a String value.
  */
  public void setE01UC3(String newvalue)
  {
    fieldE01UC3.setString(newvalue);
  }

  /**
  * Get value of field E01UC3 as a String.
  */
  public String getE01UC3()
  {
    return fieldE01UC3.getString();
  }

  /**
  * Set field E01UC4 using a String value.
  */
  public void setE01UC4(String newvalue)
  {
    fieldE01UC4.setString(newvalue);
  }

  /**
  * Get value of field E01UC4 as a String.
  */
  public String getE01UC4()
  {
    return fieldE01UC4.getString();
  }

  /**
  * Set field E01UC5 using a String value.
  */
  public void setE01UC5(String newvalue)
  {
    fieldE01UC5.setString(newvalue);
  }

  /**
  * Get value of field E01UC5 as a String.
  */
  public String getE01UC5()
  {
    return fieldE01UC5.getString();
  }

  /**
  * Set field E01UC6 using a String value.
  */
  public void setE01UC6(String newvalue)
  {
    fieldE01UC6.setString(newvalue);
  }

  /**
  * Get value of field E01UC6 as a String.
  */
  public String getE01UC6()
  {
    return fieldE01UC6.getString();
  }

  /**
  * Set field E01UC7 using a String value.
  */
  public void setE01UC7(String newvalue)
  {
    fieldE01UC7.setString(newvalue);
  }

  /**
  * Get value of field E01UC7 as a String.
  */
  public String getE01UC7()
  {
    return fieldE01UC7.getString();
  }

  /**
  * Set field E01UC8 using a String value.
  */
  public void setE01UC8(String newvalue)
  {
    fieldE01UC8.setString(newvalue);
  }

  /**
  * Get value of field E01UC8 as a String.
  */
  public String getE01UC8()
  {
    return fieldE01UC8.getString();
  }

  /**
  * Set field E01UC9 using a String value.
  */
  public void setE01UC9(String newvalue)
  {
    fieldE01UC9.setString(newvalue);
  }

  /**
  * Get value of field E01UC9 as a String.
  */
  public String getE01UC9()
  {
    return fieldE01UC9.getString();
  }

  /**
  * Set field E01PRV using a String value.
  */
  public void setE01PRV(String newvalue)
  {
    fieldE01PRV.setString(newvalue);
  }

  /**
  * Get value of field E01PRV as a String.
  */
  public String getE01PRV()
  {
    return fieldE01PRV.getString();
  }

  /**
  * Set field E01CMP using a String value.
  */
  public void setE01CMP(String newvalue)
  {
    fieldE01CMP.setString(newvalue);
  }

  /**
  * Get value of field E01CMP as a String.
  */
  public String getE01CMP()
  {
    return fieldE01CMP.getString();
  }

  /**
  * Set field E01FL4 using a String value.
  */
  public void setE01FL4(String newvalue)
  {
    fieldE01FL4.setString(newvalue);
  }

  /**
  * Get value of field E01FL4 as a String.
  */
  public String getE01FL4()
  {
    return fieldE01FL4.getString();
  }

  /**
  * Set field E01SDY using a String value.
  */
  public void setE01SDY(String newvalue)
  {
    fieldE01SDY.setString(newvalue);
  }

  /**
  * Get value of field E01SDY as a String.
  */
  public String getE01SDY()
  {
    return fieldE01SDY.getString();
  }

  /**
  * Set field E01FL5 using a String value.
  */
  public void setE01FL5(String newvalue)
  {
    fieldE01FL5.setString(newvalue);
  }

  /**
  * Get value of field E01FL5 as a String.
  */
  public String getE01FL5()
  {
    return fieldE01FL5.getString();
  }

  /**
  * Set field E01FL6 using a String value.
  */
  public void setE01FL6(String newvalue)
  {
    fieldE01FL6.setString(newvalue);
  }

  /**
  * Get value of field E01FL6 as a String.
  */
  public String getE01FL6()
  {
    return fieldE01FL6.getString();
  }

  /**
  * Set field E01FL7 using a String value.
  */
  public void setE01FL7(String newvalue)
  {
    fieldE01FL7.setString(newvalue);
  }

  /**
  * Get value of field E01FL7 as a String.
  */
  public String getE01FL7()
  {
    return fieldE01FL7.getString();
  }

  /**
  * Set field E01FL8 using a String value.
  */
  public void setE01FL8(String newvalue)
  {
    fieldE01FL8.setString(newvalue);
  }

  /**
  * Get value of field E01FL8 as a String.
  */
  public String getE01FL8()
  {
    return fieldE01FL8.getString();
  }

  /**
  * Set field E01WEB using a String value.
  */
  public void setE01WEB(String newvalue)
  {
    fieldE01WEB.setString(newvalue);
  }

  /**
  * Get value of field E01WEB as a String.
  */
  public String getE01WEB()
  {
    return fieldE01WEB.getString();
  }

  /**
  * Set field E01BRA using a String value.
  */
  public void setE01BRA(String newvalue)
  {
    fieldE01BRA.setString(newvalue);
  }

  /**
  * Get value of field E01BRA as a String.
  */
  public String getE01BRA()
  {
    return fieldE01BRA.getString();
  }

  /**
  * Set numeric field E01BRA using a BigDecimal value.
  */
  public void setE01BRA(BigDecimal newvalue)
  {
    fieldE01BRA.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01BRA as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01BRA()
  {
    return fieldE01BRA.getBigDecimal();
  }

  /**
  * Set field E01SCH using a String value.
  */
  public void setE01SCH(String newvalue)
  {
    fieldE01SCH.setString(newvalue);
  }

  /**
  * Get value of field E01SCH as a String.
  */
  public String getE01SCH()
  {
    return fieldE01SCH.getString();
  }

  /**
  * Set field E01SST using a String value.
  */
  public void setE01SST(String newvalue)
  {
    fieldE01SST.setString(newvalue);
  }

  /**
  * Get value of field E01SST as a String.
  */
  public String getE01SST()
  {
    return fieldE01SST.getString();
  }

  /**
  * Set field E01FC1 using a String value.
  */
  public void setE01FC1(String newvalue)
  {
    fieldE01FC1.setString(newvalue);
  }

  /**
  * Get value of field E01FC1 as a String.
  */
  public String getE01FC1()
  {
    return fieldE01FC1.getString();
  }

  /**
  * Set field E01FC2 using a String value.
  */
  public void setE01FC2(String newvalue)
  {
    fieldE01FC2.setString(newvalue);
  }

  /**
  * Get value of field E01FC2 as a String.
  */
  public String getE01FC2()
  {
    return fieldE01FC2.getString();
  }

  /**
  * Set field E01TER using a String value.
  */
  public void setE01TER(String newvalue)
  {
    fieldE01TER.setString(newvalue);
  }

  /**
  * Get value of field E01TER as a String.
  */
  public String getE01TER()
  {
    return fieldE01TER.getString();
  }

  /**
  * Set numeric field E01TER using a BigDecimal value.
  */
  public void setE01TER(BigDecimal newvalue)
  {
    fieldE01TER.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01TER as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01TER()
  {
    return fieldE01TER.getBigDecimal();
  }

  /**
  * Set field E01FG1 using a String value.
  */
  public void setE01FG1(String newvalue)
  {
    fieldE01FG1.setString(newvalue);
  }

  /**
  * Get value of field E01FG1 as a String.
  */
  public String getE01FG1()
  {
    return fieldE01FG1.getString();
  }

  /**
  * Set field E01FG2 using a String value.
  */
  public void setE01FG2(String newvalue)
  {
    fieldE01FG2.setString(newvalue);
  }

  /**
  * Get value of field E01FG2 as a String.
  */
  public String getE01FG2()
  {
    return fieldE01FG2.getString();
  }

  /**
  * Set field E01AM1 using a String value.
  */
  public void setE01AM1(String newvalue)
  {
    fieldE01AM1.setString(newvalue);
  }

  /**
  * Get value of field E01AM1 as a String.
  */
  public String getE01AM1()
  {
    return fieldE01AM1.getString();
  }

  /**
  * Set numeric field E01AM1 using a BigDecimal value.
  */
  public void setE01AM1(BigDecimal newvalue)
  {
    fieldE01AM1.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01AM1 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01AM1()
  {
    return fieldE01AM1.getBigDecimal();
  }

  /**
  * Set field E01DD1 using a String value.
  */
  public void setE01DD1(String newvalue)
  {
    fieldE01DD1.setString(newvalue);
  }

  /**
  * Get value of field E01DD1 as a String.
  */
  public String getE01DD1()
  {
    return fieldE01DD1.getString();
  }

  /**
  * Set numeric field E01DD1 using a BigDecimal value.
  */
  public void setE01DD1(BigDecimal newvalue)
  {
    fieldE01DD1.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DD1 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DD1()
  {
    return fieldE01DD1.getBigDecimal();
  }

  /**
  * Set field E01DD2 using a String value.
  */
  public void setE01DD2(String newvalue)
  {
    fieldE01DD2.setString(newvalue);
  }

  /**
  * Get value of field E01DD2 as a String.
  */
  public String getE01DD2()
  {
    return fieldE01DD2.getString();
  }

  /**
  * Set numeric field E01DD2 using a BigDecimal value.
  */
  public void setE01DD2(BigDecimal newvalue)
  {
    fieldE01DD2.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DD2 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DD2()
  {
    return fieldE01DD2.getBigDecimal();
  }

  /**
  * Set field E01DD3 using a String value.
  */
  public void setE01DD3(String newvalue)
  {
    fieldE01DD3.setString(newvalue);
  }

  /**
  * Get value of field E01DD3 as a String.
  */
  public String getE01DD3()
  {
    return fieldE01DD3.getString();
  }

  /**
  * Set numeric field E01DD3 using a BigDecimal value.
  */
  public void setE01DD3(BigDecimal newvalue)
  {
    fieldE01DD3.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01DD3 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01DD3()
  {
    return fieldE01DD3.getBigDecimal();
  }

  /**
  * Set field E01D11 using a String value.
  */
  public void setE01D11(String newvalue)
  {
    fieldE01D11.setString(newvalue);
  }

  /**
  * Get value of field E01D11 as a String.
  */
  public String getE01D11()
  {
    return fieldE01D11.getString();
  }

  /**
  * Set numeric field E01D11 using a BigDecimal value.
  */
  public void setE01D11(BigDecimal newvalue)
  {
    fieldE01D11.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01D11 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01D11()
  {
    return fieldE01D11.getBigDecimal();
  }

  /**
  * Set field E01D12 using a String value.
  */
  public void setE01D12(String newvalue)
  {
    fieldE01D12.setString(newvalue);
  }

  /**
  * Get value of field E01D12 as a String.
  */
  public String getE01D12()
  {
    return fieldE01D12.getString();
  }

  /**
  * Set numeric field E01D12 using a BigDecimal value.
  */
  public void setE01D12(BigDecimal newvalue)
  {
    fieldE01D12.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01D12 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01D12()
  {
    return fieldE01D12.getBigDecimal();
  }

  /**
  * Set field E01D13 using a String value.
  */
  public void setE01D13(String newvalue)
  {
    fieldE01D13.setString(newvalue);
  }

  /**
  * Get value of field E01D13 as a String.
  */
  public String getE01D13()
  {
    return fieldE01D13.getString();
  }

  /**
  * Set numeric field E01D13 using a BigDecimal value.
  */
  public void setE01D13(BigDecimal newvalue)
  {
    fieldE01D13.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01D13 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01D13()
  {
    return fieldE01D13.getBigDecimal();
  }

  /**
  * Set field E01F01 using a String value.
  */
  public void setE01F01(String newvalue)
  {
    fieldE01F01.setString(newvalue);
  }

  /**
  * Get value of field E01F01 as a String.
  */
  public String getE01F01()
  {
    return fieldE01F01.getString();
  }

  /**
  * Set field E01PHO1 using a String value.
  */
  public void setE01PHO1(String newvalue)
  {
    fieldE01PHO1.setString(newvalue);
  }

  /**
  * Get value of field E01PHO1 as a String.
  */
  public String getE01PHO1()
  {
    return fieldE01PHO1.getString();
  }

  /**
  * Set numeric field E01PHO1 using a BigDecimal value.
  */
  public void setE01PHO1(BigDecimal newvalue)
  {
    fieldE01PHO1.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01PHO1 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01PHO1()
  {
    return fieldE01PHO1.getBigDecimal();
  }

  /**
  * Set field E01PHO2 using a String value.
  */
  public void setE01PHO2(String newvalue)
  {
    fieldE01PHO2.setString(newvalue);
  }

  /**
  * Get value of field E01PHO2 as a String.
  */
  public String getE01PHO2()
  {
    return fieldE01PHO2.getString();
  }

  /**
  * Set numeric field E01PHO2 using a BigDecimal value.
  */
  public void setE01PHO2(BigDecimal newvalue)
  {
    fieldE01PHO2.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01PHO2 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01PHO2()
  {
    return fieldE01PHO2.getBigDecimal();
  }

  /**
  * Set field E01PHO3 using a String value.
  */
  public void setE01PHO3(String newvalue)
  {
    fieldE01PHO3.setString(newvalue);
  }

  /**
  * Get value of field E01PHO3 as a String.
  */
  public String getE01PHO3()
  {
    return fieldE01PHO3.getString();
  }

  /**
  * Set numeric field E01PHO3 using a BigDecimal value.
  */
  public void setE01PHO3(BigDecimal newvalue)
  {
    fieldE01PHO3.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01PHO3 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01PHO3()
  {
    return fieldE01PHO3.getBigDecimal();
  }

  /**
  * Set field D01STE using a String value.
  */
  public void setD01STE(String newvalue)
  {
    fieldD01STE.setString(newvalue);
  }

  /**
  * Get value of field D01STE as a String.
  */
  public String getD01STE()
  {
    return fieldD01STE.getString();
  }

  /**
  * Set field F01NA2 using a String value.
  */
  public void setF01NA2(String newvalue)
  {
    fieldF01NA2.setString(newvalue);
  }

  /**
  * Get value of field F01NA2 as a String.
  */
  public String getF01NA2()
  {
    return fieldF01NA2.getString();
  }

  /**
  * Set field F01NA3 using a String value.
  */
  public void setF01NA3(String newvalue)
  {
    fieldF01NA3.setString(newvalue);
  }

  /**
  * Get value of field F01NA3 as a String.
  */
  public String getF01NA3()
  {
    return fieldF01NA3.getString();
  }

  /**
  * Set field F01NA4 using a String value.
  */
  public void setF01NA4(String newvalue)
  {
    fieldF01NA4.setString(newvalue);
  }

  /**
  * Get value of field F01NA4 as a String.
  */
  public String getF01NA4()
  {
    return fieldF01NA4.getString();
  }

  /**
  * Set field F01MLC using a String value.
  */
  public void setF01MLC(String newvalue)
  {
    fieldF01MLC.setString(newvalue);
  }

  /**
  * Get value of field F01MLC as a String.
  */
  public String getF01MLC()
  {
    return fieldF01MLC.getString();
  }

  /**
  * Set field F01STE using a String value.
  */
  public void setF01STE(String newvalue)
  {
    fieldF01STE.setString(newvalue);
  }

  /**
  * Get value of field F01STE as a String.
  */
  public String getF01STE()
  {
    return fieldF01STE.getString();
  }

  /**
  * Set field F01CTR using a String value.
  */
  public void setF01CTR(String newvalue)
  {
    fieldF01CTR.setString(newvalue);
  }

  /**
  * Get value of field F01CTR as a String.
  */
  public String getF01CTR()
  {
    return fieldF01CTR.getString();
  }

  /**
  * Set field F01POB using a String value.
  */
  public void setF01POB(String newvalue)
  {
    fieldF01POB.setString(newvalue);
  }

  /**
  * Get value of field F01POB as a String.
  */
  public String getF01POB()
  {
    return fieldF01POB.getString();
  }

  /**
  * Set field F01ZPC using a String value.
  */
  public void setF01ZPC(String newvalue)
  {
    fieldF01ZPC.setString(newvalue);
  }

  /**
  * Get value of field F01ZPC as a String.
  */
  public String getF01ZPC()
  {
    return fieldF01ZPC.getString();
  }

  /**
  * Set field F01IAD using a String value.
  */
  public void setF01IAD(String newvalue)
  {
    fieldF01IAD.setString(newvalue);
  }

  /**
  * Get value of field F01IAD as a String.
  */
  public String getF01IAD()
  {
    return fieldF01IAD.getString();
  }

  /**
  * Set field F01IDN using a String value.
  */
  public void setF01IDN(String newvalue)
  {
    fieldF01IDN.setString(newvalue);
  }

  /**
  * Get value of field F01IDN as a String.
  */
  public String getF01IDN()
  {
    return fieldF01IDN.getString();
  }

  /**
  * Set field F01TID using a String value.
  */
  public void setF01TID(String newvalue)
  {
    fieldF01TID.setString(newvalue);
  }

  /**
  * Get value of field F01TID as a String.
  */
  public String getF01TID()
  {
    return fieldF01TID.getString();
  }

  /**
  * Set field F01PID using a String value.
  */
  public void setF01PID(String newvalue)
  {
    fieldF01PID.setString(newvalue);
  }

  /**
  * Get value of field F01PID as a String.
  */
  public String getF01PID()
  {
    return fieldF01PID.getString();
  }

  /**
  * Set field F01IDF using a String value.
  */
  public void setF01IDF(String newvalue)
  {
    fieldF01IDF.setString(newvalue);
  }

  /**
  * Get value of field F01IDF as a String.
  */
  public String getF01IDF()
  {
    return fieldF01IDF.getString();
  }

  /**
  * Set field F01TIF using a String value.
  */
  public void setF01TIF(String newvalue)
  {
    fieldF01TIF.setString(newvalue);
  }

  /**
  * Get value of field F01TIF as a String.
  */
  public String getF01TIF()
  {
    return fieldF01TIF.getString();
  }

  /**
  * Set field F01PIF using a String value.
  */
  public void setF01PIF(String newvalue)
  {
    fieldF01PIF.setString(newvalue);
  }

  /**
  * Get value of field F01PIF as a String.
  */
  public String getF01PIF()
  {
    return fieldF01PIF.getString();
  }

  /**
  * Set field F01ID3 using a String value.
  */
  public void setF01ID3(String newvalue)
  {
    fieldF01ID3.setString(newvalue);
  }

  /**
  * Get value of field F01ID3 as a String.
  */
  public String getF01ID3()
  {
    return fieldF01ID3.getString();
  }

  /**
  * Set field F01TI3 using a String value.
  */
  public void setF01TI3(String newvalue)
  {
    fieldF01TI3.setString(newvalue);
  }

  /**
  * Get value of field F01TI3 as a String.
  */
  public String getF01TI3()
  {
    return fieldF01TI3.getString();
  }

  /**
  * Set field F01PI3 using a String value.
  */
  public void setF01PI3(String newvalue)
  {
    fieldF01PI3.setString(newvalue);
  }

  /**
  * Get value of field F01PI3 as a String.
  */
  public String getF01PI3()
  {
    return fieldF01PI3.getString();
  }

  /**
  * Set field F01ID4 using a String value.
  */
  public void setF01ID4(String newvalue)
  {
    fieldF01ID4.setString(newvalue);
  }

  /**
  * Get value of field F01ID4 as a String.
  */
  public String getF01ID4()
  {
    return fieldF01ID4.getString();
  }

  /**
  * Set field F01TI4 using a String value.
  */
  public void setF01TI4(String newvalue)
  {
    fieldF01TI4.setString(newvalue);
  }

  /**
  * Get value of field F01TI4 as a String.
  */
  public String getF01TI4()
  {
    return fieldF01TI4.getString();
  }

  /**
  * Set field F01PI4 using a String value.
  */
  public void setF01PI4(String newvalue)
  {
    fieldF01PI4.setString(newvalue);
  }

  /**
  * Get value of field F01PI4 as a String.
  */
  public String getF01PI4()
  {
    return fieldF01PI4.getString();
  }

  /**
  * Set field E01NUMREC using a String value.
  */
  public void setE01NUMREC(String newvalue)
  {
    fieldE01NUMREC.setString(newvalue);
  }

  /**
  * Get value of field E01NUMREC as a String.
  */
  public String getE01NUMREC()
  {
    return fieldE01NUMREC.getString();
  }

  /**
  * Set numeric field E01NUMREC using a BigDecimal value.
  */
  public void setE01NUMREC(BigDecimal newvalue)
  {
    fieldE01NUMREC.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01NUMREC as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01NUMREC()
  {
    return fieldE01NUMREC.getBigDecimal();
  }

  /**
  * Set field E01INDOPE using a String value.
  */
  public void setE01INDOPE(String newvalue)
  {
    fieldE01INDOPE.setString(newvalue);
  }

  /**
  * Get value of field E01INDOPE as a String.
  */
  public String getE01INDOPE()
  {
    return fieldE01INDOPE.getString();
  }

}
