package datapro.eibs.beans;

import datapro.eibs.sockets.*;
import java.io.*;
import java.math.*;

import java.util.*;

/**
* Class generated by AS/400 CRTCLASS command from ESG010505 physical file definition.
* 
* File level identifier is 1151125123751.
* Record format level identifier is 4DB3F2F85A003.
*/

public class ESG010505Message extends MessageRecord
{
  final static String fldnames[] = {
                                     "H05SRERSP",
                                     "H05SREOCC",
                                     "E05CODI01",
                                     "E05CUEN01",
                                     "E05FPRE01",
                                     "E05FSIN01",
                                     "E05RDEN01",
                                     "E05NDEN01",
                                     "E05CODI02",
                                     "E05CUEN02",
                                     "E05FPRE02",
                                     "E05FSIN02",
                                     "E05RDEN02",
                                     "E05NDEN02",
                                     "E05CODI03",
                                     "E05CUEN03",
                                     "E05FPRE03",
                                     "E05FSIN03",
                                     "E05RDEN03",
                                     "E05NDEN03",
                                     "E05CODI04",
                                     "E05CUEN04",
                                     "E05FPRE04",
                                     "E05FSIN04",
                                     "E05RDEN04",
                                     "E05NDEN04",
                                     "E05CODI05",
                                     "E05CUEN05",
                                     "E05FPRE05",
                                     "E05FSIN05",
                                     "E05RDEN05",
                                     "E05NDEN05",
                                     "E05CODI06",
                                     "E05CUEN06",
                                     "E05FPRE06",
                                     "E05FSIN06",
                                     "E05RDEN06",
                                     "E05NDEN06",
                                     "E05CODI07",
                                     "E05CUEN07",
                                     "E05FPRE07",
                                     "E05FSIN07",
                                     "E05RDEN07",
                                     "E05NDEN07",
                                     "E05CODI08",
                                     "E05CUEN08",
                                     "E05FPRE08",
                                     "E05FSIN08",
                                     "E05RDEN08",
                                     "E05NDEN08",
                                     "E05CODI09",
                                     "E05CUEN09",
                                     "E05FPRE09",
                                     "E05FSIN09",
                                     "E05RDEN09",
                                     "E05NDEN09",
                                     "E05CODI10",
                                     "E05CUEN10",
                                     "E05FPRE10",
                                     "E05FSIN10",
                                     "E05RDEN10",
                                     "E05NDEN10",
                                     "E05CODI11",
                                     "E05CUEN11",
                                     "E05FPRE11",
                                     "E05FSIN11",
                                     "E05RDEN11",
                                     "E05NDEN11",
                                     "E05CODI12",
                                     "E05CUEN12",
                                     "E05FPRE12",
                                     "E05FSIN12",
                                     "E05RDEN12",
                                     "E05NDEN12",
                                     "E05CODI13",
                                     "E05CUEN13",
                                     "E05FPRE13",
                                     "E05FSIN13",
                                     "E05RDEN13",
                                     "E05NDEN13",
                                     "E05CODI14",
                                     "E05CUEN14",
                                     "E05FPRE14",
                                     "E05FSIN14",
                                     "E05RDEN14",
                                     "E05NDEN14",
                                     "E05CODI15",
                                     "E05CUEN15",
                                     "E05FPRE15",
                                     "E05FSIN15",
                                     "E05RDEN15",
                                     "E05NDEN15",
                                     "E05CODI16",
                                     "E05CUEN16",
                                     "E05FPRE16",
                                     "E05FSIN16",
                                     "E05RDEN16",
                                     "E05NDEN16",
                                     "E05CODI17",
                                     "E05CUEN17",
                                     "E05FPRE17",
                                     "E05FSIN17",
                                     "E05RDEN17",
                                     "E05NDEN17",
                                     "E05CODI18",
                                     "E05CUEN18",
                                     "E05FPRE18",
                                     "E05FSIN18",
                                     "E05RDEN18",
                                     "E05NDEN18",
                                     "E05CODI19",
                                     "E05CUEN19",
                                     "E05FPRE19",
                                     "E05FSIN19",
                                     "E05RDEN19",
                                     "E05NDEN19",
                                     "E05CODI20",
                                     "E05CUEN20",
                                     "E05FPRE20",
                                     "E05FSIN20",
                                     "E05RDEN20",
                                     "E05NDEN20"
                                   };
  final static String tnames[] = {
                                   "H05SRERSP",
                                   "H05SREOCC",
                                   "E05CODI01",
                                   "E05CUEN01",
                                   "E05FPRE01",
                                   "E05FSIN01",
                                   "E05RDEN01",
                                   "E05NDEN01",
                                   "E05CODI02",
                                   "E05CUEN02",
                                   "E05FPRE02",
                                   "E05FSIN02",
                                   "E05RDEN02",
                                   "E05NDEN02",
                                   "E05CODI03",
                                   "E05CUEN03",
                                   "E05FPRE03",
                                   "E05FSIN03",
                                   "E05RDEN03",
                                   "E05NDEN03",
                                   "E05CODI04",
                                   "E05CUEN04",
                                   "E05FPRE04",
                                   "E05FSIN04",
                                   "E05RDEN04",
                                   "E05NDEN04",
                                   "E05CODI05",
                                   "E05CUEN05",
                                   "E05FPRE05",
                                   "E05FSIN05",
                                   "E05RDEN05",
                                   "E05NDEN05",
                                   "E05CODI06",
                                   "E05CUEN06",
                                   "E05FPRE06",
                                   "E05FSIN06",
                                   "E05RDEN06",
                                   "E05NDEN06",
                                   "E05CODI07",
                                   "E05CUEN07",
                                   "E05FPRE07",
                                   "E05FSIN07",
                                   "E05RDEN07",
                                   "E05NDEN07",
                                   "E05CODI08",
                                   "E05CUEN08",
                                   "E05FPRE08",
                                   "E05FSIN08",
                                   "E05RDEN08",
                                   "E05NDEN08",
                                   "E05CODI09",
                                   "E05CUEN09",
                                   "E05FPRE09",
                                   "E05FSIN09",
                                   "E05RDEN09",
                                   "E05NDEN09",
                                   "E05CODI10",
                                   "E05CUEN10",
                                   "E05FPRE10",
                                   "E05FSIN10",
                                   "E05RDEN10",
                                   "E05NDEN10",
                                   "E05CODI11",
                                   "E05CUEN11",
                                   "E05FPRE11",
                                   "E05FSIN11",
                                   "E05RDEN11",
                                   "E05NDEN11",
                                   "E05CODI12",
                                   "E05CUEN12",
                                   "E05FPRE12",
                                   "E05FSIN12",
                                   "E05RDEN12",
                                   "E05NDEN12",
                                   "E05CODI13",
                                   "E05CUEN13",
                                   "E05FPRE13",
                                   "E05FSIN13",
                                   "E05RDEN13",
                                   "E05NDEN13",
                                   "E05CODI14",
                                   "E05CUEN14",
                                   "E05FPRE14",
                                   "E05FSIN14",
                                   "E05RDEN14",
                                   "E05NDEN14",
                                   "E05CODI15",
                                   "E05CUEN15",
                                   "E05FPRE15",
                                   "E05FSIN15",
                                   "E05RDEN15",
                                   "E05NDEN15",
                                   "E05CODI16",
                                   "E05CUEN16",
                                   "E05FPRE16",
                                   "E05FSIN16",
                                   "E05RDEN16",
                                   "E05NDEN16",
                                   "E05CODI17",
                                   "E05CUEN17",
                                   "E05FPRE17",
                                   "E05FSIN17",
                                   "E05RDEN17",
                                   "E05NDEN17",
                                   "E05CODI18",
                                   "E05CUEN18",
                                   "E05FPRE18",
                                   "E05FSIN18",
                                   "E05RDEN18",
                                   "E05NDEN18",
                                   "E05CODI19",
                                   "E05CUEN19",
                                   "E05FPRE19",
                                   "E05FSIN19",
                                   "E05RDEN19",
                                   "E05NDEN19",
                                   "E05CODI20",
                                   "E05CUEN20",
                                   "E05FPRE20",
                                   "E05FSIN20",
                                   "E05RDEN20",
                                   "E05NDEN20"
                                 };
  final static String fid = "1151125123751";
  final static String rid = "4DB3F2F85A003";
  final static String fmtname = "ESG010505";
  final int FIELDCOUNT = 122;
  private static Hashtable tlookup = new Hashtable();
  private DecimalField fieldH05SRERSP = null;
  private DecimalField fieldH05SREOCC = null;
  private CharacterField fieldE05CODI01 = null;
  private DecimalField fieldE05CUEN01 = null;
  private CharacterField fieldE05FPRE01 = null;
  private CharacterField fieldE05FSIN01 = null;
  private CharacterField fieldE05RDEN01 = null;
  private CharacterField fieldE05NDEN01 = null;
  private CharacterField fieldE05CODI02 = null;
  private DecimalField fieldE05CUEN02 = null;
  private CharacterField fieldE05FPRE02 = null;
  private CharacterField fieldE05FSIN02 = null;
  private CharacterField fieldE05RDEN02 = null;
  private CharacterField fieldE05NDEN02 = null;
  private CharacterField fieldE05CODI03 = null;
  private DecimalField fieldE05CUEN03 = null;
  private CharacterField fieldE05FPRE03 = null;
  private CharacterField fieldE05FSIN03 = null;
  private CharacterField fieldE05RDEN03 = null;
  private CharacterField fieldE05NDEN03 = null;
  private CharacterField fieldE05CODI04 = null;
  private DecimalField fieldE05CUEN04 = null;
  private CharacterField fieldE05FPRE04 = null;
  private CharacterField fieldE05FSIN04 = null;
  private CharacterField fieldE05RDEN04 = null;
  private CharacterField fieldE05NDEN04 = null;
  private CharacterField fieldE05CODI05 = null;
  private DecimalField fieldE05CUEN05 = null;
  private CharacterField fieldE05FPRE05 = null;
  private CharacterField fieldE05FSIN05 = null;
  private CharacterField fieldE05RDEN05 = null;
  private CharacterField fieldE05NDEN05 = null;
  private CharacterField fieldE05CODI06 = null;
  private DecimalField fieldE05CUEN06 = null;
  private CharacterField fieldE05FPRE06 = null;
  private CharacterField fieldE05FSIN06 = null;
  private CharacterField fieldE05RDEN06 = null;
  private CharacterField fieldE05NDEN06 = null;
  private CharacterField fieldE05CODI07 = null;
  private DecimalField fieldE05CUEN07 = null;
  private CharacterField fieldE05FPRE07 = null;
  private CharacterField fieldE05FSIN07 = null;
  private CharacterField fieldE05RDEN07 = null;
  private CharacterField fieldE05NDEN07 = null;
  private CharacterField fieldE05CODI08 = null;
  private DecimalField fieldE05CUEN08 = null;
  private CharacterField fieldE05FPRE08 = null;
  private CharacterField fieldE05FSIN08 = null;
  private CharacterField fieldE05RDEN08 = null;
  private CharacterField fieldE05NDEN08 = null;
  private CharacterField fieldE05CODI09 = null;
  private DecimalField fieldE05CUEN09 = null;
  private CharacterField fieldE05FPRE09 = null;
  private CharacterField fieldE05FSIN09 = null;
  private CharacterField fieldE05RDEN09 = null;
  private CharacterField fieldE05NDEN09 = null;
  private CharacterField fieldE05CODI10 = null;
  private DecimalField fieldE05CUEN10 = null;
  private CharacterField fieldE05FPRE10 = null;
  private CharacterField fieldE05FSIN10 = null;
  private CharacterField fieldE05RDEN10 = null;
  private CharacterField fieldE05NDEN10 = null;
  private CharacterField fieldE05CODI11 = null;
  private DecimalField fieldE05CUEN11 = null;
  private CharacterField fieldE05FPRE11 = null;
  private CharacterField fieldE05FSIN11 = null;
  private CharacterField fieldE05RDEN11 = null;
  private CharacterField fieldE05NDEN11 = null;
  private CharacterField fieldE05CODI12 = null;
  private DecimalField fieldE05CUEN12 = null;
  private CharacterField fieldE05FPRE12 = null;
  private CharacterField fieldE05FSIN12 = null;
  private CharacterField fieldE05RDEN12 = null;
  private CharacterField fieldE05NDEN12 = null;
  private CharacterField fieldE05CODI13 = null;
  private DecimalField fieldE05CUEN13 = null;
  private CharacterField fieldE05FPRE13 = null;
  private CharacterField fieldE05FSIN13 = null;
  private CharacterField fieldE05RDEN13 = null;
  private CharacterField fieldE05NDEN13 = null;
  private CharacterField fieldE05CODI14 = null;
  private DecimalField fieldE05CUEN14 = null;
  private CharacterField fieldE05FPRE14 = null;
  private CharacterField fieldE05FSIN14 = null;
  private CharacterField fieldE05RDEN14 = null;
  private CharacterField fieldE05NDEN14 = null;
  private CharacterField fieldE05CODI15 = null;
  private DecimalField fieldE05CUEN15 = null;
  private CharacterField fieldE05FPRE15 = null;
  private CharacterField fieldE05FSIN15 = null;
  private CharacterField fieldE05RDEN15 = null;
  private CharacterField fieldE05NDEN15 = null;
  private CharacterField fieldE05CODI16 = null;
  private DecimalField fieldE05CUEN16 = null;
  private CharacterField fieldE05FPRE16 = null;
  private CharacterField fieldE05FSIN16 = null;
  private CharacterField fieldE05RDEN16 = null;
  private CharacterField fieldE05NDEN16 = null;
  private CharacterField fieldE05CODI17 = null;
  private DecimalField fieldE05CUEN17 = null;
  private CharacterField fieldE05FPRE17 = null;
  private CharacterField fieldE05FSIN17 = null;
  private CharacterField fieldE05RDEN17 = null;
  private CharacterField fieldE05NDEN17 = null;
  private CharacterField fieldE05CODI18 = null;
  private DecimalField fieldE05CUEN18 = null;
  private CharacterField fieldE05FPRE18 = null;
  private CharacterField fieldE05FSIN18 = null;
  private CharacterField fieldE05RDEN18 = null;
  private CharacterField fieldE05NDEN18 = null;
  private CharacterField fieldE05CODI19 = null;
  private DecimalField fieldE05CUEN19 = null;
  private CharacterField fieldE05FPRE19 = null;
  private CharacterField fieldE05FSIN19 = null;
  private CharacterField fieldE05RDEN19 = null;
  private CharacterField fieldE05NDEN19 = null;
  private CharacterField fieldE05CODI20 = null;
  private DecimalField fieldE05CUEN20 = null;
  private CharacterField fieldE05FPRE20 = null;
  private CharacterField fieldE05FSIN20 = null;
  private CharacterField fieldE05RDEN20 = null;
  private CharacterField fieldE05NDEN20 = null;

  /**
  * Constructor for ESG010505Message.
  */
  public ESG010505Message()
  {
    createFields();
    initialize();
  }

  /**
  * Create fields for this message.
  * This method implements the abstract method in the MessageRecord superclass.
  */
  protected void createFields()
  {
    recordsize = 2587;
    fileid = fid;
    recordid = rid;
    message = new byte[getByteLength()];
    formatname = fmtname;
    fieldnames = fldnames;
    tagnames = tnames;
    fields = new MessageField[FIELDCOUNT];

    fields[0] = fieldH05SRERSP =
    new DecimalField(message, HEADERSIZE + 0, 4, 0, "H05SRERSP");
    fields[1] = fieldH05SREOCC =
    new DecimalField(message, HEADERSIZE + 4, 3, 0, "H05SREOCC");
    fields[2] = fieldE05CODI01 =
    new CharacterField(message, HEADERSIZE + 7, 4, "E05CODI01");
    fields[3] = fieldE05CUEN01 =
    new DecimalField(message, HEADERSIZE + 11, 13, 0, "E05CUEN01");
    fields[4] = fieldE05FPRE01 =
    new CharacterField(message, HEADERSIZE + 24, 26, "E05FPRE01");
    fields[5] = fieldE05FSIN01 =
    new CharacterField(message, HEADERSIZE + 50, 26, "E05FSIN01");
    fields[6] = fieldE05RDEN01 =
    new CharacterField(message, HEADERSIZE + 76, 10, "E05RDEN01");
    fields[7] = fieldE05NDEN01 =
    new CharacterField(message, HEADERSIZE + 86, 50, "E05NDEN01");
    fields[8] = fieldE05CODI02 =
    new CharacterField(message, HEADERSIZE + 136, 4, "E05CODI02");
    fields[9] = fieldE05CUEN02 =
    new DecimalField(message, HEADERSIZE + 140, 13, 0, "E05CUEN02");
    fields[10] = fieldE05FPRE02 =
    new CharacterField(message, HEADERSIZE + 153, 26, "E05FPRE02");
    fields[11] = fieldE05FSIN02 =
    new CharacterField(message, HEADERSIZE + 179, 26, "E05FSIN02");
    fields[12] = fieldE05RDEN02 =
    new CharacterField(message, HEADERSIZE + 205, 10, "E05RDEN02");
    fields[13] = fieldE05NDEN02 =
    new CharacterField(message, HEADERSIZE + 215, 50, "E05NDEN02");
    fields[14] = fieldE05CODI03 =
    new CharacterField(message, HEADERSIZE + 265, 4, "E05CODI03");
    fields[15] = fieldE05CUEN03 =
    new DecimalField(message, HEADERSIZE + 269, 13, 0, "E05CUEN03");
    fields[16] = fieldE05FPRE03 =
    new CharacterField(message, HEADERSIZE + 282, 26, "E05FPRE03");
    fields[17] = fieldE05FSIN03 =
    new CharacterField(message, HEADERSIZE + 308, 26, "E05FSIN03");
    fields[18] = fieldE05RDEN03 =
    new CharacterField(message, HEADERSIZE + 334, 10, "E05RDEN03");
    fields[19] = fieldE05NDEN03 =
    new CharacterField(message, HEADERSIZE + 344, 50, "E05NDEN03");
    fields[20] = fieldE05CODI04 =
    new CharacterField(message, HEADERSIZE + 394, 4, "E05CODI04");
    fields[21] = fieldE05CUEN04 =
    new DecimalField(message, HEADERSIZE + 398, 13, 0, "E05CUEN04");
    fields[22] = fieldE05FPRE04 =
    new CharacterField(message, HEADERSIZE + 411, 26, "E05FPRE04");
    fields[23] = fieldE05FSIN04 =
    new CharacterField(message, HEADERSIZE + 437, 26, "E05FSIN04");
    fields[24] = fieldE05RDEN04 =
    new CharacterField(message, HEADERSIZE + 463, 10, "E05RDEN04");
    fields[25] = fieldE05NDEN04 =
    new CharacterField(message, HEADERSIZE + 473, 50, "E05NDEN04");
    fields[26] = fieldE05CODI05 =
    new CharacterField(message, HEADERSIZE + 523, 4, "E05CODI05");
    fields[27] = fieldE05CUEN05 =
    new DecimalField(message, HEADERSIZE + 527, 13, 0, "E05CUEN05");
    fields[28] = fieldE05FPRE05 =
    new CharacterField(message, HEADERSIZE + 540, 26, "E05FPRE05");
    fields[29] = fieldE05FSIN05 =
    new CharacterField(message, HEADERSIZE + 566, 26, "E05FSIN05");
    fields[30] = fieldE05RDEN05 =
    new CharacterField(message, HEADERSIZE + 592, 10, "E05RDEN05");
    fields[31] = fieldE05NDEN05 =
    new CharacterField(message, HEADERSIZE + 602, 50, "E05NDEN05");
    fields[32] = fieldE05CODI06 =
    new CharacterField(message, HEADERSIZE + 652, 4, "E05CODI06");
    fields[33] = fieldE05CUEN06 =
    new DecimalField(message, HEADERSIZE + 656, 13, 0, "E05CUEN06");
    fields[34] = fieldE05FPRE06 =
    new CharacterField(message, HEADERSIZE + 669, 26, "E05FPRE06");
    fields[35] = fieldE05FSIN06 =
    new CharacterField(message, HEADERSIZE + 695, 26, "E05FSIN06");
    fields[36] = fieldE05RDEN06 =
    new CharacterField(message, HEADERSIZE + 721, 10, "E05RDEN06");
    fields[37] = fieldE05NDEN06 =
    new CharacterField(message, HEADERSIZE + 731, 50, "E05NDEN06");
    fields[38] = fieldE05CODI07 =
    new CharacterField(message, HEADERSIZE + 781, 4, "E05CODI07");
    fields[39] = fieldE05CUEN07 =
    new DecimalField(message, HEADERSIZE + 785, 13, 0, "E05CUEN07");
    fields[40] = fieldE05FPRE07 =
    new CharacterField(message, HEADERSIZE + 798, 26, "E05FPRE07");
    fields[41] = fieldE05FSIN07 =
    new CharacterField(message, HEADERSIZE + 824, 26, "E05FSIN07");
    fields[42] = fieldE05RDEN07 =
    new CharacterField(message, HEADERSIZE + 850, 10, "E05RDEN07");
    fields[43] = fieldE05NDEN07 =
    new CharacterField(message, HEADERSIZE + 860, 50, "E05NDEN07");
    fields[44] = fieldE05CODI08 =
    new CharacterField(message, HEADERSIZE + 910, 4, "E05CODI08");
    fields[45] = fieldE05CUEN08 =
    new DecimalField(message, HEADERSIZE + 914, 13, 0, "E05CUEN08");
    fields[46] = fieldE05FPRE08 =
    new CharacterField(message, HEADERSIZE + 927, 26, "E05FPRE08");
    fields[47] = fieldE05FSIN08 =
    new CharacterField(message, HEADERSIZE + 953, 26, "E05FSIN08");
    fields[48] = fieldE05RDEN08 =
    new CharacterField(message, HEADERSIZE + 979, 10, "E05RDEN08");
    fields[49] = fieldE05NDEN08 =
    new CharacterField(message, HEADERSIZE + 989, 50, "E05NDEN08");
    fields[50] = fieldE05CODI09 =
    new CharacterField(message, HEADERSIZE + 1039, 4, "E05CODI09");
    fields[51] = fieldE05CUEN09 =
    new DecimalField(message, HEADERSIZE + 1043, 13, 0, "E05CUEN09");
    fields[52] = fieldE05FPRE09 =
    new CharacterField(message, HEADERSIZE + 1056, 26, "E05FPRE09");
    fields[53] = fieldE05FSIN09 =
    new CharacterField(message, HEADERSIZE + 1082, 26, "E05FSIN09");
    fields[54] = fieldE05RDEN09 =
    new CharacterField(message, HEADERSIZE + 1108, 10, "E05RDEN09");
    fields[55] = fieldE05NDEN09 =
    new CharacterField(message, HEADERSIZE + 1118, 50, "E05NDEN09");
    fields[56] = fieldE05CODI10 =
    new CharacterField(message, HEADERSIZE + 1168, 4, "E05CODI10");
    fields[57] = fieldE05CUEN10 =
    new DecimalField(message, HEADERSIZE + 1172, 13, 0, "E05CUEN10");
    fields[58] = fieldE05FPRE10 =
    new CharacterField(message, HEADERSIZE + 1185, 26, "E05FPRE10");
    fields[59] = fieldE05FSIN10 =
    new CharacterField(message, HEADERSIZE + 1211, 26, "E05FSIN10");
    fields[60] = fieldE05RDEN10 =
    new CharacterField(message, HEADERSIZE + 1237, 10, "E05RDEN10");
    fields[61] = fieldE05NDEN10 =
    new CharacterField(message, HEADERSIZE + 1247, 50, "E05NDEN10");
    fields[62] = fieldE05CODI11 =
    new CharacterField(message, HEADERSIZE + 1297, 4, "E05CODI11");
    fields[63] = fieldE05CUEN11 =
    new DecimalField(message, HEADERSIZE + 1301, 13, 0, "E05CUEN11");
    fields[64] = fieldE05FPRE11 =
    new CharacterField(message, HEADERSIZE + 1314, 26, "E05FPRE11");
    fields[65] = fieldE05FSIN11 =
    new CharacterField(message, HEADERSIZE + 1340, 26, "E05FSIN11");
    fields[66] = fieldE05RDEN11 =
    new CharacterField(message, HEADERSIZE + 1366, 10, "E05RDEN11");
    fields[67] = fieldE05NDEN11 =
    new CharacterField(message, HEADERSIZE + 1376, 50, "E05NDEN11");
    fields[68] = fieldE05CODI12 =
    new CharacterField(message, HEADERSIZE + 1426, 4, "E05CODI12");
    fields[69] = fieldE05CUEN12 =
    new DecimalField(message, HEADERSIZE + 1430, 13, 0, "E05CUEN12");
    fields[70] = fieldE05FPRE12 =
    new CharacterField(message, HEADERSIZE + 1443, 26, "E05FPRE12");
    fields[71] = fieldE05FSIN12 =
    new CharacterField(message, HEADERSIZE + 1469, 26, "E05FSIN12");
    fields[72] = fieldE05RDEN12 =
    new CharacterField(message, HEADERSIZE + 1495, 10, "E05RDEN12");
    fields[73] = fieldE05NDEN12 =
    new CharacterField(message, HEADERSIZE + 1505, 50, "E05NDEN12");
    fields[74] = fieldE05CODI13 =
    new CharacterField(message, HEADERSIZE + 1555, 4, "E05CODI13");
    fields[75] = fieldE05CUEN13 =
    new DecimalField(message, HEADERSIZE + 1559, 13, 0, "E05CUEN13");
    fields[76] = fieldE05FPRE13 =
    new CharacterField(message, HEADERSIZE + 1572, 26, "E05FPRE13");
    fields[77] = fieldE05FSIN13 =
    new CharacterField(message, HEADERSIZE + 1598, 26, "E05FSIN13");
    fields[78] = fieldE05RDEN13 =
    new CharacterField(message, HEADERSIZE + 1624, 10, "E05RDEN13");
    fields[79] = fieldE05NDEN13 =
    new CharacterField(message, HEADERSIZE + 1634, 50, "E05NDEN13");
    fields[80] = fieldE05CODI14 =
    new CharacterField(message, HEADERSIZE + 1684, 4, "E05CODI14");
    fields[81] = fieldE05CUEN14 =
    new DecimalField(message, HEADERSIZE + 1688, 13, 0, "E05CUEN14");
    fields[82] = fieldE05FPRE14 =
    new CharacterField(message, HEADERSIZE + 1701, 26, "E05FPRE14");
    fields[83] = fieldE05FSIN14 =
    new CharacterField(message, HEADERSIZE + 1727, 26, "E05FSIN14");
    fields[84] = fieldE05RDEN14 =
    new CharacterField(message, HEADERSIZE + 1753, 10, "E05RDEN14");
    fields[85] = fieldE05NDEN14 =
    new CharacterField(message, HEADERSIZE + 1763, 50, "E05NDEN14");
    fields[86] = fieldE05CODI15 =
    new CharacterField(message, HEADERSIZE + 1813, 4, "E05CODI15");
    fields[87] = fieldE05CUEN15 =
    new DecimalField(message, HEADERSIZE + 1817, 13, 0, "E05CUEN15");
    fields[88] = fieldE05FPRE15 =
    new CharacterField(message, HEADERSIZE + 1830, 26, "E05FPRE15");
    fields[89] = fieldE05FSIN15 =
    new CharacterField(message, HEADERSIZE + 1856, 26, "E05FSIN15");
    fields[90] = fieldE05RDEN15 =
    new CharacterField(message, HEADERSIZE + 1882, 10, "E05RDEN15");
    fields[91] = fieldE05NDEN15 =
    new CharacterField(message, HEADERSIZE + 1892, 50, "E05NDEN15");
    fields[92] = fieldE05CODI16 =
    new CharacterField(message, HEADERSIZE + 1942, 4, "E05CODI16");
    fields[93] = fieldE05CUEN16 =
    new DecimalField(message, HEADERSIZE + 1946, 13, 0, "E05CUEN16");
    fields[94] = fieldE05FPRE16 =
    new CharacterField(message, HEADERSIZE + 1959, 26, "E05FPRE16");
    fields[95] = fieldE05FSIN16 =
    new CharacterField(message, HEADERSIZE + 1985, 26, "E05FSIN16");
    fields[96] = fieldE05RDEN16 =
    new CharacterField(message, HEADERSIZE + 2011, 10, "E05RDEN16");
    fields[97] = fieldE05NDEN16 =
    new CharacterField(message, HEADERSIZE + 2021, 50, "E05NDEN16");
    fields[98] = fieldE05CODI17 =
    new CharacterField(message, HEADERSIZE + 2071, 4, "E05CODI17");
    fields[99] = fieldE05CUEN17 =
    new DecimalField(message, HEADERSIZE + 2075, 13, 0, "E05CUEN17");
    fields[100] = fieldE05FPRE17 =
    new CharacterField(message, HEADERSIZE + 2088, 26, "E05FPRE17");
    fields[101] = fieldE05FSIN17 =
    new CharacterField(message, HEADERSIZE + 2114, 26, "E05FSIN17");
    fields[102] = fieldE05RDEN17 =
    new CharacterField(message, HEADERSIZE + 2140, 10, "E05RDEN17");
    fields[103] = fieldE05NDEN17 =
    new CharacterField(message, HEADERSIZE + 2150, 50, "E05NDEN17");
    fields[104] = fieldE05CODI18 =
    new CharacterField(message, HEADERSIZE + 2200, 4, "E05CODI18");
    fields[105] = fieldE05CUEN18 =
    new DecimalField(message, HEADERSIZE + 2204, 13, 0, "E05CUEN18");
    fields[106] = fieldE05FPRE18 =
    new CharacterField(message, HEADERSIZE + 2217, 26, "E05FPRE18");
    fields[107] = fieldE05FSIN18 =
    new CharacterField(message, HEADERSIZE + 2243, 26, "E05FSIN18");
    fields[108] = fieldE05RDEN18 =
    new CharacterField(message, HEADERSIZE + 2269, 10, "E05RDEN18");
    fields[109] = fieldE05NDEN18 =
    new CharacterField(message, HEADERSIZE + 2279, 50, "E05NDEN18");
    fields[110] = fieldE05CODI19 =
    new CharacterField(message, HEADERSIZE + 2329, 4, "E05CODI19");
    fields[111] = fieldE05CUEN19 =
    new DecimalField(message, HEADERSIZE + 2333, 13, 0, "E05CUEN19");
    fields[112] = fieldE05FPRE19 =
    new CharacterField(message, HEADERSIZE + 2346, 26, "E05FPRE19");
    fields[113] = fieldE05FSIN19 =
    new CharacterField(message, HEADERSIZE + 2372, 26, "E05FSIN19");
    fields[114] = fieldE05RDEN19 =
    new CharacterField(message, HEADERSIZE + 2398, 10, "E05RDEN19");
    fields[115] = fieldE05NDEN19 =
    new CharacterField(message, HEADERSIZE + 2408, 50, "E05NDEN19");
    fields[116] = fieldE05CODI20 =
    new CharacterField(message, HEADERSIZE + 2458, 4, "E05CODI20");
    fields[117] = fieldE05CUEN20 =
    new DecimalField(message, HEADERSIZE + 2462, 13, 0, "E05CUEN20");
    fields[118] = fieldE05FPRE20 =
    new CharacterField(message, HEADERSIZE + 2475, 26, "E05FPRE20");
    fields[119] = fieldE05FSIN20 =
    new CharacterField(message, HEADERSIZE + 2501, 26, "E05FSIN20");
    fields[120] = fieldE05RDEN20 =
    new CharacterField(message, HEADERSIZE + 2527, 10, "E05RDEN20");
    fields[121] = fieldE05NDEN20 =
    new CharacterField(message, HEADERSIZE + 2537, 50, "E05NDEN20");

    synchronized (tlookup)
    {
      if (tlookup.isEmpty())
      {
        for (int i = 0; i < tnames.length; i++)
          tlookup.put(tnames[i], new Integer(i));
      }
    }

    taglookup = tlookup;
  }

  /**
  * Set field H05SRERSP using a String value.
  */
  public void setH05SRERSP(String newvalue)
  {
    fieldH05SRERSP.setString(newvalue);
  }

  /**
  * Get value of field H05SRERSP as a String.
  */
  public String getH05SRERSP()
  {
    return fieldH05SRERSP.getString();
  }

  /**
  * Set numeric field H05SRERSP using a BigDecimal value.
  */
  public void setH05SRERSP(BigDecimal newvalue)
  {
    fieldH05SRERSP.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field H05SRERSP as a BigDecimal.
  */
  public BigDecimal getBigDecimalH05SRERSP()
  {
    return fieldH05SRERSP.getBigDecimal();
  }

  /**
  * Set field H05SREOCC using a String value.
  */
  public void setH05SREOCC(String newvalue)
  {
    fieldH05SREOCC.setString(newvalue);
  }

  /**
  * Get value of field H05SREOCC as a String.
  */
  public String getH05SREOCC()
  {
    return fieldH05SREOCC.getString();
  }

  /**
  * Set numeric field H05SREOCC using a BigDecimal value.
  */
  public void setH05SREOCC(BigDecimal newvalue)
  {
    fieldH05SREOCC.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field H05SREOCC as a BigDecimal.
  */
  public BigDecimal getBigDecimalH05SREOCC()
  {
    return fieldH05SREOCC.getBigDecimal();
  }

  /**
  * Set field E05CODI01 using a String value.
  */
  public void setE05CODI01(String newvalue)
  {
    fieldE05CODI01.setString(newvalue);
  }

  /**
  * Get value of field E05CODI01 as a String.
  */
  public String getE05CODI01()
  {
    return fieldE05CODI01.getString();
  }

  /**
  * Set field E05CUEN01 using a String value.
  */
  public void setE05CUEN01(String newvalue)
  {
    fieldE05CUEN01.setString(newvalue);
  }

  /**
  * Get value of field E05CUEN01 as a String.
  */
  public String getE05CUEN01()
  {
    return fieldE05CUEN01.getString();
  }

  /**
  * Set numeric field E05CUEN01 using a BigDecimal value.
  */
  public void setE05CUEN01(BigDecimal newvalue)
  {
    fieldE05CUEN01.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05CUEN01 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05CUEN01()
  {
    return fieldE05CUEN01.getBigDecimal();
  }

  /**
  * Set field E05FPRE01 using a String value.
  */
  public void setE05FPRE01(String newvalue)
  {
    fieldE05FPRE01.setString(newvalue);
  }

  /**
  * Get value of field E05FPRE01 as a String.
  */
  public String getE05FPRE01()
  {
    return fieldE05FPRE01.getString();
  }

  /**
  * Set field E05FSIN01 using a String value.
  */
  public void setE05FSIN01(String newvalue)
  {
    fieldE05FSIN01.setString(newvalue);
  }

  /**
  * Get value of field E05FSIN01 as a String.
  */
  public String getE05FSIN01()
  {
    return fieldE05FSIN01.getString();
  }

  /**
  * Set field E05RDEN01 using a String value.
  */
  public void setE05RDEN01(String newvalue)
  {
    fieldE05RDEN01.setString(newvalue);
  }

  /**
  * Get value of field E05RDEN01 as a String.
  */
  public String getE05RDEN01()
  {
    return fieldE05RDEN01.getString();
  }

  /**
  * Set field E05NDEN01 using a String value.
  */
  public void setE05NDEN01(String newvalue)
  {
    fieldE05NDEN01.setString(newvalue);
  }

  /**
  * Get value of field E05NDEN01 as a String.
  */
  public String getE05NDEN01()
  {
    return fieldE05NDEN01.getString();
  }

  /**
  * Set field E05CODI02 using a String value.
  */
  public void setE05CODI02(String newvalue)
  {
    fieldE05CODI02.setString(newvalue);
  }

  /**
  * Get value of field E05CODI02 as a String.
  */
  public String getE05CODI02()
  {
    return fieldE05CODI02.getString();
  }

  /**
  * Set field E05CUEN02 using a String value.
  */
  public void setE05CUEN02(String newvalue)
  {
    fieldE05CUEN02.setString(newvalue);
  }

  /**
  * Get value of field E05CUEN02 as a String.
  */
  public String getE05CUEN02()
  {
    return fieldE05CUEN02.getString();
  }

  /**
  * Set numeric field E05CUEN02 using a BigDecimal value.
  */
  public void setE05CUEN02(BigDecimal newvalue)
  {
    fieldE05CUEN02.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05CUEN02 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05CUEN02()
  {
    return fieldE05CUEN02.getBigDecimal();
  }

  /**
  * Set field E05FPRE02 using a String value.
  */
  public void setE05FPRE02(String newvalue)
  {
    fieldE05FPRE02.setString(newvalue);
  }

  /**
  * Get value of field E05FPRE02 as a String.
  */
  public String getE05FPRE02()
  {
    return fieldE05FPRE02.getString();
  }

  /**
  * Set field E05FSIN02 using a String value.
  */
  public void setE05FSIN02(String newvalue)
  {
    fieldE05FSIN02.setString(newvalue);
  }

  /**
  * Get value of field E05FSIN02 as a String.
  */
  public String getE05FSIN02()
  {
    return fieldE05FSIN02.getString();
  }

  /**
  * Set field E05RDEN02 using a String value.
  */
  public void setE05RDEN02(String newvalue)
  {
    fieldE05RDEN02.setString(newvalue);
  }

  /**
  * Get value of field E05RDEN02 as a String.
  */
  public String getE05RDEN02()
  {
    return fieldE05RDEN02.getString();
  }

  /**
  * Set field E05NDEN02 using a String value.
  */
  public void setE05NDEN02(String newvalue)
  {
    fieldE05NDEN02.setString(newvalue);
  }

  /**
  * Get value of field E05NDEN02 as a String.
  */
  public String getE05NDEN02()
  {
    return fieldE05NDEN02.getString();
  }

  /**
  * Set field E05CODI03 using a String value.
  */
  public void setE05CODI03(String newvalue)
  {
    fieldE05CODI03.setString(newvalue);
  }

  /**
  * Get value of field E05CODI03 as a String.
  */
  public String getE05CODI03()
  {
    return fieldE05CODI03.getString();
  }

  /**
  * Set field E05CUEN03 using a String value.
  */
  public void setE05CUEN03(String newvalue)
  {
    fieldE05CUEN03.setString(newvalue);
  }

  /**
  * Get value of field E05CUEN03 as a String.
  */
  public String getE05CUEN03()
  {
    return fieldE05CUEN03.getString();
  }

  /**
  * Set numeric field E05CUEN03 using a BigDecimal value.
  */
  public void setE05CUEN03(BigDecimal newvalue)
  {
    fieldE05CUEN03.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05CUEN03 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05CUEN03()
  {
    return fieldE05CUEN03.getBigDecimal();
  }

  /**
  * Set field E05FPRE03 using a String value.
  */
  public void setE05FPRE03(String newvalue)
  {
    fieldE05FPRE03.setString(newvalue);
  }

  /**
  * Get value of field E05FPRE03 as a String.
  */
  public String getE05FPRE03()
  {
    return fieldE05FPRE03.getString();
  }

  /**
  * Set field E05FSIN03 using a String value.
  */
  public void setE05FSIN03(String newvalue)
  {
    fieldE05FSIN03.setString(newvalue);
  }

  /**
  * Get value of field E05FSIN03 as a String.
  */
  public String getE05FSIN03()
  {
    return fieldE05FSIN03.getString();
  }

  /**
  * Set field E05RDEN03 using a String value.
  */
  public void setE05RDEN03(String newvalue)
  {
    fieldE05RDEN03.setString(newvalue);
  }

  /**
  * Get value of field E05RDEN03 as a String.
  */
  public String getE05RDEN03()
  {
    return fieldE05RDEN03.getString();
  }

  /**
  * Set field E05NDEN03 using a String value.
  */
  public void setE05NDEN03(String newvalue)
  {
    fieldE05NDEN03.setString(newvalue);
  }

  /**
  * Get value of field E05NDEN03 as a String.
  */
  public String getE05NDEN03()
  {
    return fieldE05NDEN03.getString();
  }

  /**
  * Set field E05CODI04 using a String value.
  */
  public void setE05CODI04(String newvalue)
  {
    fieldE05CODI04.setString(newvalue);
  }

  /**
  * Get value of field E05CODI04 as a String.
  */
  public String getE05CODI04()
  {
    return fieldE05CODI04.getString();
  }

  /**
  * Set field E05CUEN04 using a String value.
  */
  public void setE05CUEN04(String newvalue)
  {
    fieldE05CUEN04.setString(newvalue);
  }

  /**
  * Get value of field E05CUEN04 as a String.
  */
  public String getE05CUEN04()
  {
    return fieldE05CUEN04.getString();
  }

  /**
  * Set numeric field E05CUEN04 using a BigDecimal value.
  */
  public void setE05CUEN04(BigDecimal newvalue)
  {
    fieldE05CUEN04.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05CUEN04 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05CUEN04()
  {
    return fieldE05CUEN04.getBigDecimal();
  }

  /**
  * Set field E05FPRE04 using a String value.
  */
  public void setE05FPRE04(String newvalue)
  {
    fieldE05FPRE04.setString(newvalue);
  }

  /**
  * Get value of field E05FPRE04 as a String.
  */
  public String getE05FPRE04()
  {
    return fieldE05FPRE04.getString();
  }

  /**
  * Set field E05FSIN04 using a String value.
  */
  public void setE05FSIN04(String newvalue)
  {
    fieldE05FSIN04.setString(newvalue);
  }

  /**
  * Get value of field E05FSIN04 as a String.
  */
  public String getE05FSIN04()
  {
    return fieldE05FSIN04.getString();
  }

  /**
  * Set field E05RDEN04 using a String value.
  */
  public void setE05RDEN04(String newvalue)
  {
    fieldE05RDEN04.setString(newvalue);
  }

  /**
  * Get value of field E05RDEN04 as a String.
  */
  public String getE05RDEN04()
  {
    return fieldE05RDEN04.getString();
  }

  /**
  * Set field E05NDEN04 using a String value.
  */
  public void setE05NDEN04(String newvalue)
  {
    fieldE05NDEN04.setString(newvalue);
  }

  /**
  * Get value of field E05NDEN04 as a String.
  */
  public String getE05NDEN04()
  {
    return fieldE05NDEN04.getString();
  }

  /**
  * Set field E05CODI05 using a String value.
  */
  public void setE05CODI05(String newvalue)
  {
    fieldE05CODI05.setString(newvalue);
  }

  /**
  * Get value of field E05CODI05 as a String.
  */
  public String getE05CODI05()
  {
    return fieldE05CODI05.getString();
  }

  /**
  * Set field E05CUEN05 using a String value.
  */
  public void setE05CUEN05(String newvalue)
  {
    fieldE05CUEN05.setString(newvalue);
  }

  /**
  * Get value of field E05CUEN05 as a String.
  */
  public String getE05CUEN05()
  {
    return fieldE05CUEN05.getString();
  }

  /**
  * Set numeric field E05CUEN05 using a BigDecimal value.
  */
  public void setE05CUEN05(BigDecimal newvalue)
  {
    fieldE05CUEN05.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05CUEN05 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05CUEN05()
  {
    return fieldE05CUEN05.getBigDecimal();
  }

  /**
  * Set field E05FPRE05 using a String value.
  */
  public void setE05FPRE05(String newvalue)
  {
    fieldE05FPRE05.setString(newvalue);
  }

  /**
  * Get value of field E05FPRE05 as a String.
  */
  public String getE05FPRE05()
  {
    return fieldE05FPRE05.getString();
  }

  /**
  * Set field E05FSIN05 using a String value.
  */
  public void setE05FSIN05(String newvalue)
  {
    fieldE05FSIN05.setString(newvalue);
  }

  /**
  * Get value of field E05FSIN05 as a String.
  */
  public String getE05FSIN05()
  {
    return fieldE05FSIN05.getString();
  }

  /**
  * Set field E05RDEN05 using a String value.
  */
  public void setE05RDEN05(String newvalue)
  {
    fieldE05RDEN05.setString(newvalue);
  }

  /**
  * Get value of field E05RDEN05 as a String.
  */
  public String getE05RDEN05()
  {
    return fieldE05RDEN05.getString();
  }

  /**
  * Set field E05NDEN05 using a String value.
  */
  public void setE05NDEN05(String newvalue)
  {
    fieldE05NDEN05.setString(newvalue);
  }

  /**
  * Get value of field E05NDEN05 as a String.
  */
  public String getE05NDEN05()
  {
    return fieldE05NDEN05.getString();
  }

  /**
  * Set field E05CODI06 using a String value.
  */
  public void setE05CODI06(String newvalue)
  {
    fieldE05CODI06.setString(newvalue);
  }

  /**
  * Get value of field E05CODI06 as a String.
  */
  public String getE05CODI06()
  {
    return fieldE05CODI06.getString();
  }

  /**
  * Set field E05CUEN06 using a String value.
  */
  public void setE05CUEN06(String newvalue)
  {
    fieldE05CUEN06.setString(newvalue);
  }

  /**
  * Get value of field E05CUEN06 as a String.
  */
  public String getE05CUEN06()
  {
    return fieldE05CUEN06.getString();
  }

  /**
  * Set numeric field E05CUEN06 using a BigDecimal value.
  */
  public void setE05CUEN06(BigDecimal newvalue)
  {
    fieldE05CUEN06.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05CUEN06 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05CUEN06()
  {
    return fieldE05CUEN06.getBigDecimal();
  }

  /**
  * Set field E05FPRE06 using a String value.
  */
  public void setE05FPRE06(String newvalue)
  {
    fieldE05FPRE06.setString(newvalue);
  }

  /**
  * Get value of field E05FPRE06 as a String.
  */
  public String getE05FPRE06()
  {
    return fieldE05FPRE06.getString();
  }

  /**
  * Set field E05FSIN06 using a String value.
  */
  public void setE05FSIN06(String newvalue)
  {
    fieldE05FSIN06.setString(newvalue);
  }

  /**
  * Get value of field E05FSIN06 as a String.
  */
  public String getE05FSIN06()
  {
    return fieldE05FSIN06.getString();
  }

  /**
  * Set field E05RDEN06 using a String value.
  */
  public void setE05RDEN06(String newvalue)
  {
    fieldE05RDEN06.setString(newvalue);
  }

  /**
  * Get value of field E05RDEN06 as a String.
  */
  public String getE05RDEN06()
  {
    return fieldE05RDEN06.getString();
  }

  /**
  * Set field E05NDEN06 using a String value.
  */
  public void setE05NDEN06(String newvalue)
  {
    fieldE05NDEN06.setString(newvalue);
  }

  /**
  * Get value of field E05NDEN06 as a String.
  */
  public String getE05NDEN06()
  {
    return fieldE05NDEN06.getString();
  }

  /**
  * Set field E05CODI07 using a String value.
  */
  public void setE05CODI07(String newvalue)
  {
    fieldE05CODI07.setString(newvalue);
  }

  /**
  * Get value of field E05CODI07 as a String.
  */
  public String getE05CODI07()
  {
    return fieldE05CODI07.getString();
  }

  /**
  * Set field E05CUEN07 using a String value.
  */
  public void setE05CUEN07(String newvalue)
  {
    fieldE05CUEN07.setString(newvalue);
  }

  /**
  * Get value of field E05CUEN07 as a String.
  */
  public String getE05CUEN07()
  {
    return fieldE05CUEN07.getString();
  }

  /**
  * Set numeric field E05CUEN07 using a BigDecimal value.
  */
  public void setE05CUEN07(BigDecimal newvalue)
  {
    fieldE05CUEN07.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05CUEN07 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05CUEN07()
  {
    return fieldE05CUEN07.getBigDecimal();
  }

  /**
  * Set field E05FPRE07 using a String value.
  */
  public void setE05FPRE07(String newvalue)
  {
    fieldE05FPRE07.setString(newvalue);
  }

  /**
  * Get value of field E05FPRE07 as a String.
  */
  public String getE05FPRE07()
  {
    return fieldE05FPRE07.getString();
  }

  /**
  * Set field E05FSIN07 using a String value.
  */
  public void setE05FSIN07(String newvalue)
  {
    fieldE05FSIN07.setString(newvalue);
  }

  /**
  * Get value of field E05FSIN07 as a String.
  */
  public String getE05FSIN07()
  {
    return fieldE05FSIN07.getString();
  }

  /**
  * Set field E05RDEN07 using a String value.
  */
  public void setE05RDEN07(String newvalue)
  {
    fieldE05RDEN07.setString(newvalue);
  }

  /**
  * Get value of field E05RDEN07 as a String.
  */
  public String getE05RDEN07()
  {
    return fieldE05RDEN07.getString();
  }

  /**
  * Set field E05NDEN07 using a String value.
  */
  public void setE05NDEN07(String newvalue)
  {
    fieldE05NDEN07.setString(newvalue);
  }

  /**
  * Get value of field E05NDEN07 as a String.
  */
  public String getE05NDEN07()
  {
    return fieldE05NDEN07.getString();
  }

  /**
  * Set field E05CODI08 using a String value.
  */
  public void setE05CODI08(String newvalue)
  {
    fieldE05CODI08.setString(newvalue);
  }

  /**
  * Get value of field E05CODI08 as a String.
  */
  public String getE05CODI08()
  {
    return fieldE05CODI08.getString();
  }

  /**
  * Set field E05CUEN08 using a String value.
  */
  public void setE05CUEN08(String newvalue)
  {
    fieldE05CUEN08.setString(newvalue);
  }

  /**
  * Get value of field E05CUEN08 as a String.
  */
  public String getE05CUEN08()
  {
    return fieldE05CUEN08.getString();
  }

  /**
  * Set numeric field E05CUEN08 using a BigDecimal value.
  */
  public void setE05CUEN08(BigDecimal newvalue)
  {
    fieldE05CUEN08.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05CUEN08 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05CUEN08()
  {
    return fieldE05CUEN08.getBigDecimal();
  }

  /**
  * Set field E05FPRE08 using a String value.
  */
  public void setE05FPRE08(String newvalue)
  {
    fieldE05FPRE08.setString(newvalue);
  }

  /**
  * Get value of field E05FPRE08 as a String.
  */
  public String getE05FPRE08()
  {
    return fieldE05FPRE08.getString();
  }

  /**
  * Set field E05FSIN08 using a String value.
  */
  public void setE05FSIN08(String newvalue)
  {
    fieldE05FSIN08.setString(newvalue);
  }

  /**
  * Get value of field E05FSIN08 as a String.
  */
  public String getE05FSIN08()
  {
    return fieldE05FSIN08.getString();
  }

  /**
  * Set field E05RDEN08 using a String value.
  */
  public void setE05RDEN08(String newvalue)
  {
    fieldE05RDEN08.setString(newvalue);
  }

  /**
  * Get value of field E05RDEN08 as a String.
  */
  public String getE05RDEN08()
  {
    return fieldE05RDEN08.getString();
  }

  /**
  * Set field E05NDEN08 using a String value.
  */
  public void setE05NDEN08(String newvalue)
  {
    fieldE05NDEN08.setString(newvalue);
  }

  /**
  * Get value of field E05NDEN08 as a String.
  */
  public String getE05NDEN08()
  {
    return fieldE05NDEN08.getString();
  }

  /**
  * Set field E05CODI09 using a String value.
  */
  public void setE05CODI09(String newvalue)
  {
    fieldE05CODI09.setString(newvalue);
  }

  /**
  * Get value of field E05CODI09 as a String.
  */
  public String getE05CODI09()
  {
    return fieldE05CODI09.getString();
  }

  /**
  * Set field E05CUEN09 using a String value.
  */
  public void setE05CUEN09(String newvalue)
  {
    fieldE05CUEN09.setString(newvalue);
  }

  /**
  * Get value of field E05CUEN09 as a String.
  */
  public String getE05CUEN09()
  {
    return fieldE05CUEN09.getString();
  }

  /**
  * Set numeric field E05CUEN09 using a BigDecimal value.
  */
  public void setE05CUEN09(BigDecimal newvalue)
  {
    fieldE05CUEN09.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05CUEN09 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05CUEN09()
  {
    return fieldE05CUEN09.getBigDecimal();
  }

  /**
  * Set field E05FPRE09 using a String value.
  */
  public void setE05FPRE09(String newvalue)
  {
    fieldE05FPRE09.setString(newvalue);
  }

  /**
  * Get value of field E05FPRE09 as a String.
  */
  public String getE05FPRE09()
  {
    return fieldE05FPRE09.getString();
  }

  /**
  * Set field E05FSIN09 using a String value.
  */
  public void setE05FSIN09(String newvalue)
  {
    fieldE05FSIN09.setString(newvalue);
  }

  /**
  * Get value of field E05FSIN09 as a String.
  */
  public String getE05FSIN09()
  {
    return fieldE05FSIN09.getString();
  }

  /**
  * Set field E05RDEN09 using a String value.
  */
  public void setE05RDEN09(String newvalue)
  {
    fieldE05RDEN09.setString(newvalue);
  }

  /**
  * Get value of field E05RDEN09 as a String.
  */
  public String getE05RDEN09()
  {
    return fieldE05RDEN09.getString();
  }

  /**
  * Set field E05NDEN09 using a String value.
  */
  public void setE05NDEN09(String newvalue)
  {
    fieldE05NDEN09.setString(newvalue);
  }

  /**
  * Get value of field E05NDEN09 as a String.
  */
  public String getE05NDEN09()
  {
    return fieldE05NDEN09.getString();
  }

  /**
  * Set field E05CODI10 using a String value.
  */
  public void setE05CODI10(String newvalue)
  {
    fieldE05CODI10.setString(newvalue);
  }

  /**
  * Get value of field E05CODI10 as a String.
  */
  public String getE05CODI10()
  {
    return fieldE05CODI10.getString();
  }

  /**
  * Set field E05CUEN10 using a String value.
  */
  public void setE05CUEN10(String newvalue)
  {
    fieldE05CUEN10.setString(newvalue);
  }

  /**
  * Get value of field E05CUEN10 as a String.
  */
  public String getE05CUEN10()
  {
    return fieldE05CUEN10.getString();
  }

  /**
  * Set numeric field E05CUEN10 using a BigDecimal value.
  */
  public void setE05CUEN10(BigDecimal newvalue)
  {
    fieldE05CUEN10.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05CUEN10 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05CUEN10()
  {
    return fieldE05CUEN10.getBigDecimal();
  }

  /**
  * Set field E05FPRE10 using a String value.
  */
  public void setE05FPRE10(String newvalue)
  {
    fieldE05FPRE10.setString(newvalue);
  }

  /**
  * Get value of field E05FPRE10 as a String.
  */
  public String getE05FPRE10()
  {
    return fieldE05FPRE10.getString();
  }

  /**
  * Set field E05FSIN10 using a String value.
  */
  public void setE05FSIN10(String newvalue)
  {
    fieldE05FSIN10.setString(newvalue);
  }

  /**
  * Get value of field E05FSIN10 as a String.
  */
  public String getE05FSIN10()
  {
    return fieldE05FSIN10.getString();
  }

  /**
  * Set field E05RDEN10 using a String value.
  */
  public void setE05RDEN10(String newvalue)
  {
    fieldE05RDEN10.setString(newvalue);
  }

  /**
  * Get value of field E05RDEN10 as a String.
  */
  public String getE05RDEN10()
  {
    return fieldE05RDEN10.getString();
  }

  /**
  * Set field E05NDEN10 using a String value.
  */
  public void setE05NDEN10(String newvalue)
  {
    fieldE05NDEN10.setString(newvalue);
  }

  /**
  * Get value of field E05NDEN10 as a String.
  */
  public String getE05NDEN10()
  {
    return fieldE05NDEN10.getString();
  }

  /**
  * Set field E05CODI11 using a String value.
  */
  public void setE05CODI11(String newvalue)
  {
    fieldE05CODI11.setString(newvalue);
  }

  /**
  * Get value of field E05CODI11 as a String.
  */
  public String getE05CODI11()
  {
    return fieldE05CODI11.getString();
  }

  /**
  * Set field E05CUEN11 using a String value.
  */
  public void setE05CUEN11(String newvalue)
  {
    fieldE05CUEN11.setString(newvalue);
  }

  /**
  * Get value of field E05CUEN11 as a String.
  */
  public String getE05CUEN11()
  {
    return fieldE05CUEN11.getString();
  }

  /**
  * Set numeric field E05CUEN11 using a BigDecimal value.
  */
  public void setE05CUEN11(BigDecimal newvalue)
  {
    fieldE05CUEN11.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05CUEN11 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05CUEN11()
  {
    return fieldE05CUEN11.getBigDecimal();
  }

  /**
  * Set field E05FPRE11 using a String value.
  */
  public void setE05FPRE11(String newvalue)
  {
    fieldE05FPRE11.setString(newvalue);
  }

  /**
  * Get value of field E05FPRE11 as a String.
  */
  public String getE05FPRE11()
  {
    return fieldE05FPRE11.getString();
  }

  /**
  * Set field E05FSIN11 using a String value.
  */
  public void setE05FSIN11(String newvalue)
  {
    fieldE05FSIN11.setString(newvalue);
  }

  /**
  * Get value of field E05FSIN11 as a String.
  */
  public String getE05FSIN11()
  {
    return fieldE05FSIN11.getString();
  }

  /**
  * Set field E05RDEN11 using a String value.
  */
  public void setE05RDEN11(String newvalue)
  {
    fieldE05RDEN11.setString(newvalue);
  }

  /**
  * Get value of field E05RDEN11 as a String.
  */
  public String getE05RDEN11()
  {
    return fieldE05RDEN11.getString();
  }

  /**
  * Set field E05NDEN11 using a String value.
  */
  public void setE05NDEN11(String newvalue)
  {
    fieldE05NDEN11.setString(newvalue);
  }

  /**
  * Get value of field E05NDEN11 as a String.
  */
  public String getE05NDEN11()
  {
    return fieldE05NDEN11.getString();
  }

  /**
  * Set field E05CODI12 using a String value.
  */
  public void setE05CODI12(String newvalue)
  {
    fieldE05CODI12.setString(newvalue);
  }

  /**
  * Get value of field E05CODI12 as a String.
  */
  public String getE05CODI12()
  {
    return fieldE05CODI12.getString();
  }

  /**
  * Set field E05CUEN12 using a String value.
  */
  public void setE05CUEN12(String newvalue)
  {
    fieldE05CUEN12.setString(newvalue);
  }

  /**
  * Get value of field E05CUEN12 as a String.
  */
  public String getE05CUEN12()
  {
    return fieldE05CUEN12.getString();
  }

  /**
  * Set numeric field E05CUEN12 using a BigDecimal value.
  */
  public void setE05CUEN12(BigDecimal newvalue)
  {
    fieldE05CUEN12.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05CUEN12 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05CUEN12()
  {
    return fieldE05CUEN12.getBigDecimal();
  }

  /**
  * Set field E05FPRE12 using a String value.
  */
  public void setE05FPRE12(String newvalue)
  {
    fieldE05FPRE12.setString(newvalue);
  }

  /**
  * Get value of field E05FPRE12 as a String.
  */
  public String getE05FPRE12()
  {
    return fieldE05FPRE12.getString();
  }

  /**
  * Set field E05FSIN12 using a String value.
  */
  public void setE05FSIN12(String newvalue)
  {
    fieldE05FSIN12.setString(newvalue);
  }

  /**
  * Get value of field E05FSIN12 as a String.
  */
  public String getE05FSIN12()
  {
    return fieldE05FSIN12.getString();
  }

  /**
  * Set field E05RDEN12 using a String value.
  */
  public void setE05RDEN12(String newvalue)
  {
    fieldE05RDEN12.setString(newvalue);
  }

  /**
  * Get value of field E05RDEN12 as a String.
  */
  public String getE05RDEN12()
  {
    return fieldE05RDEN12.getString();
  }

  /**
  * Set field E05NDEN12 using a String value.
  */
  public void setE05NDEN12(String newvalue)
  {
    fieldE05NDEN12.setString(newvalue);
  }

  /**
  * Get value of field E05NDEN12 as a String.
  */
  public String getE05NDEN12()
  {
    return fieldE05NDEN12.getString();
  }

  /**
  * Set field E05CODI13 using a String value.
  */
  public void setE05CODI13(String newvalue)
  {
    fieldE05CODI13.setString(newvalue);
  }

  /**
  * Get value of field E05CODI13 as a String.
  */
  public String getE05CODI13()
  {
    return fieldE05CODI13.getString();
  }

  /**
  * Set field E05CUEN13 using a String value.
  */
  public void setE05CUEN13(String newvalue)
  {
    fieldE05CUEN13.setString(newvalue);
  }

  /**
  * Get value of field E05CUEN13 as a String.
  */
  public String getE05CUEN13()
  {
    return fieldE05CUEN13.getString();
  }

  /**
  * Set numeric field E05CUEN13 using a BigDecimal value.
  */
  public void setE05CUEN13(BigDecimal newvalue)
  {
    fieldE05CUEN13.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05CUEN13 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05CUEN13()
  {
    return fieldE05CUEN13.getBigDecimal();
  }

  /**
  * Set field E05FPRE13 using a String value.
  */
  public void setE05FPRE13(String newvalue)
  {
    fieldE05FPRE13.setString(newvalue);
  }

  /**
  * Get value of field E05FPRE13 as a String.
  */
  public String getE05FPRE13()
  {
    return fieldE05FPRE13.getString();
  }

  /**
  * Set field E05FSIN13 using a String value.
  */
  public void setE05FSIN13(String newvalue)
  {
    fieldE05FSIN13.setString(newvalue);
  }

  /**
  * Get value of field E05FSIN13 as a String.
  */
  public String getE05FSIN13()
  {
    return fieldE05FSIN13.getString();
  }

  /**
  * Set field E05RDEN13 using a String value.
  */
  public void setE05RDEN13(String newvalue)
  {
    fieldE05RDEN13.setString(newvalue);
  }

  /**
  * Get value of field E05RDEN13 as a String.
  */
  public String getE05RDEN13()
  {
    return fieldE05RDEN13.getString();
  }

  /**
  * Set field E05NDEN13 using a String value.
  */
  public void setE05NDEN13(String newvalue)
  {
    fieldE05NDEN13.setString(newvalue);
  }

  /**
  * Get value of field E05NDEN13 as a String.
  */
  public String getE05NDEN13()
  {
    return fieldE05NDEN13.getString();
  }

  /**
  * Set field E05CODI14 using a String value.
  */
  public void setE05CODI14(String newvalue)
  {
    fieldE05CODI14.setString(newvalue);
  }

  /**
  * Get value of field E05CODI14 as a String.
  */
  public String getE05CODI14()
  {
    return fieldE05CODI14.getString();
  }

  /**
  * Set field E05CUEN14 using a String value.
  */
  public void setE05CUEN14(String newvalue)
  {
    fieldE05CUEN14.setString(newvalue);
  }

  /**
  * Get value of field E05CUEN14 as a String.
  */
  public String getE05CUEN14()
  {
    return fieldE05CUEN14.getString();
  }

  /**
  * Set numeric field E05CUEN14 using a BigDecimal value.
  */
  public void setE05CUEN14(BigDecimal newvalue)
  {
    fieldE05CUEN14.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05CUEN14 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05CUEN14()
  {
    return fieldE05CUEN14.getBigDecimal();
  }

  /**
  * Set field E05FPRE14 using a String value.
  */
  public void setE05FPRE14(String newvalue)
  {
    fieldE05FPRE14.setString(newvalue);
  }

  /**
  * Get value of field E05FPRE14 as a String.
  */
  public String getE05FPRE14()
  {
    return fieldE05FPRE14.getString();
  }

  /**
  * Set field E05FSIN14 using a String value.
  */
  public void setE05FSIN14(String newvalue)
  {
    fieldE05FSIN14.setString(newvalue);
  }

  /**
  * Get value of field E05FSIN14 as a String.
  */
  public String getE05FSIN14()
  {
    return fieldE05FSIN14.getString();
  }

  /**
  * Set field E05RDEN14 using a String value.
  */
  public void setE05RDEN14(String newvalue)
  {
    fieldE05RDEN14.setString(newvalue);
  }

  /**
  * Get value of field E05RDEN14 as a String.
  */
  public String getE05RDEN14()
  {
    return fieldE05RDEN14.getString();
  }

  /**
  * Set field E05NDEN14 using a String value.
  */
  public void setE05NDEN14(String newvalue)
  {
    fieldE05NDEN14.setString(newvalue);
  }

  /**
  * Get value of field E05NDEN14 as a String.
  */
  public String getE05NDEN14()
  {
    return fieldE05NDEN14.getString();
  }

  /**
  * Set field E05CODI15 using a String value.
  */
  public void setE05CODI15(String newvalue)
  {
    fieldE05CODI15.setString(newvalue);
  }

  /**
  * Get value of field E05CODI15 as a String.
  */
  public String getE05CODI15()
  {
    return fieldE05CODI15.getString();
  }

  /**
  * Set field E05CUEN15 using a String value.
  */
  public void setE05CUEN15(String newvalue)
  {
    fieldE05CUEN15.setString(newvalue);
  }

  /**
  * Get value of field E05CUEN15 as a String.
  */
  public String getE05CUEN15()
  {
    return fieldE05CUEN15.getString();
  }

  /**
  * Set numeric field E05CUEN15 using a BigDecimal value.
  */
  public void setE05CUEN15(BigDecimal newvalue)
  {
    fieldE05CUEN15.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05CUEN15 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05CUEN15()
  {
    return fieldE05CUEN15.getBigDecimal();
  }

  /**
  * Set field E05FPRE15 using a String value.
  */
  public void setE05FPRE15(String newvalue)
  {
    fieldE05FPRE15.setString(newvalue);
  }

  /**
  * Get value of field E05FPRE15 as a String.
  */
  public String getE05FPRE15()
  {
    return fieldE05FPRE15.getString();
  }

  /**
  * Set field E05FSIN15 using a String value.
  */
  public void setE05FSIN15(String newvalue)
  {
    fieldE05FSIN15.setString(newvalue);
  }

  /**
  * Get value of field E05FSIN15 as a String.
  */
  public String getE05FSIN15()
  {
    return fieldE05FSIN15.getString();
  }

  /**
  * Set field E05RDEN15 using a String value.
  */
  public void setE05RDEN15(String newvalue)
  {
    fieldE05RDEN15.setString(newvalue);
  }

  /**
  * Get value of field E05RDEN15 as a String.
  */
  public String getE05RDEN15()
  {
    return fieldE05RDEN15.getString();
  }

  /**
  * Set field E05NDEN15 using a String value.
  */
  public void setE05NDEN15(String newvalue)
  {
    fieldE05NDEN15.setString(newvalue);
  }

  /**
  * Get value of field E05NDEN15 as a String.
  */
  public String getE05NDEN15()
  {
    return fieldE05NDEN15.getString();
  }

  /**
  * Set field E05CODI16 using a String value.
  */
  public void setE05CODI16(String newvalue)
  {
    fieldE05CODI16.setString(newvalue);
  }

  /**
  * Get value of field E05CODI16 as a String.
  */
  public String getE05CODI16()
  {
    return fieldE05CODI16.getString();
  }

  /**
  * Set field E05CUEN16 using a String value.
  */
  public void setE05CUEN16(String newvalue)
  {
    fieldE05CUEN16.setString(newvalue);
  }

  /**
  * Get value of field E05CUEN16 as a String.
  */
  public String getE05CUEN16()
  {
    return fieldE05CUEN16.getString();
  }

  /**
  * Set numeric field E05CUEN16 using a BigDecimal value.
  */
  public void setE05CUEN16(BigDecimal newvalue)
  {
    fieldE05CUEN16.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05CUEN16 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05CUEN16()
  {
    return fieldE05CUEN16.getBigDecimal();
  }

  /**
  * Set field E05FPRE16 using a String value.
  */
  public void setE05FPRE16(String newvalue)
  {
    fieldE05FPRE16.setString(newvalue);
  }

  /**
  * Get value of field E05FPRE16 as a String.
  */
  public String getE05FPRE16()
  {
    return fieldE05FPRE16.getString();
  }

  /**
  * Set field E05FSIN16 using a String value.
  */
  public void setE05FSIN16(String newvalue)
  {
    fieldE05FSIN16.setString(newvalue);
  }

  /**
  * Get value of field E05FSIN16 as a String.
  */
  public String getE05FSIN16()
  {
    return fieldE05FSIN16.getString();
  }

  /**
  * Set field E05RDEN16 using a String value.
  */
  public void setE05RDEN16(String newvalue)
  {
    fieldE05RDEN16.setString(newvalue);
  }

  /**
  * Get value of field E05RDEN16 as a String.
  */
  public String getE05RDEN16()
  {
    return fieldE05RDEN16.getString();
  }

  /**
  * Set field E05NDEN16 using a String value.
  */
  public void setE05NDEN16(String newvalue)
  {
    fieldE05NDEN16.setString(newvalue);
  }

  /**
  * Get value of field E05NDEN16 as a String.
  */
  public String getE05NDEN16()
  {
    return fieldE05NDEN16.getString();
  }

  /**
  * Set field E05CODI17 using a String value.
  */
  public void setE05CODI17(String newvalue)
  {
    fieldE05CODI17.setString(newvalue);
  }

  /**
  * Get value of field E05CODI17 as a String.
  */
  public String getE05CODI17()
  {
    return fieldE05CODI17.getString();
  }

  /**
  * Set field E05CUEN17 using a String value.
  */
  public void setE05CUEN17(String newvalue)
  {
    fieldE05CUEN17.setString(newvalue);
  }

  /**
  * Get value of field E05CUEN17 as a String.
  */
  public String getE05CUEN17()
  {
    return fieldE05CUEN17.getString();
  }

  /**
  * Set numeric field E05CUEN17 using a BigDecimal value.
  */
  public void setE05CUEN17(BigDecimal newvalue)
  {
    fieldE05CUEN17.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05CUEN17 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05CUEN17()
  {
    return fieldE05CUEN17.getBigDecimal();
  }

  /**
  * Set field E05FPRE17 using a String value.
  */
  public void setE05FPRE17(String newvalue)
  {
    fieldE05FPRE17.setString(newvalue);
  }

  /**
  * Get value of field E05FPRE17 as a String.
  */
  public String getE05FPRE17()
  {
    return fieldE05FPRE17.getString();
  }

  /**
  * Set field E05FSIN17 using a String value.
  */
  public void setE05FSIN17(String newvalue)
  {
    fieldE05FSIN17.setString(newvalue);
  }

  /**
  * Get value of field E05FSIN17 as a String.
  */
  public String getE05FSIN17()
  {
    return fieldE05FSIN17.getString();
  }

  /**
  * Set field E05RDEN17 using a String value.
  */
  public void setE05RDEN17(String newvalue)
  {
    fieldE05RDEN17.setString(newvalue);
  }

  /**
  * Get value of field E05RDEN17 as a String.
  */
  public String getE05RDEN17()
  {
    return fieldE05RDEN17.getString();
  }

  /**
  * Set field E05NDEN17 using a String value.
  */
  public void setE05NDEN17(String newvalue)
  {
    fieldE05NDEN17.setString(newvalue);
  }

  /**
  * Get value of field E05NDEN17 as a String.
  */
  public String getE05NDEN17()
  {
    return fieldE05NDEN17.getString();
  }

  /**
  * Set field E05CODI18 using a String value.
  */
  public void setE05CODI18(String newvalue)
  {
    fieldE05CODI18.setString(newvalue);
  }

  /**
  * Get value of field E05CODI18 as a String.
  */
  public String getE05CODI18()
  {
    return fieldE05CODI18.getString();
  }

  /**
  * Set field E05CUEN18 using a String value.
  */
  public void setE05CUEN18(String newvalue)
  {
    fieldE05CUEN18.setString(newvalue);
  }

  /**
  * Get value of field E05CUEN18 as a String.
  */
  public String getE05CUEN18()
  {
    return fieldE05CUEN18.getString();
  }

  /**
  * Set numeric field E05CUEN18 using a BigDecimal value.
  */
  public void setE05CUEN18(BigDecimal newvalue)
  {
    fieldE05CUEN18.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05CUEN18 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05CUEN18()
  {
    return fieldE05CUEN18.getBigDecimal();
  }

  /**
  * Set field E05FPRE18 using a String value.
  */
  public void setE05FPRE18(String newvalue)
  {
    fieldE05FPRE18.setString(newvalue);
  }

  /**
  * Get value of field E05FPRE18 as a String.
  */
  public String getE05FPRE18()
  {
    return fieldE05FPRE18.getString();
  }

  /**
  * Set field E05FSIN18 using a String value.
  */
  public void setE05FSIN18(String newvalue)
  {
    fieldE05FSIN18.setString(newvalue);
  }

  /**
  * Get value of field E05FSIN18 as a String.
  */
  public String getE05FSIN18()
  {
    return fieldE05FSIN18.getString();
  }

  /**
  * Set field E05RDEN18 using a String value.
  */
  public void setE05RDEN18(String newvalue)
  {
    fieldE05RDEN18.setString(newvalue);
  }

  /**
  * Get value of field E05RDEN18 as a String.
  */
  public String getE05RDEN18()
  {
    return fieldE05RDEN18.getString();
  }

  /**
  * Set field E05NDEN18 using a String value.
  */
  public void setE05NDEN18(String newvalue)
  {
    fieldE05NDEN18.setString(newvalue);
  }

  /**
  * Get value of field E05NDEN18 as a String.
  */
  public String getE05NDEN18()
  {
    return fieldE05NDEN18.getString();
  }

  /**
  * Set field E05CODI19 using a String value.
  */
  public void setE05CODI19(String newvalue)
  {
    fieldE05CODI19.setString(newvalue);
  }

  /**
  * Get value of field E05CODI19 as a String.
  */
  public String getE05CODI19()
  {
    return fieldE05CODI19.getString();
  }

  /**
  * Set field E05CUEN19 using a String value.
  */
  public void setE05CUEN19(String newvalue)
  {
    fieldE05CUEN19.setString(newvalue);
  }

  /**
  * Get value of field E05CUEN19 as a String.
  */
  public String getE05CUEN19()
  {
    return fieldE05CUEN19.getString();
  }

  /**
  * Set numeric field E05CUEN19 using a BigDecimal value.
  */
  public void setE05CUEN19(BigDecimal newvalue)
  {
    fieldE05CUEN19.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05CUEN19 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05CUEN19()
  {
    return fieldE05CUEN19.getBigDecimal();
  }

  /**
  * Set field E05FPRE19 using a String value.
  */
  public void setE05FPRE19(String newvalue)
  {
    fieldE05FPRE19.setString(newvalue);
  }

  /**
  * Get value of field E05FPRE19 as a String.
  */
  public String getE05FPRE19()
  {
    return fieldE05FPRE19.getString();
  }

  /**
  * Set field E05FSIN19 using a String value.
  */
  public void setE05FSIN19(String newvalue)
  {
    fieldE05FSIN19.setString(newvalue);
  }

  /**
  * Get value of field E05FSIN19 as a String.
  */
  public String getE05FSIN19()
  {
    return fieldE05FSIN19.getString();
  }

  /**
  * Set field E05RDEN19 using a String value.
  */
  public void setE05RDEN19(String newvalue)
  {
    fieldE05RDEN19.setString(newvalue);
  }

  /**
  * Get value of field E05RDEN19 as a String.
  */
  public String getE05RDEN19()
  {
    return fieldE05RDEN19.getString();
  }

  /**
  * Set field E05NDEN19 using a String value.
  */
  public void setE05NDEN19(String newvalue)
  {
    fieldE05NDEN19.setString(newvalue);
  }

  /**
  * Get value of field E05NDEN19 as a String.
  */
  public String getE05NDEN19()
  {
    return fieldE05NDEN19.getString();
  }

  /**
  * Set field E05CODI20 using a String value.
  */
  public void setE05CODI20(String newvalue)
  {
    fieldE05CODI20.setString(newvalue);
  }

  /**
  * Get value of field E05CODI20 as a String.
  */
  public String getE05CODI20()
  {
    return fieldE05CODI20.getString();
  }

  /**
  * Set field E05CUEN20 using a String value.
  */
  public void setE05CUEN20(String newvalue)
  {
    fieldE05CUEN20.setString(newvalue);
  }

  /**
  * Get value of field E05CUEN20 as a String.
  */
  public String getE05CUEN20()
  {
    return fieldE05CUEN20.getString();
  }

  /**
  * Set numeric field E05CUEN20 using a BigDecimal value.
  */
  public void setE05CUEN20(BigDecimal newvalue)
  {
    fieldE05CUEN20.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E05CUEN20 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE05CUEN20()
  {
    return fieldE05CUEN20.getBigDecimal();
  }

  /**
  * Set field E05FPRE20 using a String value.
  */
  public void setE05FPRE20(String newvalue)
  {
    fieldE05FPRE20.setString(newvalue);
  }

  /**
  * Get value of field E05FPRE20 as a String.
  */
  public String getE05FPRE20()
  {
    return fieldE05FPRE20.getString();
  }

  /**
  * Set field E05FSIN20 using a String value.
  */
  public void setE05FSIN20(String newvalue)
  {
    fieldE05FSIN20.setString(newvalue);
  }

  /**
  * Get value of field E05FSIN20 as a String.
  */
  public String getE05FSIN20()
  {
    return fieldE05FSIN20.getString();
  }

  /**
  * Set field E05RDEN20 using a String value.
  */
  public void setE05RDEN20(String newvalue)
  {
    fieldE05RDEN20.setString(newvalue);
  }

  /**
  * Get value of field E05RDEN20 as a String.
  */
  public String getE05RDEN20()
  {
    return fieldE05RDEN20.getString();
  }

  /**
  * Set field E05NDEN20 using a String value.
  */
  public void setE05NDEN20(String newvalue)
  {
    fieldE05NDEN20.setString(newvalue);
  }

  /**
  * Get value of field E05NDEN20 as a String.
  */
  public String getE05NDEN20()
  {
    return fieldE05NDEN20.getString();
  }

}
