package datapro.eibs.beans;

import datapro.eibs.sockets.*;
import java.io.*;
import java.math.*;

import java.util.*;

/**
* Class generated by AS/400 CRTCLASS command from ESR000104 physical file definition.
* 
* File level identifier is 1100706173657.
* Record format level identifier is 4CCC995A07219.
*/

public class ESR000104Message extends MessageRecord
{
  final static String fldnames[] = {
                                     "H02USERID",
                                     "H02PROGRM",
                                     "H02TIMSYS",
                                     "H02SCRCOD",
                                     "H02OPECOD",
                                     "H02FLGMAS",
                                     "H02FLGWK1",
                                     "H02FLGWK2",
                                     "H02FLGWK3",
                                     "ESRACC",
                                     "ESRIDN",
                                     "ESRCAT",
                                     "ESRCOD",
                                     "ESRFIA",
                                     "ESRFIM",
                                     "ESRFID",
                                     "ESRFTA",
                                     "ESRFTM",
                                     "ESRFTD",
                                     "ESRPRD",
                                     "ESROPE",
                                     "ESRF1A",
                                     "ESRF1M",
                                     "ESRF1D",
                                     "ESRF2A",
                                     "ESRF2M",
                                     "ESRF2D",
                                     "ESRNU1",
                                     "ESRNU2",
                                     "ESRGL1",
                                     "ESRGL2",
                                     "ESRCAL",
                                     "ESRORI",
                                     "ESRCOR",
                                     "ESREST",
                                     "ESRUSR",
                                     "ESRPRI",
                                     "ESRXRT"
                                   };
  final static String tnames[] = {
                                   "H02USERID",
                                   "H02PROGRM",
                                   "H02TIMSYS",
                                   "H02SCRCOD",
                                   "H02OPECOD",
                                   "H02FLGMAS",
                                   "H02FLGWK1",
                                   "H02FLGWK2",
                                   "H02FLGWK3",
                                   "ESRACC",
                                   "ESRIDN",
                                   "ESRCAT",
                                   "ESRCOD",
                                   "ESRFIA",
                                   "ESRFIM",
                                   "ESRFID",
                                   "ESRFTA",
                                   "ESRFTM",
                                   "ESRFTD",
                                   "ESRPRD",
                                   "ESROPE",
                                   "ESRF1A",
                                   "ESRF1M",
                                   "ESRF1D",
                                   "ESRF2A",
                                   "ESRF2M",
                                   "ESRF2D",
                                   "ESRNU1",
                                   "ESRNU2",
                                   "ESRGL1",
                                   "ESRGL2",
                                   "ESRCAL",
                                   "ESRORI",
                                   "ESRCOR",
                                   "ESREST",
                                   "ESRUSR",
                                   "ESRPRI",
                                   "ESRXRT"
                                 };
  final static String fid = "1100706173657";
  final static String rid = "4CCC995A07219";
  final static String fmtname = "ESR000104";
  final int FIELDCOUNT = 38;
  private static Hashtable tlookup = new Hashtable();
  private CharacterField fieldH02USERID = null;
  private CharacterField fieldH02PROGRM = null;
  private CharacterField fieldH02TIMSYS = null;
  private CharacterField fieldH02SCRCOD = null;
  private CharacterField fieldH02OPECOD = null;
  private CharacterField fieldH02FLGMAS = null;
  private CharacterField fieldH02FLGWK1 = null;
  private CharacterField fieldH02FLGWK2 = null;
  private CharacterField fieldH02FLGWK3 = null;
  private CharacterField fieldESRACC = null;
  private CharacterField fieldESRIDN = null;
  private CharacterField fieldESRCAT = null;
  private CharacterField fieldESRCOD = null;
  private DecimalField fieldESRFIA = null;
  private DecimalField fieldESRFIM = null;
  private DecimalField fieldESRFID = null;
  private DecimalField fieldESRFTA = null;
  private DecimalField fieldESRFTM = null;
  private DecimalField fieldESRFTD = null;
  private CharacterField fieldESRPRD = null;
  private CharacterField fieldESROPE = null;
  private DecimalField fieldESRF1A = null;
  private DecimalField fieldESRF1M = null;
  private DecimalField fieldESRF1D = null;
  private DecimalField fieldESRF2A = null;
  private DecimalField fieldESRF2M = null;
  private DecimalField fieldESRF2D = null;
  private DecimalField fieldESRNU1 = null;
  private DecimalField fieldESRNU2 = null;
  private CharacterField fieldESRGL1 = null;
  private CharacterField fieldESRGL2 = null;
  private CharacterField fieldESRCAL = null;
  private CharacterField fieldESRORI = null;
  private CharacterField fieldESRCOR = null;
  private CharacterField fieldESREST = null;
  private CharacterField fieldESRUSR = null;
  private DecimalField fieldESRPRI = null;
  private DecimalField fieldESRXRT = null;

  /**
  * Constructor for ESR000104Message.
  */
  public ESR000104Message()
  {
    createFields();
    initialize();
  }

  /**
  * Create fields for this message.
  * This method implements the abstract method in the MessageRecord superclass.
  */
  protected void createFields()
  {
    recordsize = 222;
    fileid = fid;
    recordid = rid;
    message = new byte[getByteLength()];
    formatname = fmtname;
    fieldnames = fldnames;
    tagnames = tnames;
    fields = new MessageField[FIELDCOUNT];

    fields[0] = fieldH02USERID =
    new CharacterField(message, HEADERSIZE + 0, 10, "H02USERID");
    fields[1] = fieldH02PROGRM =
    new CharacterField(message, HEADERSIZE + 10, 10, "H02PROGRM");
    fields[2] = fieldH02TIMSYS =
    new CharacterField(message, HEADERSIZE + 20, 12, "H02TIMSYS");
    fields[3] = fieldH02SCRCOD =
    new CharacterField(message, HEADERSIZE + 32, 2, "H02SCRCOD");
    fields[4] = fieldH02OPECOD =
    new CharacterField(message, HEADERSIZE + 34, 4, "H02OPECOD");
    fields[5] = fieldH02FLGMAS =
    new CharacterField(message, HEADERSIZE + 38, 1, "H02FLGMAS");
    fields[6] = fieldH02FLGWK1 =
    new CharacterField(message, HEADERSIZE + 39, 1, "H02FLGWK1");
    fields[7] = fieldH02FLGWK2 =
    new CharacterField(message, HEADERSIZE + 40, 1, "H02FLGWK2");
    fields[8] = fieldH02FLGWK3 =
    new CharacterField(message, HEADERSIZE + 41, 1, "H02FLGWK3");
    fields[9] = fieldESRACC =
    new CharacterField(message, HEADERSIZE + 42, 1, "ESRACC");
    fields[10] = fieldESRIDN =
    new CharacterField(message, HEADERSIZE + 43, 15, "ESRIDN");
    fields[11] = fieldESRCAT =
    new CharacterField(message, HEADERSIZE + 58, 2, "ESRCAT");
    fields[12] = fieldESRCOD =
    new CharacterField(message, HEADERSIZE + 60, 4, "ESRCOD");
    fields[13] = fieldESRFIA =
    new DecimalField(message, HEADERSIZE + 64, 5, 0, "ESRFIA");
    fields[14] = fieldESRFIM =
    new DecimalField(message, HEADERSIZE + 69, 3, 0, "ESRFIM");
    fields[15] = fieldESRFID =
    new DecimalField(message, HEADERSIZE + 72, 3, 0, "ESRFID");
    fields[16] = fieldESRFTA =
    new DecimalField(message, HEADERSIZE + 75, 5, 0, "ESRFTA");
    fields[17] = fieldESRFTM =
    new DecimalField(message, HEADERSIZE + 80, 3, 0, "ESRFTM");
    fields[18] = fieldESRFTD =
    new DecimalField(message, HEADERSIZE + 83, 3, 0, "ESRFTD");
    fields[19] = fieldESRPRD =
    new CharacterField(message, HEADERSIZE + 86, 4, "ESRPRD");
    fields[20] = fieldESROPE =
    new CharacterField(message, HEADERSIZE + 90, 12, "ESROPE");
    fields[21] = fieldESRF1A =
    new DecimalField(message, HEADERSIZE + 102, 5, 0, "ESRF1A");
    fields[22] = fieldESRF1M =
    new DecimalField(message, HEADERSIZE + 107, 3, 0, "ESRF1M");
    fields[23] = fieldESRF1D =
    new DecimalField(message, HEADERSIZE + 110, 3, 0, "ESRF1D");
    fields[24] = fieldESRF2A =
    new DecimalField(message, HEADERSIZE + 113, 5, 0, "ESRF2A");
    fields[25] = fieldESRF2M =
    new DecimalField(message, HEADERSIZE + 118, 3, 0, "ESRF2M");
    fields[26] = fieldESRF2D =
    new DecimalField(message, HEADERSIZE + 121, 3, 0, "ESRF2D");
    fields[27] = fieldESRNU1 =
    new DecimalField(message, HEADERSIZE + 124, 19, 0, "ESRNU1");
    fields[28] = fieldESRNU2 =
    new DecimalField(message, HEADERSIZE + 143, 19, 0, "ESRNU2");
    fields[29] = fieldESRGL1 =
    new CharacterField(message, HEADERSIZE + 162, 20, "ESRGL1");
    fields[30] = fieldESRGL2 =
    new CharacterField(message, HEADERSIZE + 182, 20, "ESRGL2");
    fields[31] = fieldESRCAL =
    new CharacterField(message, HEADERSIZE + 202, 1, "ESRCAL");
    fields[32] = fieldESRORI =
    new CharacterField(message, HEADERSIZE + 203, 2, "ESRORI");
    fields[33] = fieldESRCOR =
    new CharacterField(message, HEADERSIZE + 205, 2, "ESRCOR");
    fields[34] = fieldESREST =
    new CharacterField(message, HEADERSIZE + 207, 1, "ESREST");
    fields[35] = fieldESRUSR =
    new CharacterField(message, HEADERSIZE + 208, 10, "ESRUSR");
    fields[36] = fieldESRPRI =
    new DecimalField(message, HEADERSIZE + 218, 2, 0, "ESRPRI");
    fields[37] = fieldESRXRT =
    new DecimalField(message, HEADERSIZE + 220, 2, 0, "ESRXRT");

    synchronized (tlookup)
    {
      if (tlookup.isEmpty())
      {
        for (int i = 0; i < tnames.length; i++)
          tlookup.put(tnames[i], new Integer(i));
      }
    }

    taglookup = tlookup;
  }

  /**
  * Set field H02USERID using a String value.
  */
  public void setH02USERID(String newvalue)
  {
    fieldH02USERID.setString(newvalue);
  }

  /**
  * Get value of field H02USERID as a String.
  */
  public String getH02USERID()
  {
    return fieldH02USERID.getString();
  }

  /**
  * Set field H02PROGRM using a String value.
  */
  public void setH02PROGRM(String newvalue)
  {
    fieldH02PROGRM.setString(newvalue);
  }

  /**
  * Get value of field H02PROGRM as a String.
  */
  public String getH02PROGRM()
  {
    return fieldH02PROGRM.getString();
  }

  /**
  * Set field H02TIMSYS using a String value.
  */
  public void setH02TIMSYS(String newvalue)
  {
    fieldH02TIMSYS.setString(newvalue);
  }

  /**
  * Get value of field H02TIMSYS as a String.
  */
  public String getH02TIMSYS()
  {
    return fieldH02TIMSYS.getString();
  }

  /**
  * Set field H02SCRCOD using a String value.
  */
  public void setH02SCRCOD(String newvalue)
  {
    fieldH02SCRCOD.setString(newvalue);
  }

  /**
  * Get value of field H02SCRCOD as a String.
  */
  public String getH02SCRCOD()
  {
    return fieldH02SCRCOD.getString();
  }

  /**
  * Set field H02OPECOD using a String value.
  */
  public void setH02OPECOD(String newvalue)
  {
    fieldH02OPECOD.setString(newvalue);
  }

  /**
  * Get value of field H02OPECOD as a String.
  */
  public String getH02OPECOD()
  {
    return fieldH02OPECOD.getString();
  }

  /**
  * Set field H02FLGMAS using a String value.
  */
  public void setH02FLGMAS(String newvalue)
  {
    fieldH02FLGMAS.setString(newvalue);
  }

  /**
  * Get value of field H02FLGMAS as a String.
  */
  public String getH02FLGMAS()
  {
    return fieldH02FLGMAS.getString();
  }

  /**
  * Set field H02FLGWK1 using a String value.
  */
  public void setH02FLGWK1(String newvalue)
  {
    fieldH02FLGWK1.setString(newvalue);
  }

  /**
  * Get value of field H02FLGWK1 as a String.
  */
  public String getH02FLGWK1()
  {
    return fieldH02FLGWK1.getString();
  }

  /**
  * Set field H02FLGWK2 using a String value.
  */
  public void setH02FLGWK2(String newvalue)
  {
    fieldH02FLGWK2.setString(newvalue);
  }

  /**
  * Get value of field H02FLGWK2 as a String.
  */
  public String getH02FLGWK2()
  {
    return fieldH02FLGWK2.getString();
  }

  /**
  * Set field H02FLGWK3 using a String value.
  */
  public void setH02FLGWK3(String newvalue)
  {
    fieldH02FLGWK3.setString(newvalue);
  }

  /**
  * Get value of field H02FLGWK3 as a String.
  */
  public String getH02FLGWK3()
  {
    return fieldH02FLGWK3.getString();
  }

  /**
  * Set field ESRACC using a String value.
  */
  public void setESRACC(String newvalue)
  {
    fieldESRACC.setString(newvalue);
  }

  /**
  * Get value of field ESRACC as a String.
  */
  public String getESRACC()
  {
    return fieldESRACC.getString();
  }

  /**
  * Set field ESRIDN using a String value.
  */
  public void setESRIDN(String newvalue)
  {
    fieldESRIDN.setString(newvalue);
  }

  /**
  * Get value of field ESRIDN as a String.
  */
  public String getESRIDN()
  {
    return fieldESRIDN.getString();
  }

  /**
  * Set field ESRCAT using a String value.
  */
  public void setESRCAT(String newvalue)
  {
    fieldESRCAT.setString(newvalue);
  }

  /**
  * Get value of field ESRCAT as a String.
  */
  public String getESRCAT()
  {
    return fieldESRCAT.getString();
  }

  /**
  * Set field ESRCOD using a String value.
  */
  public void setESRCOD(String newvalue)
  {
    fieldESRCOD.setString(newvalue);
  }

  /**
  * Get value of field ESRCOD as a String.
  */
  public String getESRCOD()
  {
    return fieldESRCOD.getString();
  }

  /**
  * Set field ESRFIA using a String value.
  */
  public void setESRFIA(String newvalue)
  {
    fieldESRFIA.setString(newvalue);
  }

  /**
  * Get value of field ESRFIA as a String.
  */
  public String getESRFIA()
  {
    return fieldESRFIA.getString();
  }

  /**
  * Set numeric field ESRFIA using a BigDecimal value.
  */
  public void setESRFIA(BigDecimal newvalue)
  {
    fieldESRFIA.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field ESRFIA as a BigDecimal.
  */
  public BigDecimal getBigDecimalESRFIA()
  {
    return fieldESRFIA.getBigDecimal();
  }

  /**
  * Set field ESRFIM using a String value.
  */
  public void setESRFIM(String newvalue)
  {
    fieldESRFIM.setString(newvalue);
  }

  /**
  * Get value of field ESRFIM as a String.
  */
  public String getESRFIM()
  {
    return fieldESRFIM.getString();
  }

  /**
  * Set numeric field ESRFIM using a BigDecimal value.
  */
  public void setESRFIM(BigDecimal newvalue)
  {
    fieldESRFIM.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field ESRFIM as a BigDecimal.
  */
  public BigDecimal getBigDecimalESRFIM()
  {
    return fieldESRFIM.getBigDecimal();
  }

  /**
  * Set field ESRFID using a String value.
  */
  public void setESRFID(String newvalue)
  {
    fieldESRFID.setString(newvalue);
  }

  /**
  * Get value of field ESRFID as a String.
  */
  public String getESRFID()
  {
    return fieldESRFID.getString();
  }

  /**
  * Set numeric field ESRFID using a BigDecimal value.
  */
  public void setESRFID(BigDecimal newvalue)
  {
    fieldESRFID.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field ESRFID as a BigDecimal.
  */
  public BigDecimal getBigDecimalESRFID()
  {
    return fieldESRFID.getBigDecimal();
  }

  /**
  * Set field ESRFTA using a String value.
  */
  public void setESRFTA(String newvalue)
  {
    fieldESRFTA.setString(newvalue);
  }

  /**
  * Get value of field ESRFTA as a String.
  */
  public String getESRFTA()
  {
    return fieldESRFTA.getString();
  }

  /**
  * Set numeric field ESRFTA using a BigDecimal value.
  */
  public void setESRFTA(BigDecimal newvalue)
  {
    fieldESRFTA.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field ESRFTA as a BigDecimal.
  */
  public BigDecimal getBigDecimalESRFTA()
  {
    return fieldESRFTA.getBigDecimal();
  }

  /**
  * Set field ESRFTM using a String value.
  */
  public void setESRFTM(String newvalue)
  {
    fieldESRFTM.setString(newvalue);
  }

  /**
  * Get value of field ESRFTM as a String.
  */
  public String getESRFTM()
  {
    return fieldESRFTM.getString();
  }

  /**
  * Set numeric field ESRFTM using a BigDecimal value.
  */
  public void setESRFTM(BigDecimal newvalue)
  {
    fieldESRFTM.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field ESRFTM as a BigDecimal.
  */
  public BigDecimal getBigDecimalESRFTM()
  {
    return fieldESRFTM.getBigDecimal();
  }

  /**
  * Set field ESRFTD using a String value.
  */
  public void setESRFTD(String newvalue)
  {
    fieldESRFTD.setString(newvalue);
  }

  /**
  * Get value of field ESRFTD as a String.
  */
  public String getESRFTD()
  {
    return fieldESRFTD.getString();
  }

  /**
  * Set numeric field ESRFTD using a BigDecimal value.
  */
  public void setESRFTD(BigDecimal newvalue)
  {
    fieldESRFTD.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field ESRFTD as a BigDecimal.
  */
  public BigDecimal getBigDecimalESRFTD()
  {
    return fieldESRFTD.getBigDecimal();
  }

  /**
  * Set field ESRPRD using a String value.
  */
  public void setESRPRD(String newvalue)
  {
    fieldESRPRD.setString(newvalue);
  }

  /**
  * Get value of field ESRPRD as a String.
  */
  public String getESRPRD()
  {
    return fieldESRPRD.getString();
  }

  /**
  * Set field ESROPE using a String value.
  */
  public void setESROPE(String newvalue)
  {
    fieldESROPE.setString(newvalue);
  }

  /**
  * Get value of field ESROPE as a String.
  */
  public String getESROPE()
  {
    return fieldESROPE.getString();
  }

  /**
  * Set field ESRF1A using a String value.
  */
  public void setESRF1A(String newvalue)
  {
    fieldESRF1A.setString(newvalue);
  }

  /**
  * Get value of field ESRF1A as a String.
  */
  public String getESRF1A()
  {
    return fieldESRF1A.getString();
  }

  /**
  * Set numeric field ESRF1A using a BigDecimal value.
  */
  public void setESRF1A(BigDecimal newvalue)
  {
    fieldESRF1A.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field ESRF1A as a BigDecimal.
  */
  public BigDecimal getBigDecimalESRF1A()
  {
    return fieldESRF1A.getBigDecimal();
  }

  /**
  * Set field ESRF1M using a String value.
  */
  public void setESRF1M(String newvalue)
  {
    fieldESRF1M.setString(newvalue);
  }

  /**
  * Get value of field ESRF1M as a String.
  */
  public String getESRF1M()
  {
    return fieldESRF1M.getString();
  }

  /**
  * Set numeric field ESRF1M using a BigDecimal value.
  */
  public void setESRF1M(BigDecimal newvalue)
  {
    fieldESRF1M.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field ESRF1M as a BigDecimal.
  */
  public BigDecimal getBigDecimalESRF1M()
  {
    return fieldESRF1M.getBigDecimal();
  }

  /**
  * Set field ESRF1D using a String value.
  */
  public void setESRF1D(String newvalue)
  {
    fieldESRF1D.setString(newvalue);
  }

  /**
  * Get value of field ESRF1D as a String.
  */
  public String getESRF1D()
  {
    return fieldESRF1D.getString();
  }

  /**
  * Set numeric field ESRF1D using a BigDecimal value.
  */
  public void setESRF1D(BigDecimal newvalue)
  {
    fieldESRF1D.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field ESRF1D as a BigDecimal.
  */
  public BigDecimal getBigDecimalESRF1D()
  {
    return fieldESRF1D.getBigDecimal();
  }

  /**
  * Set field ESRF2A using a String value.
  */
  public void setESRF2A(String newvalue)
  {
    fieldESRF2A.setString(newvalue);
  }

  /**
  * Get value of field ESRF2A as a String.
  */
  public String getESRF2A()
  {
    return fieldESRF2A.getString();
  }

  /**
  * Set numeric field ESRF2A using a BigDecimal value.
  */
  public void setESRF2A(BigDecimal newvalue)
  {
    fieldESRF2A.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field ESRF2A as a BigDecimal.
  */
  public BigDecimal getBigDecimalESRF2A()
  {
    return fieldESRF2A.getBigDecimal();
  }

  /**
  * Set field ESRF2M using a String value.
  */
  public void setESRF2M(String newvalue)
  {
    fieldESRF2M.setString(newvalue);
  }

  /**
  * Get value of field ESRF2M as a String.
  */
  public String getESRF2M()
  {
    return fieldESRF2M.getString();
  }

  /**
  * Set numeric field ESRF2M using a BigDecimal value.
  */
  public void setESRF2M(BigDecimal newvalue)
  {
    fieldESRF2M.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field ESRF2M as a BigDecimal.
  */
  public BigDecimal getBigDecimalESRF2M()
  {
    return fieldESRF2M.getBigDecimal();
  }

  /**
  * Set field ESRF2D using a String value.
  */
  public void setESRF2D(String newvalue)
  {
    fieldESRF2D.setString(newvalue);
  }

  /**
  * Get value of field ESRF2D as a String.
  */
  public String getESRF2D()
  {
    return fieldESRF2D.getString();
  }

  /**
  * Set numeric field ESRF2D using a BigDecimal value.
  */
  public void setESRF2D(BigDecimal newvalue)
  {
    fieldESRF2D.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field ESRF2D as a BigDecimal.
  */
  public BigDecimal getBigDecimalESRF2D()
  {
    return fieldESRF2D.getBigDecimal();
  }

  /**
  * Set field ESRNU1 using a String value.
  */
  public void setESRNU1(String newvalue)
  {
    fieldESRNU1.setString(newvalue);
  }

  /**
  * Get value of field ESRNU1 as a String.
  */
  public String getESRNU1()
  {
    return fieldESRNU1.getString();
  }

  /**
  * Set numeric field ESRNU1 using a BigDecimal value.
  */
  public void setESRNU1(BigDecimal newvalue)
  {
    fieldESRNU1.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field ESRNU1 as a BigDecimal.
  */
  public BigDecimal getBigDecimalESRNU1()
  {
    return fieldESRNU1.getBigDecimal();
  }

  /**
  * Set field ESRNU2 using a String value.
  */
  public void setESRNU2(String newvalue)
  {
    fieldESRNU2.setString(newvalue);
  }

  /**
  * Get value of field ESRNU2 as a String.
  */
  public String getESRNU2()
  {
    return fieldESRNU2.getString();
  }

  /**
  * Set numeric field ESRNU2 using a BigDecimal value.
  */
  public void setESRNU2(BigDecimal newvalue)
  {
    fieldESRNU2.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field ESRNU2 as a BigDecimal.
  */
  public BigDecimal getBigDecimalESRNU2()
  {
    return fieldESRNU2.getBigDecimal();
  }

  /**
  * Set field ESRGL1 using a String value.
  */
  public void setESRGL1(String newvalue)
  {
    fieldESRGL1.setString(newvalue);
  }

  /**
  * Get value of field ESRGL1 as a String.
  */
  public String getESRGL1()
  {
    return fieldESRGL1.getString();
  }

  /**
  * Set field ESRGL2 using a String value.
  */
  public void setESRGL2(String newvalue)
  {
    fieldESRGL2.setString(newvalue);
  }

  /**
  * Get value of field ESRGL2 as a String.
  */
  public String getESRGL2()
  {
    return fieldESRGL2.getString();
  }

  /**
  * Set field ESRCAL using a String value.
  */
  public void setESRCAL(String newvalue)
  {
    fieldESRCAL.setString(newvalue);
  }

  /**
  * Get value of field ESRCAL as a String.
  */
  public String getESRCAL()
  {
    return fieldESRCAL.getString();
  }

  /**
  * Set field ESRORI using a String value.
  */
  public void setESRORI(String newvalue)
  {
    fieldESRORI.setString(newvalue);
  }

  /**
  * Get value of field ESRORI as a String.
  */
  public String getESRORI()
  {
    return fieldESRORI.getString();
  }

  /**
  * Set field ESRCOR using a String value.
  */
  public void setESRCOR(String newvalue)
  {
    fieldESRCOR.setString(newvalue);
  }

  /**
  * Get value of field ESRCOR as a String.
  */
  public String getESRCOR()
  {
    return fieldESRCOR.getString();
  }

  /**
  * Set field ESREST using a String value.
  */
  public void setESREST(String newvalue)
  {
    fieldESREST.setString(newvalue);
  }

  /**
  * Get value of field ESREST as a String.
  */
  public String getESREST()
  {
    return fieldESREST.getString();
  }

  /**
  * Set field ESRUSR using a String value.
  */
  public void setESRUSR(String newvalue)
  {
    fieldESRUSR.setString(newvalue);
  }

  /**
  * Get value of field ESRUSR as a String.
  */
  public String getESRUSR()
  {
    return fieldESRUSR.getString();
  }

  /**
  * Set field ESRPRI using a String value.
  */
  public void setESRPRI(String newvalue)
  {
    fieldESRPRI.setString(newvalue);
  }

  /**
  * Get value of field ESRPRI as a String.
  */
  public String getESRPRI()
  {
    return fieldESRPRI.getString();
  }

  /**
  * Set numeric field ESRPRI using a BigDecimal value.
  */
  public void setESRPRI(BigDecimal newvalue)
  {
    fieldESRPRI.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field ESRPRI as a BigDecimal.
  */
  public BigDecimal getBigDecimalESRPRI()
  {
    return fieldESRPRI.getBigDecimal();
  }

  /**
  * Set field ESRXRT using a String value.
  */
  public void setESRXRT(String newvalue)
  {
    fieldESRXRT.setString(newvalue);
  }

  /**
  * Get value of field ESRXRT as a String.
  */
  public String getESRXRT()
  {
    return fieldESRXRT.getString();
  }

  /**
  * Set numeric field ESRXRT using a BigDecimal value.
  */
  public void setESRXRT(BigDecimal newvalue)
  {
    fieldESRXRT.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field ESRXRT as a BigDecimal.
  */
  public BigDecimal getBigDecimalESRXRT()
  {
    return fieldESRXRT.getBigDecimal();
  }

}
