package datapro.eibs.beans;

import datapro.eibs.sockets.*;
import java.io.*;
import java.math.*;

import java.util.*;

/**
* Class generated by AS/400 CRTCLASS command from EOC000106 physical file definition.
* 
* File level identifier is 1100706173634.
* Record format level identifier is 52D3668125C8B.
*/

public class EOC000106Message extends MessageRecord
{
  final static String fldnames[] = {
                                     "H01USERID",
                                     "H01PROGRM",
                                     "H01TIMSYS",
                                     "H01SCRCOD",
                                     "H01OPECOD",
                                     "H01FLGMAS",
                                     "H01FLGWK1",
                                     "H01FLGWK2",
                                     "H01FLGWK3",
                                     "CODACC",
                                     "ARMOFI",
                                     "ARMIDE",
                                     "ARMNID",
                                     "ARMCEJ",
                                     "ARMNMB",
                                     "ARMFEC",
                                     "ACMNPL",
                                     "ACMACC",
                                     "ACMMTO",
                                     "ACMMND",
                                     "ACMPAI",
                                     "ACMPAR",
                                     "ACMTCB",
                                     "ACMMEP",
                                     "ACMMED",
                                     "ACMCCO",
                                     "ACMFVA",
                                     "ACMCB1",
                                     "ACMCM1",
                                     "ACMCN1",
                                     "ACMCR1",
                                     "ACMOBS",
                                     "AVMNPL",
                                     "AVMACC",
                                     "AVMMTO",
                                     "AVMMND",
                                     "AVMPAI",
                                     "AVMPAR",
                                     "AVMTCB",
                                     "AVMMEP",
                                     "AVMMED",
                                     "AVMCCO",
                                     "AVMFVA",
                                     "AVMAB1",
                                     "AVMAM1",
                                     "AVMAN1",
                                     "AVMAR1",
                                     "AVMCIT",
                                     "AVMGTL",
                                     "AVMCMI",
                                     "AVMPCM",
                                     "AVMTCM",
                                     "AVMOBS",
                                     "AVMFPA",
                                     "AVMFPN",
                                     "AVMICO",
                                     "AVMITL",
                                     "AVMOF1",
                                     "AVMOF2",
                                     "AVMOF3"
                                   };
  final static String tnames[] = {
                                   "H01USERID",
                                   "H01PROGRM",
                                   "H01TIMSYS",
                                   "H01SCRCOD",
                                   "H01OPECOD",
                                   "H01FLGMAS",
                                   "H01FLGWK1",
                                   "H01FLGWK2",
                                   "H01FLGWK3",
                                   "CODACC",
                                   "ARMOFI",
                                   "ARMIDE",
                                   "ARMNID",
                                   "ARMCEJ",
                                   "ARMNMB",
                                   "ARMFEC",
                                   "ACMNPL",
                                   "ACMACC",
                                   "ACMMTO",
                                   "ACMMND",
                                   "ACMPAI",
                                   "ACMPAR",
                                   "ACMTCB",
                                   "ACMMEP",
                                   "ACMMED",
                                   "ACMCCO",
                                   "ACMFVA",
                                   "ACMCB1",
                                   "ACMCM1",
                                   "ACMCN1",
                                   "ACMCR1",
                                   "ACMOBS",
                                   "AVMNPL",
                                   "AVMACC",
                                   "AVMMTO",
                                   "AVMMND",
                                   "AVMPAI",
                                   "AVMPAR",
                                   "AVMTCB",
                                   "AVMMEP",
                                   "AVMMED",
                                   "AVMCCO",
                                   "AVMFVA",
                                   "AVMAB1",
                                   "AVMAM1",
                                   "AVMAN1",
                                   "AVMAR1",
                                   "AVMCIT",
                                   "AVMGTL",
                                   "AVMCMI",
                                   "AVMPCM",
                                   "AVMTCM",
                                   "AVMOBS",
                                   "AVMFPA",
                                   "AVMFPN",
                                   "AVMICO",
                                   "AVMITL",
                                   "AVMOF1",
                                   "AVMOF2",
                                   "AVMOF3"
                                 };
  final static String fid = "1100706173634";
  final static String rid = "52D3668125C8B";
  final static String fmtname = "EOC000106";
  final int FIELDCOUNT = 60;
  private static Hashtable tlookup = new Hashtable();
  private CharacterField fieldH01USERID = null;
  private CharacterField fieldH01PROGRM = null;
  private CharacterField fieldH01TIMSYS = null;
  private CharacterField fieldH01SCRCOD = null;
  private CharacterField fieldH01OPECOD = null;
  private CharacterField fieldH01FLGMAS = null;
  private CharacterField fieldH01FLGWK1 = null;
  private CharacterField fieldH01FLGWK2 = null;
  private CharacterField fieldH01FLGWK3 = null;
  private CharacterField fieldCODACC = null;
  private DecimalField fieldARMOFI = null;
  private CharacterField fieldARMIDE = null;
  private DecimalField fieldARMNID = null;
  private CharacterField fieldARMCEJ = null;
  private CharacterField fieldARMNMB = null;
  private DecimalField fieldARMFEC = null;
  private DecimalField fieldACMNPL = null;
  private DecimalField fieldACMACC = null;
  private DecimalField fieldACMMTO = null;
  private CharacterField fieldACMMND = null;
  private CharacterField fieldACMPAI = null;
  private DecimalField fieldACMPAR = null;
  private DecimalField fieldACMTCB = null;
  private DecimalField fieldACMMEP = null;
  private DecimalField fieldACMMED = null;
  private DecimalField fieldACMCCO = null;
  private DecimalField fieldACMFVA = null;
  private CharacterField fieldACMCB1 = null;
  private DecimalField fieldACMCM1 = null;
  private CharacterField fieldACMCN1 = null;
  private CharacterField fieldACMCR1 = null;
  private CharacterField fieldACMOBS = null;
  private DecimalField fieldAVMNPL = null;
  private DecimalField fieldAVMACC = null;
  private DecimalField fieldAVMMTO = null;
  private CharacterField fieldAVMMND = null;
  private CharacterField fieldAVMPAI = null;
  private DecimalField fieldAVMPAR = null;
  private DecimalField fieldAVMTCB = null;
  private DecimalField fieldAVMMEP = null;
  private DecimalField fieldAVMMED = null;
  private DecimalField fieldAVMCCO = null;
  private DecimalField fieldAVMFVA = null;
  private CharacterField fieldAVMAB1 = null;
  private DecimalField fieldAVMAM1 = null;
  private CharacterField fieldAVMAN1 = null;
  private CharacterField fieldAVMAR1 = null;
  private DecimalField fieldAVMCIT = null;
  private DecimalField fieldAVMGTL = null;
  private DecimalField fieldAVMCMI = null;
  private DecimalField fieldAVMPCM = null;
  private DecimalField fieldAVMTCM = null;
  private CharacterField fieldAVMOBS = null;
  private CharacterField fieldAVMFPA = null;
  private CharacterField fieldAVMFPN = null;
  private DecimalField fieldAVMICO = null;
  private DecimalField fieldAVMITL = null;
  private DecimalField fieldAVMOF1 = null;
  private DecimalField fieldAVMOF2 = null;
  private DecimalField fieldAVMOF3 = null;

  /**
  * Constructor for EOC000106Message.
  */
  public EOC000106Message()
  {
    createFields();
    initialize();
  }

  /**
  * Create fields for this message.
  * This method implements the abstract method in the MessageRecord superclass.
  */
  protected void createFields()
  {
    recordsize = 942;
    fileid = fid;
    recordid = rid;
    message = new byte[getByteLength()];
    formatname = fmtname;
    fieldnames = fldnames;
    tagnames = tnames;
    fields = new MessageField[FIELDCOUNT];

    fields[0] = fieldH01USERID =
    new CharacterField(message, HEADERSIZE + 0, 10, "H01USERID");
    fields[1] = fieldH01PROGRM =
    new CharacterField(message, HEADERSIZE + 10, 10, "H01PROGRM");
    fields[2] = fieldH01TIMSYS =
    new CharacterField(message, HEADERSIZE + 20, 12, "H01TIMSYS");
    fields[3] = fieldH01SCRCOD =
    new CharacterField(message, HEADERSIZE + 32, 2, "H01SCRCOD");
    fields[4] = fieldH01OPECOD =
    new CharacterField(message, HEADERSIZE + 34, 4, "H01OPECOD");
    fields[5] = fieldH01FLGMAS =
    new CharacterField(message, HEADERSIZE + 38, 1, "H01FLGMAS");
    fields[6] = fieldH01FLGWK1 =
    new CharacterField(message, HEADERSIZE + 39, 1, "H01FLGWK1");
    fields[7] = fieldH01FLGWK2 =
    new CharacterField(message, HEADERSIZE + 40, 1, "H01FLGWK2");
    fields[8] = fieldH01FLGWK3 =
    new CharacterField(message, HEADERSIZE + 41, 1, "H01FLGWK3");
    fields[9] = fieldCODACC =
    new CharacterField(message, HEADERSIZE + 42, 1, "CODACC");
    fields[10] = fieldARMOFI =
    new DecimalField(message, HEADERSIZE + 43, 4, 0, "ARMOFI");
    fields[11] = fieldARMIDE =
    new CharacterField(message, HEADERSIZE + 47, 10, "ARMIDE");
    fields[12] = fieldARMNID =
    new DecimalField(message, HEADERSIZE + 57, 10, 0, "ARMNID");
    fields[13] = fieldARMCEJ =
    new CharacterField(message, HEADERSIZE + 67, 4, "ARMCEJ");
    fields[14] = fieldARMNMB =
    new CharacterField(message, HEADERSIZE + 71, 50, "ARMNMB");
    fields[15] = fieldARMFEC =
    new DecimalField(message, HEADERSIZE + 121, 9, 0, "ARMFEC");
    fields[16] = fieldACMNPL =
    new DecimalField(message, HEADERSIZE + 130, 7, 0, "ACMNPL");
    fields[17] = fieldACMACC =
    new DecimalField(message, HEADERSIZE + 137, 17, 0, "ACMACC");
    fields[18] = fieldACMMTO =
    new DecimalField(message, HEADERSIZE + 154, 16, 2, "ACMMTO");
    fields[19] = fieldACMMND =
    new CharacterField(message, HEADERSIZE + 170, 3, "ACMMND");
    fields[20] = fieldACMPAI =
    new CharacterField(message, HEADERSIZE + 173, 4, "ACMPAI");
    fields[21] = fieldACMPAR =
    new DecimalField(message, HEADERSIZE + 177, 11, 4, "ACMPAR");
    fields[22] = fieldACMTCB =
    new DecimalField(message, HEADERSIZE + 188, 10, 2, "ACMTCB");
    fields[23] = fieldACMMEP =
    new DecimalField(message, HEADERSIZE + 198, 16, 2, "ACMMEP");
    fields[24] = fieldACMMED =
    new DecimalField(message, HEADERSIZE + 214, 16, 2, "ACMMED");
    fields[25] = fieldACMCCO =
    new DecimalField(message, HEADERSIZE + 230, 7, 0, "ACMCCO");
    fields[26] = fieldACMFVA =
    new DecimalField(message, HEADERSIZE + 237, 9, 0, "ACMFVA");
    fields[27] = fieldACMCB1 =
    new CharacterField(message, HEADERSIZE + 246, 2, "ACMCB1");
    fields[28] = fieldACMCM1 =
    new DecimalField(message, HEADERSIZE + 248, 16, 2, "ACMCM1");
    fields[29] = fieldACMCN1 =
    new CharacterField(message, HEADERSIZE + 264, 12, "ACMCN1");
    fields[30] = fieldACMCR1 =
    new CharacterField(message, HEADERSIZE + 276, 10, "ACMCR1");
    fields[31] = fieldACMOBS =
    new CharacterField(message, HEADERSIZE + 286, 198, "ACMOBS");
    fields[32] = fieldAVMNPL =
    new DecimalField(message, HEADERSIZE + 484, 7, 0, "AVMNPL");
    fields[33] = fieldAVMACC =
    new DecimalField(message, HEADERSIZE + 491, 17, 0, "AVMACC");
    fields[34] = fieldAVMMTO =
    new DecimalField(message, HEADERSIZE + 508, 16, 2, "AVMMTO");
    fields[35] = fieldAVMMND =
    new CharacterField(message, HEADERSIZE + 524, 3, "AVMMND");
    fields[36] = fieldAVMPAI =
    new CharacterField(message, HEADERSIZE + 527, 4, "AVMPAI");
    fields[37] = fieldAVMPAR =
    new DecimalField(message, HEADERSIZE + 531, 11, 4, "AVMPAR");
    fields[38] = fieldAVMTCB =
    new DecimalField(message, HEADERSIZE + 542, 10, 2, "AVMTCB");
    fields[39] = fieldAVMMEP =
    new DecimalField(message, HEADERSIZE + 552, 16, 2, "AVMMEP");
    fields[40] = fieldAVMMED =
    new DecimalField(message, HEADERSIZE + 568, 16, 2, "AVMMED");
    fields[41] = fieldAVMCCO =
    new DecimalField(message, HEADERSIZE + 584, 7, 0, "AVMCCO");
    fields[42] = fieldAVMFVA =
    new DecimalField(message, HEADERSIZE + 591, 9, 0, "AVMFVA");
    fields[43] = fieldAVMAB1 =
    new CharacterField(message, HEADERSIZE + 600, 2, "AVMAB1");
    fields[44] = fieldAVMAM1 =
    new DecimalField(message, HEADERSIZE + 602, 16, 2, "AVMAM1");
    fields[45] = fieldAVMAN1 =
    new CharacterField(message, HEADERSIZE + 618, 12, "AVMAN1");
    fields[46] = fieldAVMAR1 =
    new CharacterField(message, HEADERSIZE + 630, 10, "AVMAR1");
    fields[47] = fieldAVMCIT =
    new DecimalField(message, HEADERSIZE + 640, 11, 0, "AVMCIT");
    fields[48] = fieldAVMGTL =
    new DecimalField(message, HEADERSIZE + 651, 11, 0, "AVMGTL");
    fields[49] = fieldAVMCMI =
    new DecimalField(message, HEADERSIZE + 662, 12, 2, "AVMCMI");
    fields[50] = fieldAVMPCM =
    new DecimalField(message, HEADERSIZE + 674, 6, 2, "AVMPCM");
    fields[51] = fieldAVMTCM =
    new DecimalField(message, HEADERSIZE + 680, 10, 0, "AVMTCM");
    fields[52] = fieldAVMOBS =
    new CharacterField(message, HEADERSIZE + 690, 198, "AVMOBS");
    fields[53] = fieldAVMFPA =
    new CharacterField(message, HEADERSIZE + 888, 2, "AVMFPA");
    fields[54] = fieldAVMFPN =
    new CharacterField(message, HEADERSIZE + 890, 12, "AVMFPN");
    fields[55] = fieldAVMICO =
    new DecimalField(message, HEADERSIZE + 902, 12, 2, "AVMICO");
    fields[56] = fieldAVMITL =
    new DecimalField(message, HEADERSIZE + 914, 16, 2, "AVMITL");
    fields[57] = fieldAVMOF1 =
    new DecimalField(message, HEADERSIZE + 930, 4, 0, "AVMOF1");
    fields[58] = fieldAVMOF2 =
    new DecimalField(message, HEADERSIZE + 934, 4, 0, "AVMOF2");
    fields[59] = fieldAVMOF3 =
    new DecimalField(message, HEADERSIZE + 938, 4, 0, "AVMOF3");

    synchronized (tlookup)
    {
      if (tlookup.isEmpty())
      {
        for (int i = 0; i < tnames.length; i++)
          tlookup.put(tnames[i], new Integer(i));
      }
    }

    taglookup = tlookup;
  }

  /**
  * Set field H01USERID using a String value.
  */
  public void setH01USERID(String newvalue)
  {
    fieldH01USERID.setString(newvalue);
  }

  /**
  * Get value of field H01USERID as a String.
  */
  public String getH01USERID()
  {
    return fieldH01USERID.getString();
  }

  /**
  * Set field H01PROGRM using a String value.
  */
  public void setH01PROGRM(String newvalue)
  {
    fieldH01PROGRM.setString(newvalue);
  }

  /**
  * Get value of field H01PROGRM as a String.
  */
  public String getH01PROGRM()
  {
    return fieldH01PROGRM.getString();
  }

  /**
  * Set field H01TIMSYS using a String value.
  */
  public void setH01TIMSYS(String newvalue)
  {
    fieldH01TIMSYS.setString(newvalue);
  }

  /**
  * Get value of field H01TIMSYS as a String.
  */
  public String getH01TIMSYS()
  {
    return fieldH01TIMSYS.getString();
  }

  /**
  * Set field H01SCRCOD using a String value.
  */
  public void setH01SCRCOD(String newvalue)
  {
    fieldH01SCRCOD.setString(newvalue);
  }

  /**
  * Get value of field H01SCRCOD as a String.
  */
  public String getH01SCRCOD()
  {
    return fieldH01SCRCOD.getString();
  }

  /**
  * Set field H01OPECOD using a String value.
  */
  public void setH01OPECOD(String newvalue)
  {
    fieldH01OPECOD.setString(newvalue);
  }

  /**
  * Get value of field H01OPECOD as a String.
  */
  public String getH01OPECOD()
  {
    return fieldH01OPECOD.getString();
  }

  /**
  * Set field H01FLGMAS using a String value.
  */
  public void setH01FLGMAS(String newvalue)
  {
    fieldH01FLGMAS.setString(newvalue);
  }

  /**
  * Get value of field H01FLGMAS as a String.
  */
  public String getH01FLGMAS()
  {
    return fieldH01FLGMAS.getString();
  }

  /**
  * Set field H01FLGWK1 using a String value.
  */
  public void setH01FLGWK1(String newvalue)
  {
    fieldH01FLGWK1.setString(newvalue);
  }

  /**
  * Get value of field H01FLGWK1 as a String.
  */
  public String getH01FLGWK1()
  {
    return fieldH01FLGWK1.getString();
  }

  /**
  * Set field H01FLGWK2 using a String value.
  */
  public void setH01FLGWK2(String newvalue)
  {
    fieldH01FLGWK2.setString(newvalue);
  }

  /**
  * Get value of field H01FLGWK2 as a String.
  */
  public String getH01FLGWK2()
  {
    return fieldH01FLGWK2.getString();
  }

  /**
  * Set field H01FLGWK3 using a String value.
  */
  public void setH01FLGWK3(String newvalue)
  {
    fieldH01FLGWK3.setString(newvalue);
  }

  /**
  * Get value of field H01FLGWK3 as a String.
  */
  public String getH01FLGWK3()
  {
    return fieldH01FLGWK3.getString();
  }

  /**
  * Set field CODACC using a String value.
  */
  public void setCODACC(String newvalue)
  {
    fieldCODACC.setString(newvalue);
  }

  /**
  * Get value of field CODACC as a String.
  */
  public String getCODACC()
  {
    return fieldCODACC.getString();
  }

  /**
  * Set field ARMOFI using a String value.
  */
  public void setARMOFI(String newvalue)
  {
    fieldARMOFI.setString(newvalue);
  }

  /**
  * Get value of field ARMOFI as a String.
  */
  public String getARMOFI()
  {
    return fieldARMOFI.getString();
  }

  /**
  * Set numeric field ARMOFI using a BigDecimal value.
  */
  public void setARMOFI(BigDecimal newvalue)
  {
    fieldARMOFI.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field ARMOFI as a BigDecimal.
  */
  public BigDecimal getBigDecimalARMOFI()
  {
    return fieldARMOFI.getBigDecimal();
  }

  /**
  * Set field ARMIDE using a String value.
  */
  public void setARMIDE(String newvalue)
  {
    fieldARMIDE.setString(newvalue);
  }

  /**
  * Get value of field ARMIDE as a String.
  */
  public String getARMIDE()
  {
    return fieldARMIDE.getString();
  }

  /**
  * Set field ARMNID using a String value.
  */
  public void setARMNID(String newvalue)
  {
    fieldARMNID.setString(newvalue);
  }

  /**
  * Get value of field ARMNID as a String.
  */
  public String getARMNID()
  {
    return fieldARMNID.getString();
  }

  /**
  * Set numeric field ARMNID using a BigDecimal value.
  */
  public void setARMNID(BigDecimal newvalue)
  {
    fieldARMNID.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field ARMNID as a BigDecimal.
  */
  public BigDecimal getBigDecimalARMNID()
  {
    return fieldARMNID.getBigDecimal();
  }

  /**
  * Set field ARMCEJ using a String value.
  */
  public void setARMCEJ(String newvalue)
  {
    fieldARMCEJ.setString(newvalue);
  }

  /**
  * Get value of field ARMCEJ as a String.
  */
  public String getARMCEJ()
  {
    return fieldARMCEJ.getString();
  }

  /**
  * Set field ARMNMB using a String value.
  */
  public void setARMNMB(String newvalue)
  {
    fieldARMNMB.setString(newvalue);
  }

  /**
  * Get value of field ARMNMB as a String.
  */
  public String getARMNMB()
  {
    return fieldARMNMB.getString();
  }

  /**
  * Set field ARMFEC using a String value.
  */
  public void setARMFEC(String newvalue)
  {
    fieldARMFEC.setString(newvalue);
  }

  /**
  * Get value of field ARMFEC as a String.
  */
  public String getARMFEC()
  {
    return fieldARMFEC.getString();
  }

  /**
  * Set numeric field ARMFEC using a BigDecimal value.
  */
  public void setARMFEC(BigDecimal newvalue)
  {
    fieldARMFEC.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field ARMFEC as a BigDecimal.
  */
  public BigDecimal getBigDecimalARMFEC()
  {
    return fieldARMFEC.getBigDecimal();
  }

  /**
  * Set field ACMNPL using a String value.
  */
  public void setACMNPL(String newvalue)
  {
    fieldACMNPL.setString(newvalue);
  }

  /**
  * Get value of field ACMNPL as a String.
  */
  public String getACMNPL()
  {
    return fieldACMNPL.getString();
  }

  /**
  * Set numeric field ACMNPL using a BigDecimal value.
  */
  public void setACMNPL(BigDecimal newvalue)
  {
    fieldACMNPL.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field ACMNPL as a BigDecimal.
  */
  public BigDecimal getBigDecimalACMNPL()
  {
    return fieldACMNPL.getBigDecimal();
  }

  /**
  * Set field ACMACC using a String value.
  */
  public void setACMACC(String newvalue)
  {
    fieldACMACC.setString(newvalue);
  }

  /**
  * Get value of field ACMACC as a String.
  */
  public String getACMACC()
  {
    return fieldACMACC.getString();
  }

  /**
  * Set numeric field ACMACC using a BigDecimal value.
  */
  public void setACMACC(BigDecimal newvalue)
  {
    fieldACMACC.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field ACMACC as a BigDecimal.
  */
  public BigDecimal getBigDecimalACMACC()
  {
    return fieldACMACC.getBigDecimal();
  }

  /**
  * Set field ACMMTO using a String value.
  */
  public void setACMMTO(String newvalue)
  {
    fieldACMMTO.setString(newvalue);
  }

  /**
  * Get value of field ACMMTO as a String.
  */
  public String getACMMTO()
  {
    return fieldACMMTO.getString();
  }

  /**
  * Set numeric field ACMMTO using a BigDecimal value.
  */
  public void setACMMTO(BigDecimal newvalue)
  {
    fieldACMMTO.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field ACMMTO as a BigDecimal.
  */
  public BigDecimal getBigDecimalACMMTO()
  {
    return fieldACMMTO.getBigDecimal();
  }

  /**
  * Set field ACMMND using a String value.
  */
  public void setACMMND(String newvalue)
  {
    fieldACMMND.setString(newvalue);
  }

  /**
  * Get value of field ACMMND as a String.
  */
  public String getACMMND()
  {
    return fieldACMMND.getString();
  }

  /**
  * Set field ACMPAI using a String value.
  */
  public void setACMPAI(String newvalue)
  {
    fieldACMPAI.setString(newvalue);
  }

  /**
  * Get value of field ACMPAI as a String.
  */
  public String getACMPAI()
  {
    return fieldACMPAI.getString();
  }

  /**
  * Set field ACMPAR using a String value.
  */
  public void setACMPAR(String newvalue)
  {
    fieldACMPAR.setString(newvalue);
  }

  /**
  * Get value of field ACMPAR as a String.
  */
  public String getACMPAR()
  {
    return fieldACMPAR.getString();
  }

  /**
  * Set numeric field ACMPAR using a BigDecimal value.
  */
  public void setACMPAR(BigDecimal newvalue)
  {
    fieldACMPAR.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field ACMPAR as a BigDecimal.
  */
  public BigDecimal getBigDecimalACMPAR()
  {
    return fieldACMPAR.getBigDecimal();
  }

  /**
  * Set field ACMTCB using a String value.
  */
  public void setACMTCB(String newvalue)
  {
    fieldACMTCB.setString(newvalue);
  }

  /**
  * Get value of field ACMTCB as a String.
  */
  public String getACMTCB()
  {
    return fieldACMTCB.getString();
  }

  /**
  * Set numeric field ACMTCB using a BigDecimal value.
  */
  public void setACMTCB(BigDecimal newvalue)
  {
    fieldACMTCB.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field ACMTCB as a BigDecimal.
  */
  public BigDecimal getBigDecimalACMTCB()
  {
    return fieldACMTCB.getBigDecimal();
  }

  /**
  * Set field ACMMEP using a String value.
  */
  public void setACMMEP(String newvalue)
  {
    fieldACMMEP.setString(newvalue);
  }

  /**
  * Get value of field ACMMEP as a String.
  */
  public String getACMMEP()
  {
    return fieldACMMEP.getString();
  }

  /**
  * Set numeric field ACMMEP using a BigDecimal value.
  */
  public void setACMMEP(BigDecimal newvalue)
  {
    fieldACMMEP.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field ACMMEP as a BigDecimal.
  */
  public BigDecimal getBigDecimalACMMEP()
  {
    return fieldACMMEP.getBigDecimal();
  }

  /**
  * Set field ACMMED using a String value.
  */
  public void setACMMED(String newvalue)
  {
    fieldACMMED.setString(newvalue);
  }

  /**
  * Get value of field ACMMED as a String.
  */
  public String getACMMED()
  {
    return fieldACMMED.getString();
  }

  /**
  * Set numeric field ACMMED using a BigDecimal value.
  */
  public void setACMMED(BigDecimal newvalue)
  {
    fieldACMMED.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field ACMMED as a BigDecimal.
  */
  public BigDecimal getBigDecimalACMMED()
  {
    return fieldACMMED.getBigDecimal();
  }

  /**
  * Set field ACMCCO using a String value.
  */
  public void setACMCCO(String newvalue)
  {
    fieldACMCCO.setString(newvalue);
  }

  /**
  * Get value of field ACMCCO as a String.
  */
  public String getACMCCO()
  {
    return fieldACMCCO.getString();
  }

  /**
  * Set numeric field ACMCCO using a BigDecimal value.
  */
  public void setACMCCO(BigDecimal newvalue)
  {
    fieldACMCCO.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field ACMCCO as a BigDecimal.
  */
  public BigDecimal getBigDecimalACMCCO()
  {
    return fieldACMCCO.getBigDecimal();
  }

  /**
  * Set field ACMFVA using a String value.
  */
  public void setACMFVA(String newvalue)
  {
    fieldACMFVA.setString(newvalue);
  }

  /**
  * Get value of field ACMFVA as a String.
  */
  public String getACMFVA()
  {
    return fieldACMFVA.getString();
  }

  /**
  * Set numeric field ACMFVA using a BigDecimal value.
  */
  public void setACMFVA(BigDecimal newvalue)
  {
    fieldACMFVA.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field ACMFVA as a BigDecimal.
  */
  public BigDecimal getBigDecimalACMFVA()
  {
    return fieldACMFVA.getBigDecimal();
  }

  /**
  * Set field ACMCB1 using a String value.
  */
  public void setACMCB1(String newvalue)
  {
    fieldACMCB1.setString(newvalue);
  }

  /**
  * Get value of field ACMCB1 as a String.
  */
  public String getACMCB1()
  {
    return fieldACMCB1.getString();
  }

  /**
  * Set field ACMCM1 using a String value.
  */
  public void setACMCM1(String newvalue)
  {
    fieldACMCM1.setString(newvalue);
  }

  /**
  * Get value of field ACMCM1 as a String.
  */
  public String getACMCM1()
  {
    return fieldACMCM1.getString();
  }

  /**
  * Set numeric field ACMCM1 using a BigDecimal value.
  */
  public void setACMCM1(BigDecimal newvalue)
  {
    fieldACMCM1.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field ACMCM1 as a BigDecimal.
  */
  public BigDecimal getBigDecimalACMCM1()
  {
    return fieldACMCM1.getBigDecimal();
  }

  /**
  * Set field ACMCN1 using a String value.
  */
  public void setACMCN1(String newvalue)
  {
    fieldACMCN1.setString(newvalue);
  }

  /**
  * Get value of field ACMCN1 as a String.
  */
  public String getACMCN1()
  {
    return fieldACMCN1.getString();
  }

  /**
  * Set field ACMCR1 using a String value.
  */
  public void setACMCR1(String newvalue)
  {
    fieldACMCR1.setString(newvalue);
  }

  /**
  * Get value of field ACMCR1 as a String.
  */
  public String getACMCR1()
  {
    return fieldACMCR1.getString();
  }

  /**
  * Set field ACMOBS using a String value.
  */
  public void setACMOBS(String newvalue)
  {
    fieldACMOBS.setString(newvalue);
  }

  /**
  * Get value of field ACMOBS as a String.
  */
  public String getACMOBS()
  {
    return fieldACMOBS.getString();
  }

  /**
  * Set field AVMNPL using a String value.
  */
  public void setAVMNPL(String newvalue)
  {
    fieldAVMNPL.setString(newvalue);
  }

  /**
  * Get value of field AVMNPL as a String.
  */
  public String getAVMNPL()
  {
    return fieldAVMNPL.getString();
  }

  /**
  * Set numeric field AVMNPL using a BigDecimal value.
  */
  public void setAVMNPL(BigDecimal newvalue)
  {
    fieldAVMNPL.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field AVMNPL as a BigDecimal.
  */
  public BigDecimal getBigDecimalAVMNPL()
  {
    return fieldAVMNPL.getBigDecimal();
  }

  /**
  * Set field AVMACC using a String value.
  */
  public void setAVMACC(String newvalue)
  {
    fieldAVMACC.setString(newvalue);
  }

  /**
  * Get value of field AVMACC as a String.
  */
  public String getAVMACC()
  {
    return fieldAVMACC.getString();
  }

  /**
  * Set numeric field AVMACC using a BigDecimal value.
  */
  public void setAVMACC(BigDecimal newvalue)
  {
    fieldAVMACC.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field AVMACC as a BigDecimal.
  */
  public BigDecimal getBigDecimalAVMACC()
  {
    return fieldAVMACC.getBigDecimal();
  }

  /**
  * Set field AVMMTO using a String value.
  */
  public void setAVMMTO(String newvalue)
  {
    fieldAVMMTO.setString(newvalue);
  }

  /**
  * Get value of field AVMMTO as a String.
  */
  public String getAVMMTO()
  {
    return fieldAVMMTO.getString();
  }

  /**
  * Set numeric field AVMMTO using a BigDecimal value.
  */
  public void setAVMMTO(BigDecimal newvalue)
  {
    fieldAVMMTO.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field AVMMTO as a BigDecimal.
  */
  public BigDecimal getBigDecimalAVMMTO()
  {
    return fieldAVMMTO.getBigDecimal();
  }

  /**
  * Set field AVMMND using a String value.
  */
  public void setAVMMND(String newvalue)
  {
    fieldAVMMND.setString(newvalue);
  }

  /**
  * Get value of field AVMMND as a String.
  */
  public String getAVMMND()
  {
    return fieldAVMMND.getString();
  }

  /**
  * Set field AVMPAI using a String value.
  */
  public void setAVMPAI(String newvalue)
  {
    fieldAVMPAI.setString(newvalue);
  }

  /**
  * Get value of field AVMPAI as a String.
  */
  public String getAVMPAI()
  {
    return fieldAVMPAI.getString();
  }

  /**
  * Set field AVMPAR using a String value.
  */
  public void setAVMPAR(String newvalue)
  {
    fieldAVMPAR.setString(newvalue);
  }

  /**
  * Get value of field AVMPAR as a String.
  */
  public String getAVMPAR()
  {
    return fieldAVMPAR.getString();
  }

  /**
  * Set numeric field AVMPAR using a BigDecimal value.
  */
  public void setAVMPAR(BigDecimal newvalue)
  {
    fieldAVMPAR.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field AVMPAR as a BigDecimal.
  */
  public BigDecimal getBigDecimalAVMPAR()
  {
    return fieldAVMPAR.getBigDecimal();
  }

  /**
  * Set field AVMTCB using a String value.
  */
  public void setAVMTCB(String newvalue)
  {
    fieldAVMTCB.setString(newvalue);
  }

  /**
  * Get value of field AVMTCB as a String.
  */
  public String getAVMTCB()
  {
    return fieldAVMTCB.getString();
  }

  /**
  * Set numeric field AVMTCB using a BigDecimal value.
  */
  public void setAVMTCB(BigDecimal newvalue)
  {
    fieldAVMTCB.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field AVMTCB as a BigDecimal.
  */
  public BigDecimal getBigDecimalAVMTCB()
  {
    return fieldAVMTCB.getBigDecimal();
  }

  /**
  * Set field AVMMEP using a String value.
  */
  public void setAVMMEP(String newvalue)
  {
    fieldAVMMEP.setString(newvalue);
  }

  /**
  * Get value of field AVMMEP as a String.
  */
  public String getAVMMEP()
  {
    return fieldAVMMEP.getString();
  }

  /**
  * Set numeric field AVMMEP using a BigDecimal value.
  */
  public void setAVMMEP(BigDecimal newvalue)
  {
    fieldAVMMEP.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field AVMMEP as a BigDecimal.
  */
  public BigDecimal getBigDecimalAVMMEP()
  {
    return fieldAVMMEP.getBigDecimal();
  }

  /**
  * Set field AVMMED using a String value.
  */
  public void setAVMMED(String newvalue)
  {
    fieldAVMMED.setString(newvalue);
  }

  /**
  * Get value of field AVMMED as a String.
  */
  public String getAVMMED()
  {
    return fieldAVMMED.getString();
  }

  /**
  * Set numeric field AVMMED using a BigDecimal value.
  */
  public void setAVMMED(BigDecimal newvalue)
  {
    fieldAVMMED.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field AVMMED as a BigDecimal.
  */
  public BigDecimal getBigDecimalAVMMED()
  {
    return fieldAVMMED.getBigDecimal();
  }

  /**
  * Set field AVMCCO using a String value.
  */
  public void setAVMCCO(String newvalue)
  {
    fieldAVMCCO.setString(newvalue);
  }

  /**
  * Get value of field AVMCCO as a String.
  */
  public String getAVMCCO()
  {
    return fieldAVMCCO.getString();
  }

  /**
  * Set numeric field AVMCCO using a BigDecimal value.
  */
  public void setAVMCCO(BigDecimal newvalue)
  {
    fieldAVMCCO.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field AVMCCO as a BigDecimal.
  */
  public BigDecimal getBigDecimalAVMCCO()
  {
    return fieldAVMCCO.getBigDecimal();
  }

  /**
  * Set field AVMFVA using a String value.
  */
  public void setAVMFVA(String newvalue)
  {
    fieldAVMFVA.setString(newvalue);
  }

  /**
  * Get value of field AVMFVA as a String.
  */
  public String getAVMFVA()
  {
    return fieldAVMFVA.getString();
  }

  /**
  * Set numeric field AVMFVA using a BigDecimal value.
  */
  public void setAVMFVA(BigDecimal newvalue)
  {
    fieldAVMFVA.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field AVMFVA as a BigDecimal.
  */
  public BigDecimal getBigDecimalAVMFVA()
  {
    return fieldAVMFVA.getBigDecimal();
  }

  /**
  * Set field AVMAB1 using a String value.
  */
  public void setAVMAB1(String newvalue)
  {
    fieldAVMAB1.setString(newvalue);
  }

  /**
  * Get value of field AVMAB1 as a String.
  */
  public String getAVMAB1()
  {
    return fieldAVMAB1.getString();
  }

  /**
  * Set field AVMAM1 using a String value.
  */
  public void setAVMAM1(String newvalue)
  {
    fieldAVMAM1.setString(newvalue);
  }

  /**
  * Get value of field AVMAM1 as a String.
  */
  public String getAVMAM1()
  {
    return fieldAVMAM1.getString();
  }

  /**
  * Set numeric field AVMAM1 using a BigDecimal value.
  */
  public void setAVMAM1(BigDecimal newvalue)
  {
    fieldAVMAM1.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field AVMAM1 as a BigDecimal.
  */
  public BigDecimal getBigDecimalAVMAM1()
  {
    return fieldAVMAM1.getBigDecimal();
  }

  /**
  * Set field AVMAN1 using a String value.
  */
  public void setAVMAN1(String newvalue)
  {
    fieldAVMAN1.setString(newvalue);
  }

  /**
  * Get value of field AVMAN1 as a String.
  */
  public String getAVMAN1()
  {
    return fieldAVMAN1.getString();
  }

  /**
  * Set field AVMAR1 using a String value.
  */
  public void setAVMAR1(String newvalue)
  {
    fieldAVMAR1.setString(newvalue);
  }

  /**
  * Get value of field AVMAR1 as a String.
  */
  public String getAVMAR1()
  {
    return fieldAVMAR1.getString();
  }

  /**
  * Set field AVMCIT using a String value.
  */
  public void setAVMCIT(String newvalue)
  {
    fieldAVMCIT.setString(newvalue);
  }

  /**
  * Get value of field AVMCIT as a String.
  */
  public String getAVMCIT()
  {
    return fieldAVMCIT.getString();
  }

  /**
  * Set numeric field AVMCIT using a BigDecimal value.
  */
  public void setAVMCIT(BigDecimal newvalue)
  {
    fieldAVMCIT.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field AVMCIT as a BigDecimal.
  */
  public BigDecimal getBigDecimalAVMCIT()
  {
    return fieldAVMCIT.getBigDecimal();
  }

  /**
  * Set field AVMGTL using a String value.
  */
  public void setAVMGTL(String newvalue)
  {
    fieldAVMGTL.setString(newvalue);
  }

  /**
  * Get value of field AVMGTL as a String.
  */
  public String getAVMGTL()
  {
    return fieldAVMGTL.getString();
  }

  /**
  * Set numeric field AVMGTL using a BigDecimal value.
  */
  public void setAVMGTL(BigDecimal newvalue)
  {
    fieldAVMGTL.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field AVMGTL as a BigDecimal.
  */
  public BigDecimal getBigDecimalAVMGTL()
  {
    return fieldAVMGTL.getBigDecimal();
  }

  /**
  * Set field AVMCMI using a String value.
  */
  public void setAVMCMI(String newvalue)
  {
    fieldAVMCMI.setString(newvalue);
  }

  /**
  * Get value of field AVMCMI as a String.
  */
  public String getAVMCMI()
  {
    return fieldAVMCMI.getString();
  }

  /**
  * Set numeric field AVMCMI using a BigDecimal value.
  */
  public void setAVMCMI(BigDecimal newvalue)
  {
    fieldAVMCMI.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field AVMCMI as a BigDecimal.
  */
  public BigDecimal getBigDecimalAVMCMI()
  {
    return fieldAVMCMI.getBigDecimal();
  }

  /**
  * Set field AVMPCM using a String value.
  */
  public void setAVMPCM(String newvalue)
  {
    fieldAVMPCM.setString(newvalue);
  }

  /**
  * Get value of field AVMPCM as a String.
  */
  public String getAVMPCM()
  {
    return fieldAVMPCM.getString();
  }

  /**
  * Set numeric field AVMPCM using a BigDecimal value.
  */
  public void setAVMPCM(BigDecimal newvalue)
  {
    fieldAVMPCM.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field AVMPCM as a BigDecimal.
  */
  public BigDecimal getBigDecimalAVMPCM()
  {
    return fieldAVMPCM.getBigDecimal();
  }

  /**
  * Set field AVMTCM using a String value.
  */
  public void setAVMTCM(String newvalue)
  {
    fieldAVMTCM.setString(newvalue);
  }

  /**
  * Get value of field AVMTCM as a String.
  */
  public String getAVMTCM()
  {
    return fieldAVMTCM.getString();
  }

  /**
  * Set numeric field AVMTCM using a BigDecimal value.
  */
  public void setAVMTCM(BigDecimal newvalue)
  {
    fieldAVMTCM.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field AVMTCM as a BigDecimal.
  */
  public BigDecimal getBigDecimalAVMTCM()
  {
    return fieldAVMTCM.getBigDecimal();
  }

  /**
  * Set field AVMOBS using a String value.
  */
  public void setAVMOBS(String newvalue)
  {
    fieldAVMOBS.setString(newvalue);
  }

  /**
  * Get value of field AVMOBS as a String.
  */
  public String getAVMOBS()
  {
    return fieldAVMOBS.getString();
  }

  /**
  * Set field AVMFPA using a String value.
  */
  public void setAVMFPA(String newvalue)
  {
    fieldAVMFPA.setString(newvalue);
  }

  /**
  * Get value of field AVMFPA as a String.
  */
  public String getAVMFPA()
  {
    return fieldAVMFPA.getString();
  }

  /**
  * Set field AVMFPN using a String value.
  */
  public void setAVMFPN(String newvalue)
  {
    fieldAVMFPN.setString(newvalue);
  }

  /**
  * Get value of field AVMFPN as a String.
  */
  public String getAVMFPN()
  {
    return fieldAVMFPN.getString();
  }

  /**
  * Set field AVMICO using a String value.
  */
  public void setAVMICO(String newvalue)
  {
    fieldAVMICO.setString(newvalue);
  }

  /**
  * Get value of field AVMICO as a String.
  */
  public String getAVMICO()
  {
    return fieldAVMICO.getString();
  }

  /**
  * Set numeric field AVMICO using a BigDecimal value.
  */
  public void setAVMICO(BigDecimal newvalue)
  {
    fieldAVMICO.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field AVMICO as a BigDecimal.
  */
  public BigDecimal getBigDecimalAVMICO()
  {
    return fieldAVMICO.getBigDecimal();
  }

  /**
  * Set field AVMITL using a String value.
  */
  public void setAVMITL(String newvalue)
  {
    fieldAVMITL.setString(newvalue);
  }

  /**
  * Get value of field AVMITL as a String.
  */
  public String getAVMITL()
  {
    return fieldAVMITL.getString();
  }

  /**
  * Set numeric field AVMITL using a BigDecimal value.
  */
  public void setAVMITL(BigDecimal newvalue)
  {
    fieldAVMITL.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field AVMITL as a BigDecimal.
  */
  public BigDecimal getBigDecimalAVMITL()
  {
    return fieldAVMITL.getBigDecimal();
  }

  /**
  * Set field AVMOF1 using a String value.
  */
  public void setAVMOF1(String newvalue)
  {
    fieldAVMOF1.setString(newvalue);
  }

  /**
  * Get value of field AVMOF1 as a String.
  */
  public String getAVMOF1()
  {
    return fieldAVMOF1.getString();
  }

  /**
  * Set numeric field AVMOF1 using a BigDecimal value.
  */
  public void setAVMOF1(BigDecimal newvalue)
  {
    fieldAVMOF1.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field AVMOF1 as a BigDecimal.
  */
  public BigDecimal getBigDecimalAVMOF1()
  {
    return fieldAVMOF1.getBigDecimal();
  }

  /**
  * Set field AVMOF2 using a String value.
  */
  public void setAVMOF2(String newvalue)
  {
    fieldAVMOF2.setString(newvalue);
  }

  /**
  * Get value of field AVMOF2 as a String.
  */
  public String getAVMOF2()
  {
    return fieldAVMOF2.getString();
  }

  /**
  * Set numeric field AVMOF2 using a BigDecimal value.
  */
  public void setAVMOF2(BigDecimal newvalue)
  {
    fieldAVMOF2.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field AVMOF2 as a BigDecimal.
  */
  public BigDecimal getBigDecimalAVMOF2()
  {
    return fieldAVMOF2.getBigDecimal();
  }

  /**
  * Set field AVMOF3 using a String value.
  */
  public void setAVMOF3(String newvalue)
  {
    fieldAVMOF3.setString(newvalue);
  }

  /**
  * Get value of field AVMOF3 as a String.
  */
  public String getAVMOF3()
  {
    return fieldAVMOF3.getString();
  }

  /**
  * Set numeric field AVMOF3 using a BigDecimal value.
  */
  public void setAVMOF3(BigDecimal newvalue)
  {
    fieldAVMOF3.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field AVMOF3 as a BigDecimal.
  */
  public BigDecimal getBigDecimalAVMOF3()
  {
    return fieldAVMOF3.getBigDecimal();
  }

}
